import Link from "next/link";
import { requireAdminPage } from "../../lib/adminAuth";
import { resolveReviewAdapter, reviewDispatchConfigured } from "../../lib/automationReviewAdapters";
import { supabaseAdmin } from "../../lib/supabaseAdmin";

export const dynamic = "force-dynamic";

type QueueRow = { id: string | number; retailer: string; retailer_id: string | number | null; offer_id: string | number | null; product_title: string; variant_title: string | null; review_status: string; review_kind: string | null; operation_type: string | null; reason_codes: string; before_state: Record<string, unknown> | null; proposed_state: Record<string, unknown> | null; impact_summary: Record<string, unknown>; source_evidence: Record<string, unknown>; source_captured_at: string | null; expires_at: string | null; source_row_fingerprint: string; plan_fingerprint: string | null; workflow_run_url: string | null; artifact_url: string | null };
type ExecutionRow = { id: string; review_id: string | number; status: string; requested_at: string; run_url: string | null; last_checkpoint: string | null; error_code: string | null; error_message: string | null; postflight_hash: string | null; idempotency_result: string | null };
function value(input: string | string[] | undefined) { return Array.isArray(input) ? input[0] : input || ""; }
function safeUrl(input: string | null) { if (!input) return null; try { const parsed = new URL(input); return ["http:", "https:"].includes(parsed.protocol) ? parsed.toString() : null; } catch { return null; } }
function lifecycle(row: QueueRow) { return row.expires_at && new Date(row.expires_at).getTime() <= Date.now() && row.review_status === "PENDING" ? "EXPIRED" : row.review_status; }

export default async function AutomationReviewPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  await requireAdminPage();
  const params = await searchParams, status = value(params.status) || "PENDING", retailer = value(params.retailer), kind = value(params.kind), query = value(params.q).trim().toLowerCase();
  const page = Math.max(1, Number.parseInt(value(params.page) || "1", 10) || 1), pageSize = 50;
  let request = supabaseAdmin.from("product_match_review_queue").select("id,retailer,retailer_id,offer_id,product_title,variant_title,review_status,review_kind,operation_type,reason_codes,before_state,proposed_state,impact_summary,source_evidence,source_captured_at,expires_at,source_row_fingerprint,plan_fingerprint,workflow_run_url,artifact_url", { count: "exact" }).not("review_status", "is", null).order("updated_at", { ascending: false });
  if (status !== "ALL") request = request.eq("review_status", status);
  if (retailer) request = request.eq("retailer", retailer);
  if (kind) request = request.eq("review_kind", kind);
  const { data, error, count } = await request.range((page - 1) * pageSize, page * pageSize - 1);
  const loaded = (data || []) as QueueRow[], rows = query ? loaded.filter((row) => [row.product_title, row.variant_title, row.offer_id, row.operation_type].join(" ").toLowerCase().includes(query)) : loaded;
  const { data: executionData } = loaded.length ? await supabaseAdmin.from("automation_review_execution_requests").select("id,review_id,status,requested_at,run_url,last_checkpoint,error_code,error_message,postflight_hash,idempotency_result").in("review_id", loaded.map((row) => row.id)).order("requested_at", { ascending: false }) : { data: [] };
  const executionByReview = new Map<string, ExecutionRow>();
  for (const execution of (executionData || []) as ExecutionRow[]) if (!executionByReview.has(String(execution.review_id))) executionByReview.set(String(execution.review_id), execution);
  const dispatchConfigured = reviewDispatchConfigured();
  const retailers = Array.from(new Set(loaded.map((row) => row.retailer))).sort();
  return <main className="min-h-screen bg-zinc-50 px-6 py-10 text-zinc-950"><div className="mx-auto max-w-7xl">
    <header className="flex items-end justify-between gap-4 border-b border-zinc-200 pb-6"><div><p className="text-sm font-semibold uppercase tracking-wide text-zinc-500">Admin</p><h1 className="mt-2 text-3xl font-bold">Automation Review Queue</h1><p className="mt-3 max-w-3xl text-sm text-zinc-600">Decisions are audit-only. Catalogue changes can run only through the existing protected importer approval and executor RPCs.</p></div><Link href="/admin" className="rounded-lg border bg-white px-4 py-2 font-semibold">Admin</Link></header>
    <form className="mt-6 grid gap-3 rounded-lg border bg-white p-4 md:grid-cols-5"><input name="q" defaultValue={value(params.q)} placeholder="Product or offer ID" className="rounded-lg border px-3 py-2" /><select name="status" defaultValue={status} className="rounded-lg border px-3 py-2"><option>ALL</option>{["PENDING","APPROVED","REJECTED","IGNORED","EXPIRED","EXECUTING","EXECUTED","FAILED"].map((item) => <option key={item}>{item}</option>)}</select><select name="retailer" defaultValue={retailer} className="rounded-lg border px-3 py-2"><option value="">All retailers</option>{retailers.map((item) => <option key={item}>{item}</option>)}</select><select name="kind" defaultValue={kind} className="rounded-lg border px-3 py-2"><option value="">All reasons</option>{["IDENTITY_CONFLICT","COMMERCIAL_CHANGE","SOURCE_FAILURE","MAPPING_DRIFT","POLICY_REVIEW"].map((item) => <option key={item}>{item}</option>)}</select><button className="rounded-lg bg-zinc-950 px-4 py-2 font-semibold text-white">Filter</button></form>
    <form id="bulk-review" action="/admin/automation-review/decision" method="post" className="mt-4 flex flex-wrap items-center gap-3 rounded-lg border border-blue-200 bg-blue-50 p-4"><span className="font-semibold">Compatible selected rows:</span><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="confirmImpact" value="yes" />I confirm the exact displayed impact, fingerprint and expiry</label><button name="action" value="approve" className="rounded-lg bg-emerald-700 px-4 py-2 font-semibold text-white">Approve decision</button><button name="action" value="reject" className="rounded-lg bg-red-700 px-4 py-2 font-semibold text-white">Reject</button><button name="action" value="ignore" className="rounded-lg border bg-white px-4 py-2 font-semibold">Ignore</button></form>
    {error && <p className="mt-6 rounded-lg border border-red-200 bg-red-50 p-4 text-red-700">Queue read failed; no action is available.</p>}<p className="mt-6 text-sm text-zinc-600">{count || 0} matching rows · page {page}</p>
    <section className="mt-4 space-y-4">{rows.map((row) => { const workflow = safeUrl(row.workflow_run_url), artifact = safeUrl(row.artifact_url), current = lifecycle(row), resolved = resolveReviewAdapter(row.retailer_id, row.operation_type, row.reason_codes), execution = executionByReview.get(String(row.id)), adapterReady = Boolean(resolved.adapter && dispatchConfigured && row.plan_fingerprint), driftScope = String(row.source_evidence?.drift_scope || row.impact_summary?.drift_scope || "REVIEW_ROW"); return <article key={row.id} className="rounded-xl border bg-white p-5 shadow-sm">
      <div className="flex flex-wrap items-start justify-between gap-3"><div className="flex gap-3"><input form="bulk-review" type="checkbox" name="selection" value={`${row.id}:${row.source_row_fingerprint}`} disabled={current !== "PENDING"} aria-label={`Select offer ${row.offer_id}`} /><div><p className="text-sm font-semibold text-zinc-500">{row.retailer} · offer {row.offer_id || "unbound"}</p><h2 className="text-lg font-bold">{row.product_title}</h2><p className="text-sm text-zinc-600">{row.variant_title || "No variant title"}</p></div></div><div className="flex gap-2"><span className="rounded-full border px-3 py-1 text-sm font-semibold">{current}</span><span className="rounded-full border px-3 py-1 text-sm">{row.review_kind}</span></div></div>
      <dl className="mt-4 grid gap-3 text-sm md:grid-cols-4"><div><dt className="text-zinc-500">Operation</dt><dd className="font-semibold">{row.operation_type || "Unknown"}</dd></div><div><dt className="text-zinc-500">Reason</dt><dd>{row.reason_codes || "Not recorded"}</dd></div><div><dt className="text-zinc-500">Captured</dt><dd>{row.source_captured_at ? new Date(row.source_captured_at).toLocaleString("en-GB") : "Missing"}</dd></div><div><dt className="text-zinc-500">Expires</dt><dd>{row.expires_at ? new Date(row.expires_at).toLocaleString("en-GB") : "Missing (fail closed)"}</dd></div></dl>
      <div className="mt-4 grid gap-3 md:grid-cols-3"><pre className="overflow-auto rounded-lg bg-zinc-100 p-3 text-xs">Before{`\n`}{JSON.stringify(row.before_state, null, 2)}</pre><pre className="overflow-auto rounded-lg bg-zinc-100 p-3 text-xs">Proposed{`\n`}{JSON.stringify(row.proposed_state, null, 2)}</pre><pre className="overflow-auto rounded-lg bg-zinc-100 p-3 text-xs">Impact / source evidence{`\n`}{JSON.stringify({ impact: row.impact_summary, source: row.source_evidence }, null, 2)}</pre></div>
      <div className="mt-3 flex gap-4 text-sm font-semibold">{workflow && <a href={workflow} target="_blank" rel="noreferrer" className="underline">Workflow run</a>}{artifact && <a href={artifact} target="_blank" rel="noreferrer" className="underline">Artifact</a>}</div>
      <div className="mt-4 rounded-lg border bg-zinc-50 p-3 text-sm"><p className="font-semibold">Execution adapter: {resolved.adapter ? `${resolved.adapter.retailerSlug} · ${resolved.adapter.operations.join(", ")}` : "unsupported"}</p><p className="mt-1 text-zinc-600">Drift scope: {driftScope}</p><p className="mt-1 text-zinc-600">{!resolved.adapter ? resolved.reason : !row.plan_fingerprint ? "A sealed plan fingerprint is missing." : !dispatchConfigured ? "Protected workflow dispatch is not configured in the server environment." : `Protected workflow ${resolved.adapter.workflow}; per-row maximum ${resolved.adapter.maximumBatch}.`}</p></div>
      {execution && <div className="mt-3 rounded-lg border border-sky-200 bg-sky-50 p-3 text-sm"><p className="font-semibold">Execution history · {execution.status}</p><p>Request {execution.id} · checkpoint {execution.last_checkpoint || "not recorded"}</p>{safeUrl(execution.run_url) && <a href={safeUrl(execution.run_url)!} target="_blank" rel="noreferrer" className="font-semibold underline">Workflow run</a>}<p>Postflight: {execution.postflight_hash || "pending"} · idempotency: {execution.idempotency_result || "pending"}</p>{(execution.error_code || execution.error_message) && <p className="text-red-700">{execution.error_code}: {execution.error_message}</p>}</div>}
      {current === "PENDING" && <form action="/admin/automation-review/decision" method="post" className="mt-4 flex flex-wrap items-center gap-2 rounded-lg border p-3"><input type="hidden" name="selection" value={`${row.id}:${row.source_row_fingerprint}`} /><label className="flex items-center gap-2 rounded border px-3 py-2 text-sm"><input type="checkbox" name="confirmImpact" value="yes" />Confirm displayed impact, fingerprint and expiry</label><button name="action" value="approve" className="rounded bg-emerald-700 px-3 py-2 text-sm font-semibold text-white">Approve decision</button><button name="action" value="reject" className="rounded bg-red-700 px-3 py-2 text-sm font-semibold text-white">Reject</button><button name="action" value="ignore" className="rounded border px-3 py-2 text-sm font-semibold">Ignore</button>{["IDENTITY_CONFLICT","MAPPING_DRIFT"].includes(row.review_kind || "") && <><input name="binding" placeholder="product_id:variant_id" className="rounded border px-3 py-2 text-sm" /><button name="action" value="rebind" className="rounded border border-violet-500 px-3 py-2 text-sm font-semibold">Approve rebind decision</button></>}<label className="flex items-center gap-2 rounded border border-amber-300 px-3 py-2 text-sm"><input type="checkbox" name="confirmUnavailable" value="yes" />Source explicitly confirms unavailable</label><button name="action" value="unavailable" className="rounded bg-amber-700 px-3 py-2 text-sm font-semibold text-white">Approve unavailable decision</button></form>}
      {current === "APPROVED" && <form action="/admin/automation-review/execute" method="post" className="mt-4 rounded-lg border border-violet-200 bg-violet-50 p-3"><input type="hidden" name="selection" value={`${row.id}:${row.source_row_fingerprint}`} /><p className="mb-2 text-sm text-violet-900">Execution performs a fresh source and database revalidation. Approval alone has not changed the catalogue.</p><label className="mb-2 flex items-center gap-2 text-sm"><input type="checkbox" name="confirmExecution" value="yes" disabled={!adapterReady} />I confirm this exact one-row impact, fingerprint and expiry</label><button disabled={!adapterReady || Boolean(execution && ["QUEUED","DISPATCHED","EXECUTING","EXECUTED"].includes(execution.status))} className="rounded bg-violet-800 px-3 py-2 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:bg-zinc-400">Execute approved</button>{!adapterReady && <p className="mt-2 text-sm font-semibold text-amber-800">Execution unavailable: {!resolved.adapter ? resolved.reason : !row.plan_fingerprint ? "missing plan fingerprint" : "protected dispatcher credential missing"}</p>}</form>}
    </article>; })}</section>
    <nav className="mt-6 flex justify-between"><Link href={`?status=${encodeURIComponent(status)}&page=${Math.max(1,page-1)}`} className="rounded border bg-white px-4 py-2">Previous</Link><Link href={`?status=${encodeURIComponent(status)}&page=${page+1}`} className="rounded border bg-white px-4 py-2">Next</Link></nav>
  </div></main>;
}
