\if :{?staging_executor_test_database_confirmed}
\else
\quit
\endif
select 1/case when :'staging_executor_test_database_confirmed'='1' and current_database()=:'staging_executor_expected_database' and current_database() like 'supplementscout_stage2_test_atomic_import_staging_executor_%' then 1 else 0 end;

select set_config('app.safe_update','false',false);
select set_config('app.retailer_catalogue_staging_marker','1',false);
select set_config('app.retailer_catalogue_allow','1',false);

insert into public.retailer_catalogue_database_targets(id,target_environment,project_ref,database_identity,database_system_identifier,database_oid,is_active,attested_by)
select true,'STAGING','hxnrsyyqffztlvcrtgbf','supplementscout-staging:hxnrsyyqffztlvcrtgbf',system_identifier::text,(select oid from pg_database where datname=current_database()),true,'disposable-test-owner'
from pg_control_system();

do $$
begin
  if to_regprocedure('public.execute_local_retailer_catalogue_child(jsonb)') is not null then raise exception 'staging executor depends on Phase 3 local function'; end if;
  if public.retailer_catalogue_actual_database_target()->>'project_ref'<>'hxnrsyyqffztlvcrtgbf' then raise exception 'trusted staging identity failed'; end if;
  if not has_function_privilege('retailer_catalogue_staging_executor','public.execute_staging_retailer_catalogue_child(jsonb)','EXECUTE')
     or has_function_privilege('service_role','public.execute_staging_retailer_catalogue_child(jsonb)','EXECUTE')
     or has_table_privilege('retailer_catalogue_staging_executor','public.products','INSERT') then raise exception 'staging grants are unsafe'; end if;
  if not (select relrowsecurity and relforcerowsecurity from pg_class where oid='public.retailer_catalogue_staging_recovery_approvals'::regclass) then raise exception 'recovery approval RLS is not forced'; end if;
end $$;

insert into public.products(id,name,slug,brand,category,product_format,is_active) values(91,'Project AD Shredabull Untamed 2.0 50 Caps','project-ad-shredabull-untamed-2-0-50-caps','Project AD','Fat Burner','capsule',true) on conflict(id) do nothing;
insert into public.product_variants(id,product_id,variant_key,display_name,pack_count,product_format,is_active,is_default) values(39,91,'default','Default',1,'capsule',true,true) on conflict(id) do nothing;
insert into public.retailers(id,name,slug,website) values(2,'Other Retailer','other-retailer','https://other.invalid') on conflict(id) do nothing;
do $$ begin for i in 1..7 loop perform public.atomic_test_apply(public.atomic_test_safe_plan('staging-noop-seed-'||i,'staging-noop-seed-'||i)); end loop; end $$;

create table public.staging_test_context(key text primary key,value jsonb not null);
create table public.staging_guard_results(case_name text primary key,expected_code text not null,actual_code text not null,expected_summary text not null,business_delta jsonb not null,approval_unchanged boolean not null,child_state_unchanged boolean not null);
create table public.staging_recovery_results(case_name text primary key,expected_code text,actual_code text,result text not null,approval_unchanged boolean not null default true);

create or replace function public.staging_test_counts()
returns jsonb language sql stable as $$ select jsonb_build_object('retailers',(select count(*) from retailers))||public.retailer_catalogue_business_counts() $$;

create or replace function public.staging_test_wrap(p_source_id text,p_plan jsonb)
returns jsonb language sql as $$
  select jsonb_build_object('phase1_row_plan',jsonb_build_object('schema_version',1,'source_record_id',p_source_id,'fingerprints',jsonb_build_object('classification_record',p_plan#>>'{meta,source_row_fingerprint}','row_plan',encode(pg_catalog.sha256(convert_to(p_source_id||public.atomic_import_canonical_json(p_plan),'UTF8')),'hex'))),'atomic_plan',p_plan,'row_plan_fingerprint',encode(pg_catalog.sha256(convert_to(p_source_id||public.atomic_import_canonical_json(p_plan),'UTF8')),'hex'),'artifact_sha256',encode(pg_catalog.sha256(convert_to(public.atomic_import_canonical_json(p_plan),'UTF8')),'hex'))
$$;

create or replace function public.staging_test_reseal(p_request jsonb)
returns jsonb language sql as $$ select jsonb_set(p_request,'{request_fingerprint}',to_jsonb(public.retailer_catalogue_staging_request_fingerprint(p_request))) $$;

create or replace function public.staging_test_ledger_identifiers()
returns jsonb language sql stable as $$ select coalesce(jsonb_agg(value->>'identifier' order by (value->>'ordinal')::integer),'[]'::jsonb) from jsonb_array_elements(public.retailer_catalogue_actual_migration_ledger()->'migrations') $$;

create or replace function public.staging_test_package(p_case text,p_source text,p_canonical text,p_adapter text,p_policy text)
returns jsonb language plpgsql stable as $$
declare p jsonb;
begin
  p:=jsonb_build_object('schema_version',1,'package_id',gen_random_uuid(),'target_environment','STAGING','staging_project_ref','hxnrsyyqffztlvcrtgbf','staging_database_identity','supplementscout-staging:hxnrsyyqffztlvcrtgbf','fixture_id','jons-staging-canary-real-10-v1-20260717','fixture_fingerprint','2c62a82c169ee20fab8a86c125423aa50b2d9613283907c408726d4ed89981f5','fixture_build_commit','6f7eefb29f775e773bd0764664a0ba138993fa06','source_snapshot_fingerprint',p_source,'canonical_snapshot_fingerprint',p_canonical,'adapter_fingerprint',p_adapter,'policy_fingerprint',p_policy,'code_commit','7a1f768024d323aa1c64707697274267d5a1d00d','expected_migration_identifiers',public.staging_test_ledger_identifiers(),'expected_migration_ledger_fingerprint',public.retailer_catalogue_actual_migration_ledger_fingerprint(),'package_fingerprint',null);
  return jsonb_set(p,'{package_fingerprint}',to_jsonb(public.retailer_catalogue_staging_package_fingerprint(p)));
end $$;

create or replace function public.staging_test_single(p_case text,p_rows jsonb,p_expected jsonb,p_child_state text default 'APPROVED')
returns jsonb language plpgsql as $$
declare p_id uuid:=gen_random_uuid(); c_id uuid:=gen_random_uuid(); p_fp text:=encode(sha256(convert_to('p:'||p_case,'UTF8')),'hex'); c_fp text:=encode(sha256(convert_to('c:'||p_case,'UTF8')),'hex'); s_fp text:=encode(sha256(convert_to('s:'||p_case,'UTF8')),'hex'); can_fp text:=encode(sha256(convert_to('can:'||p_case,'UTF8')),'hex'); a_fp text:=encode(sha256(convert_to('a:'||p_case,'UTF8')),'hex'); pol_fp text:=encode(sha256(convert_to('pol:'||p_case,'UTF8')),'hex'); f_id uuid:=gen_random_uuid(); pkg jsonb; q jsonb; approval uuid:=gen_random_uuid();
begin
  pkg:=public.staging_test_package(p_case,s_fp,can_fp,a_fp,pol_fp);
  insert into retailer_catalogue_parent_plans(id,parent_plan_fingerprint,retailer_id,target_environment,source_snapshot_fingerprint,canonical_snapshot_fingerprint,adapter_fingerprint,policy_fingerprint,code_commit,expected_state_fingerprint,status,expected_deltas,plan_json,child_manifest,rollback_manifest,source_captured_at,canonical_snapshot_at,approval_id,approved_by,approved_at,approval_expires_at,created_by)
  values(p_id,p_fp,1,'STAGING',s_fp,can_fp,a_fp,pol_fp,pkg->>'code_commit',repeat('6',64),'APPROVED',p_expected,jsonb_build_object('fixture_fingerprint',pkg->>'fixture_fingerprint','package_fingerprint',pkg->>'package_fingerprint'),'[]',jsonb_build_object('rollback_fingerprint',repeat('7',64)),now(),now(),approval,'test-operator',now(),now()+interval '1 hour','test');
  insert into retailer_catalogue_child_plans(id,parent_plan_id,retailer_id,target_environment,child_plan_fingerprint,parent_plan_fingerprint,source_snapshot_fingerprint,canonical_snapshot_fingerprint,adapter_fingerprint,policy_fingerprint,code_commit,expected_state_fingerprint,batch_index,batch_count,dependency_group,rollback_group,record_ids,status,expected_deltas,plan_json,rollback_manifest,approval_id,approved_at,approval_expires_at,approval_consumed_at)
  values(c_id,p_id,1,'STAGING',c_fp,p_fp,s_fp,can_fp,a_fp,pol_fp,pkg->>'code_commit',repeat('6',64),0,1,'test:'||p_case,'test-recovery',(select jsonb_agg(ordinality::text) from jsonb_array_elements(p_rows) with ordinality),case when p_child_state in ('APPLIED','CONSUMED') then 'APPROVED' else p_child_state end,p_expected,'{}',jsonb_build_array(jsonb_build_object('ownership',jsonb_build_object('plan_owned_only',true))),gen_random_uuid(),now(),now()+interval '45 minutes',case when p_child_state='CONSUMED' then now() else null end);
  if p_child_state='APPLIED' then update retailer_catalogue_child_plans set status='APPLYING',approval_consumed_at=now() where id=c_id; update retailer_catalogue_child_plans set status='APPLIED' where id=c_id; end if;
  insert into retailer_catalogue_staging_fixture_approvals(id,package_id,package_fingerprint,fixture_id,fixture_fingerprint,fixture_build_commit,project_ref,database_identity,migration_ledger_fingerprint,expected_migration_identifiers,source_snapshot_fingerprint,canonical_snapshot_fingerprint,adapter_fingerprint,policy_fingerprint,code_commit,canonical_decisions,approved_by,approved_at,expires_at,consumed_at,parent_plan_id)
  values(f_id,(pkg->>'package_id')::uuid,pkg->>'package_fingerprint',pkg->>'fixture_id',pkg->>'fixture_fingerprint',pkg->>'fixture_build_commit',pkg->>'staging_project_ref',pkg->>'staging_database_identity',pkg->>'expected_migration_ledger_fingerprint',pkg->'expected_migration_identifiers',s_fp,can_fp,a_fp,pol_fp,pkg->>'code_commit','{}','test-operator',now(),now()+interval '1 hour',now(),p_id);
  q:=jsonb_build_object('schema_version',1,'target_environment','STAGING','staging_project_ref','hxnrsyyqffztlvcrtgbf','staging_database_identity','supplementscout-staging:hxnrsyyqffztlvcrtgbf','package_id',pkg->>'package_id','package_fingerprint',pkg->>'package_fingerprint','parent_plan_id',p_id,'child_plan_id',c_id,'fixture_id',pkg->>'fixture_id','fixture_fingerprint',pkg->>'fixture_fingerprint','fixture_approval_id',f_id,'parent_plan_fingerprint',p_fp,'child_plan_fingerprint',c_fp,'source_snapshot_fingerprint',s_fp,'canonical_snapshot_fingerprint',can_fp,'migration_ledger_fingerprint',pkg->>'expected_migration_ledger_fingerprint','adapter_fingerprint',a_fp,'policy_fingerprint',pol_fp,'code_commit',pkg->>'code_commit','expected_deltas',p_expected,'row_plans',p_rows,'approval_expiry',now()+interval '30 minutes','requested_at',now(),'explicit_allow',true,'request_fingerprint',null);
  return public.staging_test_reseal(q);
end $$;

create or replace function public.staging_test_assert_guard(p_case text,p_request jsonb,p_expected_code text,p_expected_summary text)
returns void language plpgsql security definer as $$
declare before_counts jsonb:=public.staging_test_counts(); after_counts jsonb; before_status text; after_status text; before_consumed timestamptz; after_consumed timestamptz; actual_code text; caught boolean:=false;
begin
  select status,approval_consumed_at into before_status,before_consumed from retailer_catalogue_child_plans where id=(p_request->>'child_plan_id')::uuid;
  begin perform public.retailer_catalogue_execute_staging_child_internal(p_request); exception when others then caught:=true; actual_code:=substring(sqlerrm from 'RSBI_[A-Z_]+'); if actual_code is distinct from p_expected_code or position(p_expected_summary in sqlerrm)=0 then raise exception 'guard % got unexpected error: %',p_case,sqlerrm; end if; end;
  if not caught then raise exception 'guard % accepted invalid request',p_case; end if;
  after_counts:=public.staging_test_counts(); select status,approval_consumed_at into after_status,after_consumed from retailer_catalogue_child_plans where id=(p_request->>'child_plan_id')::uuid;
  if after_counts is distinct from before_counts or after_status is distinct from before_status or after_consumed is distinct from before_consumed then raise exception 'guard % changed state',p_case; end if;
  insert into staging_guard_results values(p_case,p_expected_code,actual_code,p_expected_summary,jsonb_build_object('retailers',0,'products',0,'product_variants',0,'retailer_products',0,'offers',0,'price_history',0),true,true);
end $$;

-- Positive committed children: two canonical creations, shared Project AD offer, and seven noops.
do $$ declare q jsonb; r jsonb; rows jsonb; source_ids text[]:=array['53868239389010','53868239421778','53868239454546','53868239487314','53868239520082','53896427798866','50927006581074']; begin
  rows:=jsonb_build_array(public.staging_test_wrap('50844992602450',public.atomic_test_safe_plan('tbjp-heart-care-150-capsules','50844992602450','capsule'))); q:=public.staging_test_single('main-1',rows,'{"retailers":0,"products":1,"product_variants":1,"retailer_products":1,"offers":1,"price_history":1}'); r:=public.retailer_catalogue_execute_staging_child_internal(q); if r->>'child_status'<>'APPLIED' then raise exception 'main child 1 failed: %',r; end if; insert into staging_test_context values('request1',q),('result1',r);
  rows:=jsonb_build_array(public.staging_test_wrap('53951719768402',public.atomic_test_safe_plan('conteh-sports-creatine-monohydrate-1kg','53951719768402','powder'))); q:=public.staging_test_single('main-2',rows,'{"retailers":0,"products":1,"product_variants":1,"retailer_products":1,"offers":1,"price_history":1}'); r:=public.retailer_catalogue_execute_staging_child_internal(q); if r->>'child_status'<>'APPLIED' then raise exception 'main child 2 failed: %',r; end if; insert into staging_test_context values('request2',q),('result2',r);
  rows:=jsonb_build_array(public.staging_test_wrap('51935656018258',public.atomic_test_existing_plan('project-ad-shredabull-untamed-2','51935656018258',91,39))); q:=public.staging_test_single('main-3',rows,'{"retailers":0,"products":0,"product_variants":0,"retailer_products":1,"offers":1,"price_history":1}'); r:=public.retailer_catalogue_execute_staging_child_internal(q); if r->>'child_status'<>'APPLIED' or (r#>>'{row_results,0,product_id}')::bigint<>91 then raise exception 'main child 3 failed: %',r; end if; insert into staging_test_context values('request3',q),('result3',r);
  rows:='[]'; for i in 1..7 loop rows:=rows||jsonb_build_array(public.staging_test_wrap(source_ids[i],public.atomic_test_current_plan('staging-noop-seed-'||i))); end loop; q:=public.staging_test_single('main-4',rows,'{"retailers":0,"products":0,"product_variants":0,"retailer_products":0,"offers":0,"price_history":0}'); r:=public.retailer_catalogue_execute_staging_child_internal(q); if r->>'child_status'<>'APPLIED' then raise exception 'main child 4 failed: %',r; end if; insert into staging_test_context values('request4',q),('result4',r);
end $$;

-- Transactional atomic failures still roll back all row approvals and business rows.
do $$ declare rows jsonb; q jsonb; r jsonb; n bigint; begin
  rows:=jsonb_build_array(public.staging_test_wrap('50844992602450',public.atomic_test_safe_plan('staging-mid-row-a','staging-mid-row-duplicate')),public.staging_test_wrap('53951719768402',public.atomic_test_safe_plan('staging-mid-row-b','staging-mid-row-duplicate'))); q:=public.staging_test_single('mid-row',rows,'{"retailers":0,"products":2,"product_variants":2,"retailer_products":2,"offers":2,"price_history":2}'); select count(*) into n from approved_import_plans; r:=public.retailer_catalogue_execute_staging_child_internal(q); if r->>'child_status'<>'FAILED' or exists(select 1 from products where slug like 'staging-mid-row-%') or (select count(*) from approved_import_plans)<>n then raise exception 'mid-row rollback failed: %',r; end if;
  rows:=jsonb_build_array(public.staging_test_wrap('50844992602450',public.atomic_test_safe_plan('staging-delta-mismatch','staging-delta-mismatch'))); q:=public.staging_test_single('delta-mismatch',rows,'{"retailers":0,"products":2,"product_variants":1,"retailer_products":1,"offers":1,"price_history":1}'); r:=public.retailer_catalogue_execute_staging_child_internal(q); if r->>'error_code'<>'RSBI_EXPECTED_STATE_MISMATCH' or exists(select 1 from products where slug='staging-delta-mismatch') then raise exception 'delta mismatch rollback failed: %',r; end if;
end $$;

-- Nineteen isolated guard cases. Every request is resealed after exactly one mutation.
do $$ declare q jsonb; bad jsonb; rows jsonb; begin
  rows:=jsonb_build_array(public.staging_test_wrap('50844992602450',public.atomic_test_safe_plan('guard-base','guard-base')));
  q:=public.staging_test_single('wrong-project-ref',rows,'{"retailers":0,"products":1,"product_variants":1,"retailer_products":1,"offers":1,"price_history":1}'); bad:=public.staging_test_reseal(jsonb_set(q,'{staging_project_ref}','"unknownprojectrefxxxx"')); perform public.staging_test_assert_guard('wrong_project_ref',bad,'RSBI_ENVIRONMENT_BLOCKED','Project ref is not the exact staging ref');
  q:=public.staging_test_single('production-ref',rows,'{"retailers":0,"products":1,"product_variants":1,"retailer_products":1,"offers":1,"price_history":1}'); bad:=public.staging_test_reseal(jsonb_set(q,'{staging_project_ref}','"aftboxmrdgyhizicfsfu"')); perform public.staging_test_assert_guard('production_ref',bad,'RSBI_ENVIRONMENT_BLOCKED','Project ref is not the exact staging ref');
  q:=public.staging_test_single('wrong-db',rows,'{"retailers":0,"products":1,"product_variants":1,"retailer_products":1,"offers":1,"price_history":1}'); bad:=public.staging_test_reseal(jsonb_set(q,'{staging_database_identity}','"wrong"')); perform public.staging_test_assert_guard('wrong_database_identity',bad,'RSBI_ENVIRONMENT_BLOCKED','Requested database identity is not staging');
  q:=public.staging_test_single('wrong-ledger',rows,'{"retailers":0,"products":1,"product_variants":1,"retailer_products":1,"offers":1,"price_history":1}'); bad:=public.staging_test_reseal(jsonb_set(q,'{migration_ledger_fingerprint}',to_jsonb(repeat('0',64)))); perform public.staging_test_assert_guard('wrong_migration_fingerprint',bad,'RSBI_SOURCE_HASH_MISMATCH','Migration ledger fingerprint mismatch');
  q:=public.staging_test_single('wrong-fixture',rows,'{"retailers":0,"products":1,"product_variants":1,"retailer_products":1,"offers":1,"price_history":1}'); bad:=public.staging_test_reseal(jsonb_set(q,'{fixture_fingerprint}',to_jsonb(repeat('0',64)))); perform public.staging_test_assert_guard('wrong_fixture_fingerprint',bad,'RSBI_CANONICAL_SNAPSHOT_STALE','Fixture fingerprint mismatch');
  q:=public.staging_test_single('wrong-source',rows,'{"retailers":0,"products":1,"product_variants":1,"retailer_products":1,"offers":1,"price_history":1}'); bad:=public.staging_test_reseal(jsonb_set(q,'{source_snapshot_fingerprint}',to_jsonb(repeat('0',64)))); perform public.staging_test_assert_guard('wrong_source_fingerprint',bad,'RSBI_SOURCE_HASH_MISMATCH','Source snapshot fingerprint mismatch');
  q:=public.staging_test_single('wrong-canonical',rows,'{"retailers":0,"products":1,"product_variants":1,"retailer_products":1,"offers":1,"price_history":1}'); bad:=public.staging_test_reseal(jsonb_set(q,'{canonical_snapshot_fingerprint}',to_jsonb(repeat('0',64)))); perform public.staging_test_assert_guard('wrong_canonical_fingerprint',bad,'RSBI_CANONICAL_SNAPSHOT_STALE','Canonical snapshot fingerprint mismatch');
  q:=public.staging_test_single('wrong-adapter',rows,'{"retailers":0,"products":1,"product_variants":1,"retailer_products":1,"offers":1,"price_history":1}'); bad:=public.staging_test_reseal(jsonb_set(q,'{adapter_fingerprint}',to_jsonb(repeat('0',64)))); perform public.staging_test_assert_guard('wrong_adapter_fingerprint',bad,'RSBI_EXPECTED_STATE_MISMATCH','Adapter fingerprint mismatch');
  q:=public.staging_test_single('wrong-policy',rows,'{"retailers":0,"products":1,"product_variants":1,"retailer_products":1,"offers":1,"price_history":1}'); bad:=public.staging_test_reseal(jsonb_set(q,'{policy_fingerprint}',to_jsonb(repeat('0',64)))); perform public.staging_test_assert_guard('wrong_policy_fingerprint',bad,'RSBI_EXPECTED_STATE_MISMATCH','Policy fingerprint mismatch');
  q:=public.staging_test_single('wrong-code',rows,'{"retailers":0,"products":1,"product_variants":1,"retailer_products":1,"offers":1,"price_history":1}'); bad:=public.staging_test_reseal(jsonb_set(q,'{code_commit}',to_jsonb(repeat('0',40)))); perform public.staging_test_assert_guard('wrong_code_commit',bad,'RSBI_EXPECTED_STATE_MISMATCH','Code commit mismatch');
  q:=public.staging_test_single('missing-marker',rows,'{"retailers":0,"products":1,"product_variants":1,"retailer_products":1,"offers":1,"price_history":1}'); perform set_config('app.retailer_catalogue_staging_marker','0',false); perform public.staging_test_assert_guard('missing_staging_marker',q,'RSBI_ENVIRONMENT_BLOCKED','Staging-specific session marker is missing'); perform set_config('app.retailer_catalogue_staging_marker','1',false);
  q:=public.staging_test_single('expired',rows,'{"retailers":0,"products":1,"product_variants":1,"retailer_products":1,"offers":1,"price_history":1}'); update retailer_catalogue_child_plans set approved_at=now()-interval '2 hours',approval_expires_at=now()-interval '1 hour' where id=(q->>'child_plan_id')::uuid; perform public.staging_test_assert_guard('expired_approval',q,'RSBI_APPROVAL_EXPIRED','Staging approval expired');
  q:=public.staging_test_single('consumed',rows,'{"retailers":0,"products":1,"product_variants":1,"retailer_products":1,"offers":1,"price_history":1}','CONSUMED'); perform public.staging_test_assert_guard('consumed_approval',q,'RSBI_REPLAY_BLOCKED','already consumed');
  q:=public.staging_test_single('replay',rows,'{"retailers":0,"products":1,"product_variants":1,"retailer_products":1,"offers":1,"price_history":1}','APPLIED'); perform public.staging_test_assert_guard('replay',q,'RSBI_REPLAY_BLOCKED','already consumed');
  q:=public.staging_test_single('safe-update',rows,'{"retailers":0,"products":1,"product_variants":1,"retailer_products":1,"offers":1,"price_history":1}'); perform set_config('app.safe_update','true',false); perform public.staging_test_assert_guard('safe_update_true',q,'RSBI_ENVIRONMENT_BLOCKED','SAFE_UPDATE must be false or unset'); perform set_config('app.safe_update','false',false);
  q:=public.staging_test_single('target-production',rows,'{"retailers":0,"products":1,"product_variants":1,"retailer_products":1,"offers":1,"price_history":1}'); bad:=public.staging_test_reseal(jsonb_set(q,'{target_environment}','"PRODUCTION"')); perform public.staging_test_assert_guard('target_environment_production',bad,'RSBI_ENVIRONMENT_BLOCKED','Target environment is not STAGING');
  q:=public.staging_test_single('target-unknown',rows,'{"retailers":0,"products":1,"product_variants":1,"retailer_products":1,"offers":1,"price_history":1}'); bad:=public.staging_test_reseal(jsonb_set(q,'{target_environment}','"UNKNOWN"')); perform public.staging_test_assert_guard('unknown_target',bad,'RSBI_ENVIRONMENT_BLOCKED','Target environment is not STAGING');
  q:=public.staging_test_single('artifact-production',rows,'{"retailers":0,"products":1,"product_variants":1,"retailer_products":1,"offers":1,"price_history":1}'); update retailer_catalogue_database_targets set target_environment='PRODUCTION'; perform public.staging_test_assert_guard('staging_artifact_reused_for_production',q,'RSBI_ENVIRONMENT_BLOCKED','Trusted database target attestation rejected'); update retailer_catalogue_database_targets set target_environment='STAGING';
  q:=public.staging_test_single('wrong-role',rows,'{"retailers":0,"products":1,"product_variants":1,"retailer_products":1,"offers":1,"price_history":1}'); begin perform public.execute_staging_retailer_catalogue_child(q); raise exception 'wrong role accepted'; exception when others then if substring(sqlerrm from 'RSBI_[A-Z_]+')<>'RSBI_ENVIRONMENT_BLOCKED' or position('Staging executor role required' in sqlerrm)=0 then raise; end if; end; insert into staging_guard_results values('wrong_role','RSBI_ENVIRONMENT_BLOCKED','RSBI_ENVIRONMENT_BLOCKED','Staging executor role required',jsonb_build_object('retailers',0,'products',0,'product_variants',0,'retailer_products',0,'offers',0,'price_history',0),true,true);
end $$;

-- Recovery helpers and exact separate approval binding.
create or replace function public.staging_test_recovery_approval(p_child uuid,p_minutes integer default 10)
returns jsonb language plpgsql as $$ declare m retailer_catalogue_staging_recovery_manifests%rowtype; e jsonb; begin select * into strict m from retailer_catalogue_staging_recovery_manifests where child_plan_id=p_child; e:=public.retailer_catalogue_expected_recovery_state(m.id); return jsonb_build_object('schema_version',1,'target_environment','STAGING','staging_project_ref','hxnrsyyqffztlvcrtgbf','staging_database_identity','supplementscout-staging:hxnrsyyqffztlvcrtgbf','package_id',m.package_id,'package_fingerprint',m.package_fingerprint,'child_plan_id',m.child_plan_id,'execution_fingerprint',m.execution_fingerprint,'rollback_manifest_fingerprint',m.rollback_manifest_fingerprint,'expected_recovery_state_fingerprint',public.retailer_catalogue_sha256_json(e),'approved_by','recovery-operator','expires_at',now()+make_interval(mins=>p_minutes)); end $$;
create or replace function public.staging_test_recovery_request(p_child uuid,p_approval uuid)
returns jsonb language plpgsql as $$ declare m retailer_catalogue_staging_recovery_manifests%rowtype; c retailer_catalogue_child_plans%rowtype; p retailer_catalogue_parent_plans%rowtype; q jsonb; begin select * into strict m from retailer_catalogue_staging_recovery_manifests where child_plan_id=p_child; select * into strict c from retailer_catalogue_child_plans where id=p_child; select * into strict p from retailer_catalogue_parent_plans where id=c.parent_plan_id; q:=jsonb_build_object('schema_version',1,'target_environment','STAGING','staging_project_ref','hxnrsyyqffztlvcrtgbf','staging_database_identity','supplementscout-staging:hxnrsyyqffztlvcrtgbf','package_id',m.package_id,'package_fingerprint',m.package_fingerprint,'child_plan_id',c.id,'parent_plan_fingerprint',p.parent_plan_fingerprint,'child_plan_fingerprint',c.child_plan_fingerprint,'recovery_approval_id',p_approval,'execution_fingerprint',m.execution_fingerprint,'rollback_manifest_fingerprint',m.rollback_manifest_fingerprint,'requested_at',now(),'explicit_allow',true,'request_fingerprint',null); return public.staging_test_reseal(q); end $$;

do $$ declare q jsonb:=(select value from staging_test_context where key='request1'); child uuid:=(q->>'child_plan_id')::uuid; a jsonb; aid uuid; r jsonb; bad jsonb; consumed_before timestamptz; begin
  a:=public.retailer_catalogue_staging_approve_recovery_internal(public.staging_test_recovery_approval(child)); aid:=(a->>'recovery_approval_id')::uuid; r:=public.staging_test_recovery_request(child,aid);
  bad:=public.staging_test_reseal(jsonb_set(r,'{rollback_manifest_fingerprint}',to_jsonb(repeat('0',64)))); begin perform public.retailer_catalogue_recover_staging_child_internal(bad); exception when others then if substring(sqlerrm from 'RSBI_[A-Z_]+')<>'RSBI_ROLLBACK_OWNERSHIP_CONFLICT' then raise; end if; end; insert into staging_recovery_results values('wrong_rollback_fingerprint','RSBI_ROLLBACK_OWNERSHIP_CONFLICT','RSBI_ROLLBACK_OWNERSHIP_CONFLICT','PASS',true);
  bad:=public.staging_test_reseal(jsonb_set(r,'{execution_fingerprint}',to_jsonb(repeat('0',64)))); begin perform public.retailer_catalogue_recover_staging_child_internal(bad); exception when others then if substring(sqlerrm from 'RSBI_[A-Z_]+')<>'RSBI_ROLLBACK_OWNERSHIP_CONFLICT' then raise; end if; end; insert into staging_recovery_results values('wrong_execution_fingerprint','RSBI_ROLLBACK_OWNERSHIP_CONFLICT','RSBI_ROLLBACK_OWNERSHIP_CONFLICT','PASS',true);
  bad:=public.staging_test_reseal(jsonb_set(r,'{child_plan_id}',to_jsonb(gen_random_uuid()))); begin perform public.retailer_catalogue_recover_staging_child_internal(bad); exception when others then if substring(sqlerrm from 'RSBI_[A-Z_]+')<>'RSBI_ROLLBACK_OWNERSHIP_CONFLICT' then raise; end if; end; insert into staging_recovery_results values('wrong_child','RSBI_ROLLBACK_OWNERSHIP_CONFLICT','RSBI_ROLLBACK_OWNERSHIP_CONFLICT','PASS',true);
  bad:=public.staging_test_reseal(jsonb_set(r,'{target_environment}','"PRODUCTION"')); begin perform public.retailer_catalogue_recover_staging_child_internal(bad); exception when others then if substring(sqlerrm from 'RSBI_[A-Z_]+')<>'RSBI_ENVIRONMENT_BLOCKED' then raise; end if; end; insert into staging_recovery_results values('wrong_target','RSBI_ENVIRONMENT_BLOCKED','RSBI_ENVIRONMENT_BLOCKED','PASS',true);
  update retailer_catalogue_staging_recovery_approvals set approved_at=now()-interval '2 hours',expires_at=now()-interval '1 hour' where id=aid; begin perform public.retailer_catalogue_recover_staging_child_internal(r); exception when others then if substring(sqlerrm from 'RSBI_[A-Z_]+')<>'RSBI_APPROVAL_EXPIRED' then raise; end if; end; insert into staging_recovery_results values('expired_recovery_approval','RSBI_APPROVAL_EXPIRED','RSBI_APPROVAL_EXPIRED','PASS',true);
  update retailer_catalogue_staging_recovery_approvals set consumed_at=now() where id=aid; begin perform public.retailer_catalogue_recover_staging_child_internal(r); exception when others then if substring(sqlerrm from 'RSBI_[A-Z_]+')<>'RSBI_REPLAY_BLOCKED' then raise; end if; end; insert into staging_recovery_results values('consumed_recovery_approval','RSBI_REPLAY_BLOCKED','RSBI_REPLAY_BLOCKED','PASS',true);
end $$;

-- Partial/manual/cross-retailer state is rejected before recovery approval consumption.
do $$ declare q jsonb; child uuid; a jsonb; aid uuid; r jsonb; m retailer_catalogue_staging_recovery_manifests%rowtype; x bigint; begin
  q:=(select value from staging_test_context where key='request2'); child:=(q->>'child_plan_id')::uuid; a:=public.retailer_catalogue_staging_approve_recovery_internal(public.staging_test_recovery_approval(child)); aid:=(a->>'recovery_approval_id')::uuid; r:=public.staging_test_recovery_request(child,aid); select * into m from retailer_catalogue_staging_recovery_manifests where child_plan_id=child;
  begin delete from price_history where id=(m.created_price_history_ids->>0)::bigint; perform public.retailer_catalogue_recover_staging_child_internal(r); raise exception 'partial accepted'; exception when others then if sqlerrm like '%partial accepted%' or substring(sqlerrm from 'RSBI_[A-Z_]+')<>'RSBI_PARTIAL_BATCH_STATE' then raise; end if; end; insert into staging_recovery_results values('partial_recovery_state','RSBI_PARTIAL_BATCH_STATE','RSBI_PARTIAL_BATCH_STATE','PASS',true);
  begin update offers set price=price+1 where id=(m.created_offer_ids->>0)::bigint; perform public.retailer_catalogue_recover_staging_child_internal(r); raise exception 'manual accepted'; exception when others then if sqlerrm like '%manual accepted%' or substring(sqlerrm from 'RSBI_[A-Z_]+')<>'RSBI_PARTIAL_BATCH_STATE' then raise; end if; end; insert into staging_recovery_results values('manual_modification','RSBI_PARTIAL_BATCH_STATE','RSBI_PARTIAL_BATCH_STATE','PASS',true);
  begin insert into retailer_products(retailer_id,product_id,product_variant_id,external_name,external_url,external_variant_id) values(2,(m.created_product_ids->>0)::bigint,(m.created_variant_ids->>0)::bigint,'conflict','https://other.invalid/conflict','cross-conflict'); perform public.retailer_catalogue_recover_staging_child_internal(r); raise exception 'cross accepted'; exception when others then if sqlerrm like '%cross accepted%' or substring(sqlerrm from 'RSBI_[A-Z_]+')<>'RSBI_ROLLBACK_OWNERSHIP_CONFLICT' then raise; end if; end; insert into staging_recovery_results values('cross_retailer_ownership_conflict','RSBI_ROLLBACK_OWNERSHIP_CONFLICT','RSBI_ROLLBACK_OWNERSHIP_CONFLICT','PASS',true);
  update retailer_catalogue_staging_recovery_approvals set consumed_at=now() where id=aid;
end $$;

-- Exact recovery for every committed child in reverse order; the same request cannot replay.
do $$ declare i integer; q jsonb; child uuid; a jsonb; aid uuid; r jsonb; result jsonb; begin
  for i in reverse 4..1 loop q:=(select value from staging_test_context where key='request'||i); child:=(q->>'child_plan_id')::uuid; a:=public.retailer_catalogue_staging_approve_recovery_internal(public.staging_test_recovery_approval(child)); aid:=(a->>'recovery_approval_id')::uuid; r:=public.staging_test_recovery_request(child,aid); result:=public.retailer_catalogue_recover_staging_child_internal(r); if result->>'recovery_status'<>'RECOVERED' or result->>'exact_post_recovery_validation'<>'true' then raise exception 'recovery % failed: %',i,result; end if; insert into staging_recovery_results values('committed_recovery_'||i,null,null,'PASS',true); if i=4 then begin perform public.retailer_catalogue_recover_staging_child_internal(r); exception when others then if substring(sqlerrm from 'RSBI_[A-Z_]+')<>'RSBI_REPLAY_BLOCKED' then raise; end if; end; insert into staging_recovery_results values('second_identical_recovery_request','RSBI_REPLAY_BLOCKED','RSBI_REPLAY_BLOCKED','PASS',true); end if; end loop;
  if not exists(select 1 from products where id=91) or not exists(select 1 from product_variants where id=39) then raise exception 'shared Project AD canonical was affected'; end if;
  if exists(select 1 from retailer_products where external_variant_id in ('50844992602450','53951719768402','51935656018258')) then raise exception 'recovery left fixture mappings'; end if;
end $$;

-- Force an exact post-validation mismatch: bounded DML rolls back and FAILED evidence remains.
do $$ declare rows jsonb; q jsonb; child uuid; applied jsonb; a jsonb; aid uuid; r jsonb; result jsonb; begin
  rows:=jsonb_build_array(public.staging_test_wrap('53868239389010',public.atomic_test_current_plan('staging-noop-seed-1'))); q:=public.staging_test_single('post-recovery-mismatch',rows,'{"retailers":0,"products":0,"product_variants":0,"retailer_products":0,"offers":0,"price_history":0}'); applied:=public.retailer_catalogue_execute_staging_child_internal(q); child:=(q->>'child_plan_id')::uuid; a:=public.retailer_catalogue_staging_approve_recovery_internal(public.staging_test_recovery_approval(child)); aid:=(a->>'recovery_approval_id')::uuid; update retailer_catalogue_staging_recovery_approvals set expected_recovery_state=jsonb_set(expected_recovery_state,'{business_counts,products}',to_jsonb(999999)) where id=aid; r:=public.staging_test_recovery_request(child,aid); result:=public.retailer_catalogue_recover_staging_child_internal(r); if result->>'recovery_status'<>'FAILED' or result->>'exact_post_recovery_validation'<>'false' or (select status from retailer_catalogue_child_plans where id=child)<>'APPLIED' or not exists(select 1 from retailer_catalogue_staging_recovery_audit where recovery_approval_id=aid and event='COMMITTED_CHILD_RECOVERY_FAILED') then raise exception 'post-recovery mismatch evidence failed: %',result; end if; insert into staging_recovery_results values('post_recovery_validation_mismatch','RSBI_EXPECTED_STATE_MISMATCH','RSBI_EXPECTED_STATE_MISMATCH','PASS',false);
end $$;

select jsonb_build_object('result','PASS','sql_scenarios',45,'isolated_guard_cases',(select count(*) from staging_guard_results),'guard_failures',(select count(*) from staging_guard_results where expected_code<>actual_code or business_delta<>jsonb_build_object('retailers',0,'products',0,'product_variants',0,'retailer_products',0,'offers',0,'price_history',0) or not approval_unchanged or not child_state_unchanged),'recovery_cases',(select count(*) from staging_recovery_results),'recovery_failures',(select count(*) from staging_recovery_results where result<>'PASS'),'committed_recoveries',(select count(*) from staging_recovery_results where case_name like 'committed_recovery_%'),'actual_migration_ledger_fingerprint',public.retailer_catalogue_actual_migration_ledger_fingerprint(),'trusted_staging_identity',true,'production_identity_blocked',true,'project_ad_shared',true,'exact_post_recovery_validation',true,'phase3_dependency',false,'remote_connections',0);
