const { parse } = require("csv-parse/sync");
const { canonicalize, fingerprintReviewDecision, hash } = require("./fingerprints");
const { fail } = require("./errors");

const COLUMNS = Object.freeze(["review_item_id","snapshot_id","source_record_id","retailer","product_title","variant_title","primary_status","reason_codes","confidence","canonical_candidates","source_sku","source_gtin","source_weight","source_price","source_url","suggested_action","reviewer_decision","selected_canonical_product_id","selected_canonical_variant_id","reviewer_notes","reviewed_by","reviewed_at","decision_fingerprint"]);
const DECISIONS = Object.freeze(["APPROVE_EXISTING_VARIANT","APPROVE_NEW_VARIANT_SEED","APPROVE_NEW_PRODUCT","APPROVE_NEW_FAMILY_SEED","DEFER_POLICY","MARK_OOS","REJECT_IDENTITY","REQUEST_NEW_SOURCE","SUPERSEDE"]);
function csvCell(value) { const text = value == null ? "" : String(value); return /[",\r\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text; }
function normalizeRow(row) { const out = {}; for (const column of COLUMNS) out[column] = row[column] == null ? "" : String(row[column]); out.reason_codes = Array.isArray(row.reason_codes) ? [...row.reason_codes].sort().join("|") : out.reason_codes; out.canonical_candidates = Array.isArray(row.canonical_candidates) ? canonicalize(row.canonical_candidates) : out.canonical_candidates; return out; }
function exportReviewQueueJson(rows, metadata = {}) { const normalized = rows.map(normalizeRow); return Object.freeze({ schema_version: 1, snapshot_id: metadata.snapshot_id || null, rows: normalized, artifact_fingerprint: hash("RSBI:REVIEW-QUEUE:1", normalized) }); }
function exportReviewQueueCsv(rows) { return `${COLUMNS.join(",")}\n${rows.map((row) => { const normalized = normalizeRow(row); return COLUMNS.map((column) => csvCell(normalized[column])).join(","); }).join("\n")}${rows.length ? "\n" : ""}`; }
function parseReviewQueueCsv(csv) { const rows = parse(csv, { columns: true, skip_empty_lines: true, bom: true }); const header = csv.split(/\r?\n/, 1)[0]; if (header !== COLUMNS.join(",")) fail("RSBI_SOURCE_SCHEMA_MISMATCH", "Review CSV header differs from frozen 23 columns"); return rows; }
function sealDecision(row) { const normalized = normalizeRow(row); if (!DECISIONS.includes(normalized.reviewer_decision)) fail("RSBI_INVALID_TRANSITION", `Unknown reviewer decision ${normalized.reviewer_decision}`); if (!normalized.reviewed_by || !normalized.reviewed_at) fail("RSBI_MISSING_REQUIRED_EVIDENCE", "Decided row requires reviewer and timestamp"); normalized.decision_fingerprint = ""; normalized.decision_fingerprint = fingerprintReviewDecision(normalized); return Object.freeze(normalized); }
function validateDecision(row) { const normalized = normalizeRow(row); if (!normalized.reviewer_decision) return { state: "OPEN", valid: true }; const actual = normalized.decision_fingerprint; normalized.decision_fingerprint = ""; return { state: "DECIDED", valid: DECISIONS.includes(normalized.reviewer_decision) && Boolean(normalized.reviewed_by && normalized.reviewed_at) && actual === fingerprintReviewDecision(normalized) }; }

module.exports = { COLUMNS, DECISIONS, exportReviewQueueCsv, exportReviewQueueJson, normalizeRow, parseReviewQueueCsv, sealDecision, validateDecision };
