create table public.retailer_products (
  id bigint generated by default as identity primary key,
  retailer_id bigint not null references public.retailers(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,

  external_name text not null,
  external_slug text,
  external_gtin text,
  external_url text not null,

  match_method text,
  match_confidence numeric(5,2),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint retailer_products_retailer_url_unique
    unique (retailer_id, external_url)
);

create index retailer_products_external_gtin_idx
on public.retailer_products (external_gtin);

create index retailer_products_external_slug_idx
on public.retailer_products (external_slug);

create index retailer_products_product_id_idx
on public.retailer_products (product_id);

insert into public.retailer_products (
  retailer_id,
  product_id,
  external_name,
  external_slug,
  external_gtin,
  external_url,
  match_method,
  match_confidence
)
select
  o.retailer_id,
  o.product_id,
  p.name,
  p.slug,
  p.gtin,
  o.url,
  'existing_offer',
  100
from public.offers o
join public.products p
  on p.id = o.product_id
on conflict (retailer_id, external_url) do nothing;