-- Stage 1: add a nullable canonical-variant layer without changing application behaviour.
-- This migration deliberately keeps offers(product_id, retailer_id) unique and does
-- not copy any GTIN from products into product_variants.

begin;

-- Transaction-local preservation baseline. The final guard compares every
-- pre-existing field and row before COMMIT; new nullable columns are excluded.
create temp table product_variants_stage1_baseline on commit drop as
select
  (select count(*) from public.products) as products_count,
  (select count(*) from public.retailer_products) as retailer_products_count,
  (select count(*) from public.offers) as offers_count,
  (select count(*) from public.price_history) as price_history_count,
  (select coalesce(jsonb_agg(to_jsonb(p) order by p.id), '[]'::jsonb) from public.products p) as products_snapshot,
  (select coalesce(jsonb_agg(
    to_jsonb(rp) - array[
      'product_variant_id', 'external_product_id', 'external_variant_id',
      'external_sku', 'external_options'
    ] order by rp.id
  ), '[]'::jsonb) from public.retailer_products rp) as retailer_products_snapshot,
  (select coalesce(jsonb_agg(
    to_jsonb(o) - array['retailer_product_id', 'product_variant_id'] order by o.id
  ), '[]'::jsonb) from public.offers o) as offers_snapshot,
  (select coalesce(jsonb_agg(to_jsonb(ph) order by ph.id), '[]'::jsonb) from public.price_history ph) as price_history_snapshot;

create table if not exists public.product_variants (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  variant_key text not null,
  display_name text not null,
  flavour_code text,
  flavour_label text,
  size_value numeric,
  size_unit text,
  pack_count integer,
  product_format text,
  gtin text,
  image text,
  nutrition_override jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint product_variants_product_key_unique unique (product_id, variant_key),
  constraint product_variants_variant_key_nonempty check (btrim(variant_key) <> ''),
  constraint product_variants_display_name_nonempty check (btrim(display_name) <> ''),
  constraint product_variants_flavour_pair check (
    (flavour_code is null and flavour_label is null)
    or (
      flavour_code is not null and btrim(flavour_code) <> ''
      and flavour_label is not null and btrim(flavour_label) <> ''
    )
  ),
  constraint product_variants_size_value_positive check (
    size_value is null or (size_value::text <> 'NaN' and size_value > 0)
  ),
  constraint product_variants_size_unit_nonempty check (size_unit is null or btrim(size_unit) <> ''),
  constraint product_variants_pack_count_positive check (pack_count is null or pack_count > 0),
  constraint product_variants_gtin_nonempty check (gtin is null or btrim(gtin) <> ''),
  constraint product_variants_nutrition_override_object check (
    jsonb_typeof(nutrition_override) = 'object'
  )
);

comment on column public.product_variants.flavour_code is
  'NULL means no flavour dimension. Use an explicit code such as unflavoured when the product is explicitly unflavoured.';
comment on column public.product_variants.gtin is
  'Variant-level evidence only. This value must not be copied into products.gtin.';

create unique index if not exists product_variants_one_default_per_product_idx
  on public.product_variants (product_id)
  where is_default = true;

create index if not exists product_variants_gtin_idx
  on public.product_variants (gtin)
  where gtin is not null and btrim(gtin) <> '';

alter table public.product_variants enable row level security;

alter table public.retailer_products
  add column if not exists product_variant_id bigint,
  add column if not exists external_product_id text,
  add column if not exists external_variant_id text,
  add column if not exists external_sku text,
  add column if not exists external_options jsonb;

alter table public.offers
  add column if not exists retailer_product_id bigint,
  add column if not exists product_variant_id bigint;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.retailer_products'::regclass
      and conname = 'retailer_products_product_variant_id_fkey'
  ) then
    alter table public.retailer_products
      add constraint retailer_products_product_variant_id_fkey
      foreign key (product_variant_id)
      references public.product_variants(id)
      on delete set null;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.retailer_products'::regclass
      and conname = 'retailer_products_external_options_object'
  ) then
    alter table public.retailer_products
      add constraint retailer_products_external_options_object
      check (external_options is null or jsonb_typeof(external_options) = 'object');
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.offers'::regclass
      and conname = 'offers_retailer_product_id_fkey'
  ) then
    alter table public.offers
      add constraint offers_retailer_product_id_fkey
      foreign key (retailer_product_id)
      references public.retailer_products(id)
      on delete set null;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.offers'::regclass
      and conname = 'offers_product_variant_id_fkey'
  ) then
    alter table public.offers
      add constraint offers_product_variant_id_fkey
      foreign key (product_variant_id)
      references public.product_variants(id)
      on delete set null;
  end if;
end;
$$;

create index if not exists retailer_products_product_variant_id_idx
  on public.retailer_products (product_variant_id);
create index if not exists retailer_products_external_product_id_idx
  on public.retailer_products (retailer_id, external_product_id);
create index if not exists retailer_products_external_variant_id_idx
  on public.retailer_products (retailer_id, external_variant_id);
create index if not exists offers_retailer_product_id_idx
  on public.offers (retailer_product_id);
create index if not exists offers_product_variant_id_idx
  on public.offers (product_variant_id);

-- Every current product, including inactive/history-only products, receives one
-- neutral default variant. Variant GTIN and nutrition data intentionally remain empty.
do $$
begin
  if exists (select 1 from public.products where is_active is null) then
    raise exception 'Cannot backfill variants: products.is_active contains NULL';
  end if;
end;
$$;

insert into public.product_variants (
  product_id,
  variant_key,
  display_name,
  flavour_code,
  flavour_label,
  pack_count,
  gtin,
  nutrition_override,
  is_active,
  is_default
)
select
  p.id,
  'default',
  'Default',
  null,
  null,
  null,
  null,
  '{}'::jsonb,
  p.is_active,
  true
from public.products p
on conflict (product_id, variant_key) do nothing;

do $$
begin
  if exists (
    select p.id
    from public.products p
    left join public.product_variants pv
      on pv.product_id = p.id and pv.is_default = true
    group by p.id
    having count(pv.id) <> 1
  ) then
    raise exception 'Cannot backfill variants: every product must have exactly one default variant';
  end if;

  if exists (
    select 1
    from public.products p
    join public.product_variants pv
      on pv.product_id = p.id and pv.variant_key = 'default'
    where pv.is_default is not true
      or pv.display_name <> 'Default'
      or pv.is_active is distinct from p.is_active
  ) then
    raise exception 'Cannot backfill variants: an existing default row conflicts with the approved baseline';
  end if;
end;
$$;

update public.retailer_products rp
set product_variant_id = pv.id
from public.product_variants pv
where rp.product_id = pv.product_id
  and pv.is_default = true
  and rp.product_variant_id is null;

update public.offers o
set product_variant_id = pv.id
from public.product_variants pv
where o.product_id = pv.product_id
  and pv.is_default = true
  and o.product_variant_id is null;

-- Link an offer to a retailer mapping only when retailer_id + product_id has
-- exactly one candidate. Ambiguous pairs (currently retailer 1/product 510)
-- deliberately remain NULL for manual resolution.
with unambiguous_mappings as (
  select retailer_id, product_id, min(id) as retailer_product_id
  from public.retailer_products
  group by retailer_id, product_id
  having count(*) = 1
)
update public.offers o
set retailer_product_id = m.retailer_product_id
from unambiguous_mappings m
where o.retailer_id = m.retailer_id
  and o.product_id = m.product_id
  and o.retailer_product_id is null;

do $$
declare
  baseline record;
  current_retailer_products_snapshot jsonb;
  current_offers_snapshot jsonb;
begin
  if exists (select 1 from public.retailer_products where product_variant_id is null) then
    raise exception 'Variant backfill incomplete for retailer_products';
  end if;

  if exists (select 1 from public.offers where product_variant_id is null) then
    raise exception 'Variant backfill incomplete for offers';
  end if;

  if exists (
    select 1
    from public.offers o
    join public.retailer_products rp on rp.id = o.retailer_product_id
    where o.retailer_product_id is not null
      and (rp.retailer_id <> o.retailer_id or rp.product_id <> o.product_id)
  ) then
    raise exception 'Offer linked to a retailer_product with different identity';
  end if;

  select * into strict baseline from product_variants_stage1_baseline;

  select coalesce(jsonb_agg(
    to_jsonb(rp) - array[
      'product_variant_id', 'external_product_id', 'external_variant_id',
      'external_sku', 'external_options'
    ] order by rp.id
  ), '[]'::jsonb)
  into current_retailer_products_snapshot
  from public.retailer_products rp;

  select coalesce(jsonb_agg(
    to_jsonb(o) - array['retailer_product_id', 'product_variant_id'] order by o.id
  ), '[]'::jsonb)
  into current_offers_snapshot
  from public.offers o;

  if baseline.products_count <> (select count(*) from public.products)
    or baseline.retailer_products_count <> (select count(*) from public.retailer_products)
    or baseline.offers_count <> (select count(*) from public.offers)
    or baseline.price_history_count <> (select count(*) from public.price_history)
    or baseline.products_snapshot is distinct from (
      select coalesce(jsonb_agg(to_jsonb(p) order by p.id), '[]'::jsonb)
      from public.products p
    )
    or baseline.retailer_products_snapshot is distinct from current_retailer_products_snapshot
    or baseline.offers_snapshot is distinct from current_offers_snapshot
    or baseline.price_history_snapshot is distinct from (
      select coalesce(jsonb_agg(to_jsonb(ph) order by ph.id), '[]'::jsonb)
      from public.price_history ph
    )
  then
    raise exception 'Stage-one migration changed pre-existing rows or fields';
  end if;
end;
$$;

commit;
