alter table public.products
add column merged_into_product_id bigint null references public.products(id),
add column merged_at timestamptz null,
add column is_active boolean not null default true;

alter table public.products
add constraint products_cannot_merge_into_self
check (
  merged_into_product_id is null
  or merged_into_product_id <> id
);

alter table public.products
add constraint products_merge_state_consistent
check (
  (
    merged_into_product_id is null
    and merged_at is null
    and is_active = true
  )
  or
  (
    merged_into_product_id is not null
    and merged_at is not null
    and is_active = false
  )
);

create index products_is_active_idx
on public.products (is_active);

create index products_merged_into_product_id_idx
on public.products (merged_into_product_id);

create table public.product_merge_history (
  id bigint generated by default as identity primary key,

  canonical_product_id bigint not null references public.products(id),
  candidate_product_id bigint not null references public.products(id),

  merged_at timestamptz not null default now(),

  offers_moved integer not null default 0,
  retailer_products_moved integer not null default 0,
  price_history_preserved integer not null default 0,

  moved_offer_ids bigint[] not null default '{}',
  moved_retailer_product_ids bigint[] not null default '{}',
  candidate_offer_ids bigint[] not null default '{}',
  price_history_offer_ids bigint[] not null default '{}',

  snapshot jsonb not null,
  source text not null default 'admin_merge_rpc',

  constraint product_merge_history_not_same_product
    check (canonical_product_id <> candidate_product_id),

  constraint product_merge_history_candidate_once
    unique (candidate_product_id)
);

create index product_merge_history_canonical_product_id_idx
on public.product_merge_history (canonical_product_id);

create index product_merge_history_candidate_product_id_idx
on public.product_merge_history (candidate_product_id);

alter table public.product_merge_history enable row level security;

create or replace function public.extract_product_size(product_name text)
returns table (
  value numeric,
  dimension text
)
language sql
immutable
set search_path = pg_catalog, public
as $$
  with size_match as (
    select regexp_match(
      lower(coalesce(product_name, '')),
      '([0-9]+(?:\.[0-9]+)?)\s*(kg|g|ml|l)([^a-z0-9_]|$)'
    ) as match
  )
  select
    case (match)[2]
      when 'kg' then ((match)[1])::numeric * 1000
      when 'g' then ((match)[1])::numeric
      when 'l' then ((match)[1])::numeric * 1000
      when 'ml' then ((match)[1])::numeric
    end as value,
    case
      when (match)[2] in ('kg', 'g') then 'mass'
      when (match)[2] in ('l', 'ml') then 'volume'
    end as dimension
  from size_match
  where match is not null;
$$;

revoke all on function public.extract_product_size(text)
from public, anon, authenticated, service_role;

create or replace function public.merge_products(
  canonical_id bigint,
  candidate_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  canonical_product public.products%rowtype;
  candidate_product public.products%rowtype;

  locked_count integer;

  canonical_size_value numeric;
  canonical_size_dimension text;
  candidate_size_value numeric;
  candidate_size_dimension text;

  candidate_offer_ids bigint[] := '{}';
  moved_offer_ids bigint[] := '{}';
  candidate_retailer_product_ids bigint[] := '{}';
  moved_retailer_product_ids bigint[] := '{}';
  price_history_offer_ids bigint[] := '{}';
  candidate_offers_before jsonb := '[]'::jsonb;
  candidate_retailer_products_before jsonb := '[]'::jsonb;

  price_history_count integer := 0;
  merged_at_value timestamptz := now();
  merge_history_id bigint;
begin
  if canonical_id is null or candidate_id is null then
    raise exception 'canonical_id and candidate_id are required';
  end if;

  if canonical_id <= 0 or candidate_id <= 0 then
    raise exception 'canonical_id and candidate_id must be positive integers';
  end if;

  if canonical_id = candidate_id then
    raise exception 'canonical_id and candidate_id must be different';
  end if;

  select count(*)
  into locked_count
  from (
    select id
    from public.products
    where id in (canonical_id, candidate_id)
    order by id
    for update
  ) locked_products;

  if locked_count <> 2 then
    raise exception 'Both products must exist';
  end if;

  select *
  into canonical_product
  from public.products
  where id = canonical_id;

  select *
  into candidate_product
  from public.products
  where id = candidate_id;

  if canonical_product.is_active is not true
     or canonical_product.merged_into_product_id is not null
     or canonical_product.merged_at is not null then
    raise exception 'Canonical product is already merged or inactive';
  end if;

  if candidate_product.is_active is not true
     or candidate_product.merged_into_product_id is not null
     or candidate_product.merged_at is not null then
    raise exception 'Candidate product is already merged or inactive';
  end if;

  if nullif(btrim(coalesce(canonical_product.gtin, '')), '') is not null
     and nullif(btrim(coalesce(candidate_product.gtin, '')), '') is not null
     and btrim(canonical_product.gtin) <> btrim(candidate_product.gtin) then
    raise exception 'Merge blocked: products have different non-empty GTINs';
  end if;

  if lower(btrim(coalesce(canonical_product.brand, '')))
     <> lower(btrim(coalesce(candidate_product.brand, ''))) then
    raise exception 'Merge blocked: products have different brands';
  end if;

  if lower(btrim(coalesce(canonical_product.category, '')))
     <> lower(btrim(coalesce(candidate_product.category, ''))) then
    raise exception 'Merge blocked: products have different categories';
  end if;

  if canonical_product.servings is not null
     and candidate_product.servings is not null
     and canonical_product.servings <> candidate_product.servings then
    raise exception 'Merge blocked: products have different servings';
  end if;

  select value, dimension
  into canonical_size_value, canonical_size_dimension
  from public.extract_product_size(canonical_product.name)
  limit 1;

  select value, dimension
  into candidate_size_value, candidate_size_dimension
  from public.extract_product_size(candidate_product.name)
  limit 1;

  if canonical_size_value is not null
     and candidate_size_value is not null
     and (
       canonical_size_value <> candidate_size_value
       or canonical_size_dimension <> candidate_size_dimension
     ) then
    raise exception 'Merge blocked: products have different detected sizes';
  end if;

  if exists (
    select 1
    from public.offers candidate_offer
    where candidate_offer.product_id = candidate_id
      and candidate_offer.retailer_id is null
  ) then
    raise exception 'Merge blocked: candidate offer is missing retailer_id';
  end if;

  if exists (
    select 1
    from public.offers candidate_offer
    where candidate_offer.product_id = candidate_id
      and nullif(btrim(coalesce(candidate_offer.url, '')), '') is null
  ) then
    raise exception 'Merge blocked: candidate offer is missing URL';
  end if;

  if exists (
    select 1
    from public.offers candidate_offer
    join public.offers canonical_offer
      on canonical_offer.product_id = canonical_id
     and canonical_offer.retailer_id = candidate_offer.retailer_id
    where candidate_offer.product_id = candidate_id
  ) then
    raise exception 'Merge blocked: canonical already has an offer for a candidate retailer';
  end if;

  if exists (
    select 1
    from public.offers candidate_offer
    join public.offers canonical_offer
      on canonical_offer.product_id = canonical_id
     and nullif(btrim(coalesce(canonical_offer.url, '')), '')
       = nullif(btrim(coalesce(candidate_offer.url, '')), '')
    where candidate_offer.product_id = candidate_id
  ) then
    raise exception 'Merge blocked: canonical already has an offer with a candidate URL';
  end if;

  if exists (
    select 1
    from public.retailer_products candidate_mapping
    where candidate_mapping.product_id = candidate_id
      and nullif(btrim(coalesce(candidate_mapping.external_url, '')), '') is null
  ) then
    raise exception 'Merge blocked: candidate retailer_products mapping is missing external_url';
  end if;

  if exists (
    select 1
    from public.retailer_products candidate_mapping
    join public.retailer_products canonical_mapping
      on canonical_mapping.product_id = canonical_id
     and canonical_mapping.retailer_id = candidate_mapping.retailer_id
    where candidate_mapping.product_id = candidate_id
  ) then
    raise exception 'Merge blocked: canonical already has a retailer_products mapping for a candidate retailer';
  end if;

  if exists (
    select 1
    from public.retailer_products candidate_mapping
    join public.retailer_products canonical_mapping
      on canonical_mapping.product_id = canonical_id
     and canonical_mapping.retailer_id = candidate_mapping.retailer_id
     and canonical_mapping.external_url = candidate_mapping.external_url
    where candidate_mapping.product_id = candidate_id
  ) then
    raise exception 'Merge blocked: canonical already has the same retailer_products external_url';
  end if;

  select coalesce(array_agg(id order by id), '{}')
  into candidate_offer_ids
  from public.offers
  where product_id = candidate_id;

  select coalesce(array_agg(id order by id), '{}')
  into candidate_retailer_product_ids
  from public.retailer_products
  where product_id = candidate_id;

  select coalesce(jsonb_agg(to_jsonb(o) order by o.id), '[]'::jsonb)
  into candidate_offers_before
  from public.offers o
  where o.product_id = candidate_id;

  select coalesce(jsonb_agg(to_jsonb(rp) order by rp.id), '[]'::jsonb)
  into candidate_retailer_products_before
  from public.retailer_products rp
  where rp.product_id = candidate_id;

  select coalesce(array_agg(distinct offer_id order by offer_id), '{}')
  into price_history_offer_ids
  from public.price_history
  where offer_id = any(candidate_offer_ids);

  select count(*)
  into price_history_count
  from public.price_history
  where offer_id = any(candidate_offer_ids);

  with moved_offers as (
    update public.offers
    set product_id = canonical_id
    where product_id = candidate_id
    returning id
  )
  select coalesce(array_agg(id order by id), '{}')
  into moved_offer_ids
  from moved_offers;

  with moved_mappings as (
    update public.retailer_products
    set product_id = canonical_id
    where product_id = candidate_id
    returning id
  )
  select coalesce(array_agg(id order by id), '{}')
  into moved_retailer_product_ids
  from moved_mappings;

  update public.products
  set
    merged_into_product_id = canonical_id,
    merged_at = merged_at_value,
    is_active = false
  where id = candidate_id;

  insert into public.product_merge_history (
    canonical_product_id,
    candidate_product_id,
    merged_at,
    offers_moved,
    retailer_products_moved,
    price_history_preserved,
    moved_offer_ids,
    moved_retailer_product_ids,
    candidate_offer_ids,
    price_history_offer_ids,
    snapshot,
    source
  )
  values (
    canonical_id,
    candidate_id,
    merged_at_value,
    cardinality(moved_offer_ids),
    cardinality(moved_retailer_product_ids),
    price_history_count,
    moved_offer_ids,
    moved_retailer_product_ids,
    candidate_offer_ids,
    price_history_offer_ids,
    jsonb_build_object(
      'canonical_before_merge', to_jsonb(canonical_product),
      'candidate_before_merge', to_jsonb(candidate_product),
      'candidate_offer_ids', candidate_offer_ids,
      'candidate_retailer_product_ids', candidate_retailer_product_ids,
      'candidate_offers_before', candidate_offers_before,
      'candidate_retailer_products_before', candidate_retailer_products_before,
      'moved_offer_ids', moved_offer_ids,
      'moved_retailer_product_ids', moved_retailer_product_ids,
      'price_history_offer_ids', price_history_offer_ids,
      'price_history_preserved', price_history_count,
      'merged_at', merged_at_value,
      'source', 'admin_merge_rpc'
    ),
    'admin_merge_rpc'
  )
  returning id into merge_history_id;

  return jsonb_build_object(
    'merge_history_id', merge_history_id,
    'canonical_product_id', canonical_id,
    'candidate_product_id', candidate_id,
    'merged_at', merged_at_value,
    'offers_moved', cardinality(moved_offer_ids),
    'retailer_products_moved', cardinality(moved_retailer_product_ids),
    'price_history_preserved', price_history_count,
    'redirect_to', '/product/' || canonical_id::text
  );
end;
$$;

revoke all on function public.merge_products(bigint, bigint)
from public, anon, authenticated, service_role;

grant execute on function public.merge_products(bigint, bigint)
to service_role;
