const assert=require("node:assert/strict");
const test=require("node:test");
const {buildExistingOfferUpdatePlan}=require("./lib/retailer-offer-sync/existing-offer-plan");
const {guardrailsFor,parseArgs,sumDeltas}=require("./jons-offer-refresh");

const rowDelta=(stock=0)=>({row_count_deltas:{products:0,product_variants:0,retailer_products:0,offers:0,price_history:0},logical_field_deltas:{offer_price_updates:0,offer_shipping_updates:0,offer_total_updates:0,offer_stock_updates:stock,offer_url_updates:0,mapping_url_updates:0,mapping_updated_at_updates:0,last_checked_at_updates:1}});
const state={product:{id:1,name:"Test",is_active:true,merged_into_product_id:null,product_format:"powder"},variant:{id:2,product_id:1,variant_key:"default",display_name:"Default",flavour_code:null,flavour_label:null,size_value:"300",size_unit:"g",pack_count:null,product_format:"powder",is_active:true,is_default:true},retailer:{id:10,name:"Jon's Supplements",slug:"jon-s-supplements",website:"https://jonssupplements.co.uk"},mapping:{id:3,retailer_id:10,product_id:1,product_variant_id:2,external_product_id:"100",external_variant_id:"200",external_sku:"SKU",external_options:null,external_name:"Test",external_slug:"test",external_gtin:null,external_url:"https://jonssupplements.co.uk/products/test?variant=200",match_method:"EXACT",match_confidence:"1",updated_at:"2026-07-22T10:00:00Z"},offer:{id:4,product_id:1,retailer_id:10,product_variant_id:2,retailer_product_id:3,price:"10.00",shipping_cost:"3.99",total_price:"13.99",in_stock:true,url:"https://jonssupplements.co.uk/products/test?variant=200",last_checked_at:"2026-07-22T10:00:00Z"}};

test("stock-only update builds an existing-identity standard plan",()=>{const built=buildExistingOfferUpdatePlan({...state,source:{external_product_id:"100",external_variant_id:"200",price:"10.00",shipping_cost:"3.99",total_price:"13.99",in_stock:false,url:state.offer.url},sourceCapturedAt:"2026-07-22T11:00:00Z",sourceSnapshotFingerprint:"a".repeat(64)});assert.deepEqual(built.changed,{price:false,stock:true,url:false});assert.equal(built.plan.meta.operation_type,"standard_import");assert.equal(built.plan.product.action,"existing");assert.equal(built.plan.product_variant.action,"existing");assert.equal(built.plan.retailer_product.action,"noop");assert.equal(built.plan.offer.action,"update");assert.equal(built.plan.price_history.action,"noop")});
test("identity drift and false no-op standard updates block",()=>{assert.throws(()=>buildExistingOfferUpdatePlan({...state,source:{external_product_id:"999",external_variant_id:"200",price:"10.00",shipping_cost:"3.99",total_price:"13.99",in_stock:false,url:state.offer.url},sourceCapturedAt:"2026-07-22T11:00:00Z",sourceSnapshotFingerprint:"a".repeat(64)}),/identity drift/);assert.throws(()=>buildExistingOfferUpdatePlan({...state,source:{external_product_id:"100",external_variant_id:"200",price:"10.00",shipping_cost:"3.99",total_price:"13.99",in_stock:true,url:state.offer.url},sourceCapturedAt:"2026-07-22T11:00:00Z",sourceSnapshotFingerprint:"a".repeat(64)}),/changed field/)});
test("delta aggregation preserves freshness and stock counts",()=>{const total=sumDeltas([{expected_deltas:rowDelta(0)},{expected_deltas:rowDelta(1)}]);assert.equal(total.logical_field_deltas.last_checked_at_updates,2);assert.equal(total.logical_field_deltas.offer_stock_updates,1);assert.equal(total.row_count_deltas.price_history,0)});
test("guard evidence retains unchanged MASS_OOS limits",()=>{const rows=[{action:"UPDATE_STOCK",changed_fields:{price:false},policy_fingerprint:"p",atomic_plan:{expected_state:{offer:{in_stock:true}},offer:{values:{in_stock:false}}}}];const guard=guardrailsFor(rows,224);assert.equal(guard.limits.maximum_new_oos_count,"3");assert.equal(guard.limits.maximum_oos_increase_ratio,"0.15");assert.equal(guard.new_oos_count,1)});
test("CLI scope is closed",()=>{assert.deepEqual(parseArgs(["--target=production","--mode=dry-run"]),{target:"production",mode:"dry-run"});assert.throws(()=>parseArgs(["--target=other","--mode=apply"]));assert.throws(()=>parseArgs(["--target=production","--mode=unsafe"]))});
