const assert=require("node:assert/strict");
const fs=require("node:fs");
const os=require("node:os");
const path=require("node:path");
const test=require("node:test");
const {buildExistingOfferUpdatePlan}=require("./lib/retailer-offer-sync/existing-offer-plan");
const {excludedMigrationIds}=require("./lib/environment-migrations");
const {loadReviewedMixedChangeManifest}=require("./lib/retailer-offer-sync/reviewed-mixed-change");
const config=require("../config/retailers/jons-supplements-offer-sync.json");
const {RefreshError,canonicalHash,classificationDiagnostic,executionRow,guardrailsFor,loadReviewedMissingVariantManifest,migrationBinding,parseArgs,partitionExecutionRows,reconcileReviewedMissingVariants,registrationRequest,runWithDiagnostic,selectReviewedClassificationRows,sourceHealth,sumDeltas,verificationRecord}=require("./jons-offer-refresh");

const migrationFiles=fs.readdirSync(path.join(process.cwd(),"supabase","migrations"));
const approvedRegistrationMigration="20260724100000_add_approved_retailer_sync_registration";
function assertMigrationBindingContract(files){
  const allMigrationIds=files.filter(name=>/^\d+_[a-z0-9_]+\.sql$/.test(name)).map(name=>name.slice(0,-4));
  for(const environment of ["STAGING","PRODUCTION"]){
    const versions=migrationBinding(environment,files).versions;
    assert.equal(versions.includes(approvedRegistrationMigration),true,`${environment} must bind the approved retailer sync registration migration`);
    const exclusions=excludedMigrationIds(environment);
    for(const id of allMigrationIds)assert.equal(versions.includes(id),!exclusions.has(id),`${environment} migration binding mismatch for ${id}`);
  }
}

const rowDelta=(stock=0)=>({row_count_deltas:{products:0,product_variants:0,retailer_products:0,offers:0,price_history:0},logical_field_deltas:{offer_price_updates:0,offer_shipping_updates:0,offer_total_updates:0,offer_stock_updates:stock,offer_url_updates:0,mapping_url_updates:0,mapping_updated_at_updates:0,last_checked_at_updates:1}});
const state={product:{id:1,name:"Test",is_active:true,merged_into_product_id:null,product_format:"powder"},variant:{id:2,product_id:1,variant_key:"default",display_name:"Default",flavour_code:null,flavour_label:null,size_value:"300",size_unit:"g",pack_count:null,product_format:"powder",is_active:true,is_default:true},retailer:{id:10,name:"Jon's Supplements",slug:"jon-s-supplements",website:"https://jonssupplements.co.uk"},mapping:{id:3,retailer_id:10,product_id:1,product_variant_id:2,external_product_id:"100",external_variant_id:"200",external_sku:"SKU",external_options:null,external_name:"Test",external_slug:"test",external_gtin:null,external_url:"https://jonssupplements.co.uk/products/test?variant=200",match_method:"EXACT",match_confidence:"1",updated_at:"2026-07-22T10:00:00Z"},offer:{id:4,product_id:1,retailer_id:10,product_variant_id:2,retailer_product_id:3,price:"10.00",shipping_cost:"3.99",total_price:"13.99",in_stock:true,url:"https://jonssupplements.co.uk/products/test?variant=200",last_checked_at:"2026-07-22T10:00:00Z"}};

test("stock-only update builds a source-bound existing-identity standard plan",()=>{const snapshot="a".repeat(64),built=buildExistingOfferUpdatePlan({...state,source:{external_product_id:"100",external_variant_id:"200",price:"10.00",shipping_cost:"3.99",total_price:"13.99",in_stock:false,url:state.offer.url},sourceCapturedAt:"2026-07-22T11:00:00Z",sourceSnapshotFingerprint:snapshot});assert.deepEqual(built.changed,{price:false,stock:true,url:false});assert.equal(built.plan.meta.operation_type,"standard_import");assert.equal(built.plan.meta.source_snapshot_sha256,snapshot);assert.equal(built.plan.meta.source_captured_at,"2026-07-22T11:00:00.000Z");assert.equal(built.plan.product.action,"existing");assert.equal(built.plan.product_variant.action,"existing");assert.equal(built.plan.retailer_product.action,"noop");assert.equal(built.plan.offer.action,"update");assert.equal(built.plan.price_history.action,"noop")});
test("identity drift and false no-op standard updates block",()=>{assert.throws(()=>buildExistingOfferUpdatePlan({...state,source:{external_product_id:"999",external_variant_id:"200",price:"10.00",shipping_cost:"3.99",total_price:"13.99",in_stock:false,url:state.offer.url},sourceCapturedAt:"2026-07-22T11:00:00Z",sourceSnapshotFingerprint:"a".repeat(64)}),/identity drift/);assert.throws(()=>buildExistingOfferUpdatePlan({...state,source:{external_product_id:"100",external_variant_id:"200",price:"10.00",shipping_cost:"3.99",total_price:"13.99",in_stock:true,url:state.offer.url},sourceCapturedAt:"2026-07-22T11:00:00Z",sourceSnapshotFingerprint:"a".repeat(64)}),/changed field/)});
test("standard update preserves PostgreSQL microsecond expected state",()=>{const precise={...state,mapping:{...state.mapping,updated_at:"2026-07-22T10:00:00.123456Z"},offer:{...state.offer,last_checked_at:"2026-07-22T10:00:00.654321Z"}},built=buildExistingOfferUpdatePlan({...precise,source:{external_product_id:"100",external_variant_id:"200",price:"10.00",shipping_cost:"3.99",total_price:"13.99",in_stock:false,url:state.offer.url},sourceCapturedAt:"2026-07-22T11:00:00Z",sourceSnapshotFingerprint:"a".repeat(64)});assert.equal(built.plan.expected_state.retailer_product.updated_at,"2026-07-22T10:00:00.123456Z");assert.equal(built.plan.expected_state.offer.last_checked_at,"2026-07-22T10:00:00.654321Z")});
test("offer-only updates preserve mapping options in expected state without reinterpreting variant identity",()=>{const withOptions={...state,variant:{...state.variant,size_value:null,size_unit:null},mapping:{...state.mapping,external_options:{Size:"60 capsules",Subscription:"[Multibuy 1]"}}},built=buildExistingOfferUpdatePlan({...withOptions,source:{external_product_id:"100",external_variant_id:"200",price:"11.00",shipping_cost:"3.99",total_price:"14.99",in_stock:true,url:state.offer.url},sourceCapturedAt:"2026-07-22T11:00:00Z",sourceSnapshotFingerprint:"a".repeat(64)});assert.equal(built.plan.product_variant.evidence.external_options,null);assert.deepEqual(built.plan.expected_state.retailer_product.external_options,withOptions.mapping.external_options);assert.equal(built.plan.product_variant.action,"existing");assert.equal(built.plan.retailer_product.action,"noop")});
test("URL updates bind existing mapping options as exact variant evidence",()=>{const withOptions={...state,mapping:{...state.mapping,external_options:{Size:"2000g",Flavour:"Biscoff Spread"}}},nextUrl="https://jonssupplements.co.uk/products/new-handle?variant=200",built=buildExistingOfferUpdatePlan({...withOptions,source:{external_product_id:"100",external_variant_id:"200",price:"10.00",shipping_cost:"3.99",total_price:"13.99",in_stock:true,url:nextUrl},sourceCapturedAt:"2026-07-22T11:00:00Z",sourceSnapshotFingerprint:"a".repeat(64)});assert.equal(built.plan.retailer_product.action,"update");assert.deepEqual(built.plan.product_variant.evidence.external_options,withOptions.mapping.external_options);assert.deepEqual(built.plan.retailer_product.values.external_options,withOptions.mapping.external_options);assert.equal(built.plan.retailer_product.values.external_url,nextUrl)});
test("delta aggregation preserves freshness and stock counts",()=>{const total=sumDeltas([{expected_deltas:rowDelta(0)},{expected_deltas:rowDelta(1)}]);assert.equal(total.logical_field_deltas.last_checked_at_updates,2);assert.equal(total.logical_field_deltas.offer_stock_updates,1);assert.equal(total.row_count_deltas.price_history,0)});
test("guard evidence retains unchanged MASS_OOS limits",()=>{const policy="a".repeat(64),rows=[{action:"UPDATE_STOCK",changed_fields:{price:false},atomic_plan:{expected_state:{offer:{in_stock:true}},offer:{values:{in_stock:false}}}}];const guard=guardrailsFor(rows,224,policy);assert.equal(guard.policy_fingerprint,policy);assert.equal(guard.limits.maximum_new_oos_count,"3");assert.equal(guard.limits.maximum_oos_increase_ratio,"0.15");assert.equal(guard.new_oos_count,1)});
test("Jon's Shopify variant IDs stay authoritative when optional source SKU metadata changes",()=>{assert.equal(config.guardrails.ignore_source_sku,true)});
test("reviewed missing variants are exact, OOS-only and any fourth absence blocks",()=>{const reviewed=loadReviewedMissingVariantManifest();assert.equal(reviewed.manifest.rows.length,3);assert.equal(reviewed.sha256,config.reviewed_missing_variant_manifest_sha256);const records=reviewed.manifest.rows.map((row,index)=>({product:{id:row.canonical_product_id},variant:{id:row.canonical_variant_id},mapping:{id:row.mapping_id,external_product_id:row.external_product_id,external_variant_id:row.external_variant_id,external_sku:row.external_sku,external_url:`https://jonssupplements.co.uk/products/test-${index}?variant=${row.external_variant_id}`},offer:{id:row.offer_id,price:"10.00",shipping_cost:"3.99"}}));const result=reconcileReviewedMissingVariants(records,[],reviewed);assert.equal(result.sourceVariants.length,3);assert.ok(result.sourceVariants.every(row=>row.in_stock===false&&row.price==="10.00"&&row.shipping_cost==="3.99"&&row.reviewed_source_absent));assert.throws(()=>reconcileReviewedMissingVariants([...records,{product:{id:"1"},variant:{id:"2"},mapping:{id:"3",external_product_id:"4",external_variant_id:"5",external_sku:null,external_url:"https://jonssupplements.co.uk/products/x?variant=5"},offer:{id:"6",price:"1.00",shipping_cost:"3.99"}}],[],reviewed),/unreviewed Jon's mapped variants/)});
test("ordinary 506-row validation partitions balance historical OOS rows and avoid a tiny-tail false alarm",()=>{const rows=Array.from({length:506},(_,index)=>{const currentOos=index>=475,changed=index===501;return{offer_id:String(992+index),action:changed?"UPDATE_STOCK":"VERIFY_NO_CHANGE",changed_fields:{price:false,stock:changed,url:false,blocked:false},atomic_plan:{expected_state:{offer:{in_stock:changed?true:!currentOos}},offer:{values:{in_stock:!currentOos}}}}});const batches=partitionExecutionRows(rows,50);assert.equal(batches.length,11);assert.equal(batches.reduce((sum,batch)=>sum+batch.length,0),506);for(const batch of batches){assert.ok(batch.length<=50);assert.deepEqual(batch.map(row=>Number(row.offer_id)),[...batch].map(row=>Number(row.offer_id)).sort((a,b)=>a-b));const guard=guardrailsFor(batch,229,"a".repeat(64));assert.ok(guard.new_oos_count<=3);assert.ok(guard.total_oos_count/batch.length<=0.35);assert.ok((guard.total_oos_count-guard.previous_oos_count)/batch.length<=0.15)}});
test("classifier diagnostics retain exact changed row IDs and declared guard scope",()=>{const classification={state:"BLOCKED",reason:"MASS_OOS",rows:[{offer_id:"1",retailer_product_id:"11",external_product_id:"101",external_variant_id:"1001",action:"UPDATE_STOCK",changed_fields:{price:false,stock:true,url:false,blocked:false}},{offer_id:"2",retailer_product_id:"12",external_product_id:"102",external_variant_id:"1002",action:"VERIFY_NO_CHANGE",changed_fields:{price:false,stock:false,url:false,blocked:false}}],guard_evidence:{scope_name:"JONS_FULL_506",retailer:"Jon's Supplements",scope_row_ids:["1","2"],total:2,changed:1}};const diagnostic=classificationDiagnostic(classification);assert.equal(diagnostic.reason,"MASS_OOS");assert.deepEqual(diagnostic.changed_row_ids,["1"]);assert.deepEqual(diagnostic.action_counts,{UPDATE_STOCK:1,VERIFY_NO_CHANGE:1});assert.equal(diagnostic.scope.scope_name,"JONS_FULL_506")});
test("reviewed OOS execution selects only exact approved rows and rejects any extra new OOS",()=>{const reviewed={reviewed_rows:[{external_product_id:"100",external_variant_id:"200",action:"UPDATE_STOCK"}]};const rows=Array.from({length:506},(_,index)=>({offer_id:String(index+1),external_product_id:String(100+index),external_variant_id:String(200+index),action:"VERIFY_NO_CHANGE",target:{in_stock:true},source:{in_stock:true}}));rows[0]={...rows[0],action:"UPDATE_STOCK",source:{in_stock:false}};rows[1]={...rows[1],action:"UPDATE_PRICE",target:{in_stock:true},source:{in_stock:true}};const classification={reason:"MASS_OOS",rows};assert.deepEqual(selectReviewedClassificationRows(classification,reviewed),[rows[0]]);rows[2]={...rows[2],action:"UPDATE_STOCK",source:{in_stock:false}};assert.throws(()=>selectReviewedClassificationRows(classification,reviewed),/outside the owner-approved scope/)});

test("reviewed Jon's price execution is limited to offer 1098 at 9.99",()=>{const reviewed={manifest:{kind:"jons-existing-offer-1-price-change-reviewed-manifest"},reviewed_rows:[{external_product_id:"10074965508434",external_variant_id:"50781523575122",action:"UPDATE_PRICE"}]};const rows=Array.from({length:506},(_,index)=>({offer_id:String(index+1),retailer_product_id:String(index+1000),external_product_id:String(index+2000),external_variant_id:String(index+3000),action:"VERIFY_NO_CHANGE",target:{price:"1.00",in_stock:true},source:{price:"1.00",in_stock:true}}));const approved={offer_id:"1098",retailer_product_id:"1284",external_product_id:"10074965508434",external_variant_id:"50781523575122",action:"UPDATE_PRICE",target:{price:"27.95",in_stock:true},source:{price:"9.99",in_stock:true}};rows[97]=approved;assert.deepEqual(selectReviewedClassificationRows({state:"DRY_RUN_READY",rows},reviewed),[approved]);rows[98]={...rows[98],action:"UPDATE_STOCK",source:{price:"1.00",in_stock:false}};rows[99]={...rows[99],action:"UPDATE_PRICE",source:{price:"2.00",in_stock:true}};assert.deepEqual(selectReviewedClassificationRows({reason:"MASS_OOS",rows},reviewed),[approved]);rows[97]={...approved,source:{price:"10.99",in_stock:true}};assert.throws(()=>selectReviewedClassificationRows({reason:"MASS_OOS",rows},reviewed),/owner-approved offer 1098 scope/)});
test("offer 1098 price manifest and workflow are exact and never enabled by schedule",()=>{const manifest=loadReviewedMixedChangeManifest(path.join(process.cwd(),"config/retailers/jons-reviewed-price-change-2026-08-18.json"),"6d9a854bc3cdda674b3ded7d27eb54f11aa1903bba851024077770e7ac51158e");assert.equal(manifest.manifest.kind,"jons-existing-offer-1-price-change-reviewed-manifest");assert.deepEqual(manifest.manifest.immutable_scope_offer_ids,["1098"]);assert.equal(manifest.manifest.rows[0].new_price,"9.99");const workflow=fs.readFileSync(path.join(process.cwd(),".github/workflows/jons-offer-refresh.yml"),"utf8");assert.match(workflow,/reviewed_price_1098:/);assert.match(workflow,/github\.event_name == 'workflow_dispatch' && inputs\.reviewed_price_1098 \|\| false/);assert.equal((workflow.match(/jons-reviewed-price-change-2026-08-18\.json/g)||[]).length,2);assert.equal((workflow.match(/6d9a854bc3cdda674b3ded7d27eb54f11aa1903bba851024077770e7ac51158e/g)||[]).length,2)});
test("CLI scope is closed",()=>{assert.deepEqual(parseArgs(["--target=production","--mode=dry-run"]),{target:"production",mode:"dry-run"});assert.deepEqual(parseArgs(["--target=staging","--mode=apply","--reviewed-manifest=manifest.json","--reviewed-manifest-sha256="+"a".repeat(64)]),{target:"staging",mode:"apply","reviewed-manifest":"manifest.json","reviewed-manifest-sha256":"a".repeat(64)});assert.throws(()=>parseArgs(["--target=other","--mode=apply"]));assert.throws(()=>parseArgs(["--target=production","--mode=unsafe"]));assert.throws(()=>parseArgs(["--target=production","--mode=apply","--reviewed-manifest=manifest.json"]));assert.throws(()=>parseArgs(["--target=production","--mode=apply","--unknown=true"]))});
test("verification records omit mapping audit-only columns",()=>{const record=verificationRecord(state,{external_product_id:"100",external_variant_id:"200",price:"10.00",in_stock:true,url:state.offer.url},"a".repeat(64),"2026-07-22T11:00:00Z");assert.equal(Object.hasOwn(record.target.retailer_product,"updated_at"),false);assert.deepEqual(Object.keys(record.target.retailer_product).sort(),["external_gtin","external_name","external_options","external_product_id","external_sku","external_slug","external_url","external_variant_id","id","match_confidence","match_method","product_id","product_variant_id","retailer_id"].sort())});
test("verification records serialize PostgreSQL timestamp values",()=>{const record=verificationRecord({...state,offer:{...state.offer,last_checked_at:new Date("2026-07-22T10:00:00Z")}},{external_product_id:"100",external_variant_id:"200",price:"10.00",in_stock:true,url:state.offer.url},"a".repeat(64),"2026-07-22T11:00:00Z");assert.equal(record.target.offer.last_checked_at,"2026-07-22T10:00:00.000Z")});
test("control hashes use the JSON value sent to PostgreSQL",()=>{assert.equal(canonicalHash({timestamp:new Date("2026-07-22T10:00:00Z"),omitted:undefined}),canonicalHash({timestamp:"2026-07-22T10:00:00.000Z"}))});
test("migration bindings exclude only environment-specific ledgers",()=>{assertMigrationBindingContract(migrationFiles)});
test("later unrelated migrations do not change the retailer registration binding contract",()=>{const laterUnrelatedMigration="99999999999999_unrelated_future_migration.sql";assertMigrationBindingContract([...migrationFiles,laterUnrelatedMigration]);for(const environment of ["STAGING","PRODUCTION"])assert.equal(migrationBinding(environment,[...migrationFiles,laterUnrelatedMigration]).versions.includes(laterUnrelatedMigration.slice(0,-4)),true)});
test("execution rows use the validator closed schema",()=>{const input={offer_id:"1",retailer_product_id:"2",external_product_id:"3",external_variant_id:"4",action:"VERIFY_NO_CHANGE",changed_fields:{},source_captured_at:"now",expected_deltas:{},atomic_plan:{},source:{diagnostic:true},target:{diagnostic:true},policy_fingerprint:"a"};assert.deepEqual(Object.keys(executionRow(input)).sort(),["offer_id","retailer_product_id","external_product_id","external_variant_id","action","changed_fields","source_captured_at","expected_deltas","atomic_plan"].sort())});
test("reviewed registration keeps one exact child and binds its contract into the request hash",()=>{const expiresAt=new Date(Date.now()+10*60000).toISOString(),contract={reviewed_contract_hash:"a".repeat(64)},run={target:"production",spec:{environment:"PRODUCTION",ref:"aftboxmrdgyhizicfsfu",identity:"supplementscout-production:aftboxmrdgyhizicfsfu"},artifacts:[{artifact_fingerprint:"b".repeat(64)}],snapshot:{semantic_source_fingerprint:"c".repeat(64)},capturedAt:new Date().toISOString(),manifest:[],manifestFingerprint:"d".repeat(64),head:"e".repeat(40),reviewed:{},reviewedExpiresAt:expiresAt,reviewedContract:contract};const request=registrationRequest(run);assert.equal(request.children.length,1);assert.equal(request.reviewed_mixed_change_contract,contract);assert.equal(request.expires_at,expiresAt);assert.equal(request.request_fingerprint,canonicalHash({...request,request_fingerprint:null}))});
test("two-default-flavour correction is exact, production-only and cannot alter catalogue rows",()=>{const migration=fs.readFileSync(path.join(process.cwd(),"supabase","migrations","20260731120000_correct_jons_two_default_flavour_variants.sql"),"utf8"),rollback=fs.readFileSync(path.join(process.cwd(),"supabase","rollbacks","20260731120000_correct_jons_two_default_flavour_variants.sql"),"utf8");for(const token of ["id=1188","id=1261","id=1302","id=1375","id=1116","id=1189","10563642065234","52597672542546","10088748908882","50838685286738","berry-465g","fizzy-blue-bottles-300g"])assert.match(migration,new RegExp(token));assert.match(migration,/requires production database owner/);assert.doesNotMatch(migration,/(?:insert into|delete from) public\.(?:products|product_variants|retailers|retailer_products|offers|price_history)/i);assert.doesNotMatch(migration,/update public\.(?:products|offers|price_history)/i);assert.match(rollback,/rollback is forbidden after either corrected offer has been refreshed/)});

function sourceCounts(productCount,variantCount,{complete=true}={}){
  const products=Array.from({length:productCount},(_,index)=>({id:index+1,variants:[]}));
  for(let index=0;index<variantCount;index++)products[index%Math.max(1,productCount)]?.variants.push({id:index+1});
  return{snapshot:{products,source_diagnostic:{pagination_completed:complete}},variants:Array.from({length:variantCount},(_,index)=>({external_variant_id:String(index+1)}) )};
}
test("source health accepts baseline and catalogue growth without weakening the 90 percent guard",()=>{
  for(const [products,variants] of [[224,844],[225,847]]){const value=sourceCounts(products,variants);const result=sourceHealth(value.snapshot,value.variants);assert.equal(result.result,"PASS");assert.ok(result.observed_ratio>=1)}
});
test("source health distinguishes incomplete, degraded and genuine collapse",()=>{
  let value=sourceCounts(0,0);assert.equal(sourceHealth(value.snapshot,value.variants).code,"SOURCE_INCOMPLETE");
  value=sourceCounts(210,740);assert.equal(sourceHealth(value.snapshot,value.variants).code,"SOURCE_DEGRADED");
  value=sourceCounts(100,400);assert.equal(sourceHealth(value.snapshot,value.variants).code,"GENUINE_SOURCE_COLLAPSE");
  value=sourceCounts(224,844,{complete:false});assert.equal(sourceHealth(value.snapshot,value.variants).code,"SOURCE_INCOMPLETE");
});
test("diagnostic artifact is written on success",async()=>{
  const outDir=fs.mkdtempSync(path.join(os.tmpdir(),"jons-refresh-success-"));
  const completed=await runWithDiagnostic(["--target=production","--mode=dry-run"],{outDir,operation:async(_args,diagnostic)=>{diagnostic.approved_mapping_count=506;diagnostic.mappings_matched=506;diagnostic.validator_result="PASS";return{result:"PASS"}}});
  const artifact=JSON.parse(fs.readFileSync(completed.diagnostic_path,"utf8"));
  assert.equal(artifact.result,"PASS");assert.equal(artifact.approved_mapping_count,506);assert.equal(artifact.mappings_matched,506);assert.equal(artifact.database_writes_completed,0);
});
test("diagnostic artifact is written before a guard failure and records zero writes",async()=>{
  const outDir=fs.mkdtempSync(path.join(os.tmpdir(),"jons-refresh-failure-"));
  await assert.rejects(runWithDiagnostic(["--target=production","--mode=dry-run"],{outDir,operation:async()=>{throw new RefreshError("SOURCE_INCOMPLETE","pagination incomplete","SOURCE_GUARD")}}),/pagination incomplete/);
  const artifact=JSON.parse(fs.readFileSync(path.join(outDir,"production-dry-run-diagnostic.json"),"utf8"));
  assert.equal(artifact.result,"FAIL");assert.equal(artifact.failure_stage,"SOURCE_GUARD");assert.equal(artifact.error_code,"SOURCE_INCOMPLETE");assert.equal(artifact.database_writes_attempted,0);assert.equal(artifact.database_writes_completed,0);assert.equal(artifact.approvals_created,0);assert.equal(artifact.recovery_calls,0);
});
test("failed classifier dry-run preserves evidence and performs zero control or business writes",async()=>{
  const outDir=fs.mkdtempSync(path.join(os.tmpdir(),"jons-refresh-classifier-failure-"));
  const guard={scope_name:"JONS_FULL_506",scope_row_ids:["1"],total:1,changed:1,ratio:1,threshold:0.25,result:"BLOCK"};
  await assert.rejects(runWithDiagnostic(["--target=production","--mode=dry-run"],{outDir,operation:async(_args,diagnostic)=>{diagnostic.classifier_summary={state:"BLOCKED",reason:"MASS_CHANGE",scope:guard};throw new RefreshError("MASS_CHANGE","full Jon's classifier blocked","CLASSIFIER",{guard_evidence:guard})}}),/full Jon's classifier blocked/);
  const artifact=JSON.parse(fs.readFileSync(path.join(outDir,"production-dry-run-diagnostic.json"),"utf8"));
  assert.equal(artifact.error_code,"MASS_CHANGE");assert.equal(artifact.classifier_summary.scope.scope_name,"JONS_FULL_506");assert.equal(artifact.error_detail.guard_evidence.changed,1);assert.equal(artifact.database_writes_attempted,0);assert.equal(artifact.database_writes_completed,0);assert.equal(artifact.business_writes_completed,0);assert.equal(artifact.control_writes_completed,0);
});
