const assert = require("node:assert/strict");
const crypto = require("node:crypto");
const fs = require("node:fs");
const path = require("node:path");
const { spawn, spawnSync } = require("node:child_process");
const test = require("node:test");
const policy = require("./config/retailers/jons-supplements");
const { buildClassificationArtifact } = require("./lib/retailer-snapshot/classifier");
const { buildParentPlan } = require("./lib/retailer-snapshot/parent-plan-builder");
const { LocalLedgerClient, sqlLiteral } = require("./retailer-snapshot-phase2-ledger");

const ROOT = path.resolve(__dirname, "..");
const MIGRATION = path.join(ROOT, "supabase/migrations/20260717120000_create_retailer_catalogue_control_ledger.sql");
const SQL_TEST = path.join(ROOT, "supabase/test/retailer_catalogue_control_ledger_integration_test.sql");
const IMAGE = "postgres:17-alpine";
function run(command,args,timeout=120000){return spawnSync(command,args,{cwd:ROOT,encoding:"utf8",timeout});}
function requireSuccess(result,label){assert.equal(result.error,undefined,`${label}: ${result.error?.message}`);assert.equal(result.status,0,`${label}: ${result.stderr||result.stdout}`);return result;}
function dockerAvailable(){const result=run("docker",["version","--format","{{.Server.Version}}"],10000);return result.status===0;}
function dockerExec(container,args,timeout=120000){return run("docker",["exec",container,...args],timeout);}
function psql(container,database,sql){return dockerExec(container,["psql","-X","--no-psqlrc","-v","ON_ERROR_STOP=1","-U","postgres","-d",database,"-tA","-c",sql]);}
function psqlFile(container,database,file,variables={}){const variableArgs=Object.entries(variables).flatMap(([key,value])=>["-v",`${key}=${value}`]);return dockerExec(container,["psql","-X","--no-psqlrc","-v","ON_ERROR_STOP=1",...variableArgs,"-U","postgres","-d",database,"-f",`/workspace/${path.relative(ROOT,file).replaceAll("\\","/")}`]);}
function waitForPostgres(container){for(let i=0;i<80;i+=1){const logs=run("docker",["logs",container],5000);if(/PostgreSQL init process complete; ready for start up\./i.test(`${logs.stdout}\n${logs.stderr}`)){const result=dockerExec(container,["psql","-X","--no-psqlrc","-U","postgres","-d","postgres","-tAc","select 1"],5000);if(result.status===0&&result.stdout.trim()==="1")return;}Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,250);}assert.fail("PostgreSQL did not start");}
function parallelPsql(container,database,sql){return new Promise((resolve)=>{const child=spawn("docker",["exec",container,"psql","-X","--no-psqlrc","-v","ON_ERROR_STOP=1","-U","postgres","-d",database,"-tA","-c",sql],{cwd:ROOT});let stdout="",stderr="";child.stdout.on("data",(b)=>stdout+=b);child.stderr.on("data",(b)=>stderr+=b);child.on("close",(status)=>resolve({status,stdout,stderr}));});}
function preview(offset,sourceDigit){
  const records=Array.from({length:96},(_,i)=>({source_record_id:String(offset+i+1),external_product_id:String(offset+i+1001),external_variant_id:String(offset+i+2001),source_fingerprint:sourceDigit.repeat(64),raw:{}}));
  const snapshot={snapshot_id:`00000000-0000-4000-8${String(offset).padStart(3,"0").slice(-3)}-000000000001`,source_sha256:sourceDigit.repeat(64),records};
  const contexts=new Map(records.map((r,i)=>[r.source_record_id,{primary_status:i<26?"SAFE_EXISTING_VARIANT":"SAFE_NEW_CANONICAL_PRODUCT",reason_codes:i<26?["IDENTITY_EXACT_EXTERNAL_VARIANT"]:["IDENTITY_EXACT_FORMAT","IDENTITY_EXACT_SIZE"],proposed_action:i<26?"NOOP":"CREATE_CANONICAL_PRODUCT",approval_level:"PARENT_APPROVAL",dependency_group:`group:${r.external_product_id}`,rollback_group:`group:${r.external_product_id}`} ]));
  const canonical={snapshot_id:`00000000-0000-4000-8${String(offset).padStart(3,"0").slice(-3)}-000000000003`,captured_at:new Date().toISOString(),fingerprint:"b".repeat(64),indexes:{}};
  const classification=buildClassificationArtifact({snapshot,canonicalSnapshot:canonical,policy,contexts,metadata:{classification_id:`00000000-0000-4000-8${String(offset).padStart(3,"0").slice(-3)}-000000000002`,code_commit:"53446ce6ed755f484e25551a757d4d0161e8a290"}});
  const result=buildParentPlan({classification,sourceSnapshot:snapshot,canonicalSnapshot:canonical,policy,metadata:{code_commit:"53446ce6ed755f484e25551a757d4d0161e8a290",retailer_id:"0"}});return{snapshot,classification,...result};
}
function childControl(child,parent){return{child_plan_id:child.child_plan_id,child_plan_fingerprint:child.child_plan_fingerprint,source_snapshot_fingerprint:parent.source_sha256,canonical_snapshot_fingerprint:parent.canonical_snapshot_fingerprint,adapter_fingerprint:parent.adapter_sha256,policy_fingerprint:parent.policy_config_sha256,code_commit:parent.code_commit,expected_state_fingerprint:child.expected_state.parent_core_fingerprint};}
function createWithControl(client, plan, actor, control = {}) {
  const envelope={parent_plan:plan.parent,child_plans:plan.children,control:{target_environment:"LOCAL_POSTGRES",retailer_id:"0",source_captured_at:new Date().toISOString(),canonical_snapshot_at:new Date().toISOString(),expected_state_fingerprint:plan.parent.canonical_snapshot_fingerprint,...control}};
  return client.query(`select public.create_retailer_catalogue_parent_plan(${sqlLiteral(JSON.stringify(envelope))}::jsonb,${sqlLiteral(plan.parent.parent_plan_fingerprint)},${sqlLiteral(plan.parent.source_sha256)},${sqlLiteral(actor)})::text;`);
}
function beginSql(child,parent,actor){const c=childControl(child,parent);return`select public.begin_retailer_catalogue_child_apply(${sqlLiteral(c.child_plan_id)}::uuid,${sqlLiteral(parent.parent_plan_fingerprint)},${sqlLiteral(c.child_plan_fingerprint)},${sqlLiteral(c.source_snapshot_fingerprint)},${sqlLiteral(c.canonical_snapshot_fingerprint)},${sqlLiteral(c.adapter_fingerprint)},${sqlLiteral(c.policy_fingerprint)},${sqlLiteral(c.code_commit)},${sqlLiteral(c.expected_state_fingerprint)},${sqlLiteral(actor)})::text;`;}
function parseLast(output){return JSON.parse(output.trim().split(/\r?\n/).at(-1));}

test("control-ledger migration is control-plane-only and retains existing approval architecture",()=>{
  const sql=fs.readFileSync(MIGRATION,"utf8");assert.match(sql,/^begin;/i);assert.match(sql,/create table if not exists public\.retailer_catalogue_parent_plans/i);assert.match(sql,/create table if not exists public\.retailer_catalogue_child_plans/i);assert.match(sql,/create table if not exists public\.retailer_catalogue_apply_runs/i);assert.match(sql,/security definer/gi);assert.match(sql,/force row level security/gi);assert.match(sql,/pg_advisory_xact_lock/i);assert.doesNotMatch(sql,/create table[^;]+review/i);assert.doesNotMatch(sql,/\b(?:insert\s+into|update|delete\s+from)\s+public\.(?:products|product_variants|retailers|retailer_products|offers|price_history|approved_import_plans)\b/i);assert.doesNotMatch(sql,/apply_product_import_plan\s*\(/i);
});

test("parent/child lifecycle, concurrency, resume, replay and rollback metadata pass on disposable PostgreSQL",{skip:!dockerAvailable()&&"Docker daemon unavailable"},async()=>{
  const container=`supplementscout-ledger-${crypto.randomBytes(5).toString("hex")}`;const database="supplementscout_retailer_ledger_test";let primaryError=null;
  try{
    requireSuccess(run("docker",["run","--detach","--rm","--name",container,"--network","none","-e","POSTGRES_HOST_AUTH_METHOD=trust","-v",`${ROOT}:/workspace:ro`,IMAGE],180000),"start PostgreSQL");waitForPostgres(container);requireSuccess(dockerExec(container,["createdb","-U","postgres",database]),"create database");
    requireSuccess(psql(container,database,"do $roles$ begin if not exists(select 1 from pg_roles where rolname='anon')then create role anon nologin;end if;if not exists(select 1 from pg_roles where rolname='authenticated')then create role authenticated nologin;end if;if not exists(select 1 from pg_roles where rolname='service_role')then create role service_role nologin;end if;end $roles$;"),"roles");requireSuccess(psqlFile(container,database,MIGRATION),"migration");requireSuccess(psqlFile(container,database,MIGRATION),"migration rerun");requireSuccess(psqlFile(container,database,SQL_TEST,{expected_database:database}),"SQL contract test");
    const client=new LocalLedgerClient({command:"status",allowLocalLedger:true,target:"local-postgres","database-url":`postgresql://postgres@127.0.0.1/${database}`,"docker-container":container},{});
    const schema=client.query("select jsonb_build_object('tables',(select count(*) from pg_tables where schemaname='public' and tablename like 'retailer_catalogue_%'),'rls',(select count(*) from pg_class where relnamespace='public'::regnamespace and relname like 'retailer_catalogue_%' and relrowsecurity and relforcerowsecurity),'functions',(select count(*) from pg_proc where pronamespace='public'::regnamespace and proname like '%retailer_catalogue%'))::text;");assert.deepEqual(schema.tables,3);assert.deepEqual(schema.rls,3);assert.ok(schema.functions>=17);
    const success=preview(10000,"a");assert.deepEqual(success.children.map(c=>c.record_ids.length),[50,46]);const created=client.create(success.parent,success.children,"integration-success");assert.equal(created.noop,false);const duplicate=client.create(success.parent,success.children,"integration-success");assert.equal(duplicate.noop,true);
    const approved=client.approveParent(created.parent_plan_id,success.parent.parent_plan_fingerprint,"operator");assert.equal(approved.status,"APPROVED");assert.equal(client.approveParent(created.parent_plan_id,success.parent.parent_plan_fingerprint,"operator").noop,true);assert.equal(client.generateChildren(created.parent_plan_id,success.parent.parent_plan_fingerprint).child_count,2);assert.equal(client.generateChildren(created.parent_plan_id,success.parent.parent_plan_fingerprint).noop,true);
    assert.throws(()=>client.approveChild(success.children[0].child_plan_id,approved.approval_id,success.parent.parent_plan_fingerprint,"f".repeat(64)),error=>error.code==="RSBI_CHILD_FINGERPRINT_MISMATCH");
    client.approveChild(success.children[0].child_plan_id,approved.approval_id,success.parent.parent_plan_fingerprint,success.children[0].child_plan_fingerprint);
    const concurrent=await Promise.all([parallelPsql(container,database,beginSql(success.children[0],success.parent,"parallel-a")),parallelPsql(container,database,beginSql(success.children[0],success.parent,"parallel-b"))]);assert.equal(concurrent.filter(r=>r.status===0).length,1);assert.match(concurrent.find(r=>r.status!==0).stderr,/RSBI_REPLAY_BLOCKED/);const firstRun=parseLast(concurrent.find(r=>r.status===0).stdout);const firstComplete=client.completeChild(firstRun.run_id,success.parent.parent_plan_fingerprint,success.children[0].child_plan_fingerprint,"operator");assert.equal(firstComplete.parent_status,"PARTIALLY_APPLIED");
    const resume=client.resume(created.parent_plan_id,success.parent.parent_plan_fingerprint,"PREVIEW","operator");assert.equal(resume.ready_children.length,1);assert.equal(resume.skipped_applied,1);client.approveChild(success.children[1].child_plan_id,approved.approval_id,success.parent.parent_plan_fingerprint,success.children[1].child_plan_fingerprint);
    const runsBeforeMismatch=client.query("select jsonb_build_object('count',count(*))::text from public.retailer_catalogue_apply_runs;").count;assert.throws(()=>client.beginChild({...childControl(success.children[1],success.parent),code_commit:"f".repeat(40)},success.parent.parent_plan_fingerprint,"operator"),error=>error.code==="RSBI_EXPECTED_STATE_MISMATCH");const runsAfterMismatch=client.query("select jsonb_build_object('count',count(*))::text from public.retailer_catalogue_apply_runs;").count;assert.equal(runsAfterMismatch,runsBeforeMismatch);
    const secondRun=client.beginChild(childControl(success.children[1],success.parent),success.parent.parent_plan_fingerprint,"operator");const secondComplete=client.completeChild(secondRun.run_id,success.parent.parent_plan_fingerprint,success.children[1].child_plan_fingerprint,"operator");assert.equal(secondComplete.parent_status,"COMPLETED");const replay=client.beginChild(childControl(success.children[1],success.parent),success.parent.parent_plan_fingerprint,"operator");assert.equal(replay.code,"RSBI_REPLAY_BLOCKED");assert.equal(client.create(success.parent,success.children,"integration-success").noop,true);
    assert.throws(()=>client.query(`update public.retailer_catalogue_child_plans set status='APPLYING' where id=${sqlLiteral(success.children[0].child_plan_id)}::uuid returning '{}'::jsonb::text;`),error=>error.code==="RSBI_INVALID_TRANSITION");assert.throws(()=>client.query(`delete from public.retailer_catalogue_parent_plans where id=${sqlLiteral(created.parent_plan_id)}::uuid returning '{}'::jsonb::text;`),/foreign key|violates/i);
    const failure=preview(20000,"c");const failureCreated=client.create(failure.parent,failure.children,"integration-failure");const failureApproved=client.approveParent(failureCreated.parent_plan_id,failure.parent.parent_plan_fingerprint,"operator");client.generateChildren(failureCreated.parent_plan_id,failure.parent.parent_plan_fingerprint);client.approveChild(failure.children[0].child_plan_id,failureApproved.approval_id,failure.parent.parent_plan_fingerprint,failure.children[0].child_plan_fingerprint);const f1=client.beginChild(childControl(failure.children[0],failure.parent),failure.parent.parent_plan_fingerprint,"operator");client.completeChild(f1.run_id,failure.parent.parent_plan_fingerprint,failure.children[0].child_plan_fingerprint,"operator");client.approveChild(failure.children[1].child_plan_id,failureApproved.approval_id,failure.parent.parent_plan_fingerprint,failure.children[1].child_plan_fingerprint);const f2=client.beginChild(childControl(failure.children[1],failure.parent),failure.parent.parent_plan_fingerprint,"operator");const failed=client.failChild(f2.run_id,failure.parent.parent_plan_fingerprint,failure.children[1].child_plan_fingerprint,"RSBI_EXPECTED_STATE_MISMATCH","operator");assert.equal(failed.parent_status,"FAILED");const failureResume=client.resume(failureCreated.parent_plan_id,failure.parent.parent_plan_fingerprint,"PREVIEW","operator");assert.equal(failureResume.ready_children.length,0);assert.equal(failureResume.blocked_dependency_groups.length,1);const rollback=client.requestRollback(failure.children[0].child_plan_id,failure.parent.parent_plan_fingerprint,failure.children[0].child_plan_fingerprint,failure.parent.rollback_manifest.rollback_fingerprint,"operator");const rollbackDone=client.completeRollback(rollback.run_id,failure.parent.parent_plan_fingerprint,failure.children[0].child_plan_fingerprint,"operator");assert.equal(rollbackDone.status,"ROLLED_BACK");assert.equal(rollbackDone.parent_status,"FAILED");
    const stale=preview(30000,"d");const staleCreated=createWithControl(client,stale,"integration-stale",{canonical_snapshot_at:"2000-01-01T00:00:00.000Z"});assert.throws(()=>client.approveParent(staleCreated.parent_plan_id,stale.parent.parent_plan_fingerprint,"operator"),error=>error.code==="RSBI_CANONICAL_SNAPSHOT_STALE");
    const expired=preview(40000,"e");const expiredCreated=client.create(expired.parent,expired.children,"integration-expired");client.approveParent(expiredCreated.parent_plan_id,expired.parent.parent_plan_fingerprint,"operator");client.query(`with changed as (update public.retailer_catalogue_parent_plans set approved_at=now()-interval '2 hours',approval_expires_at=now()-interval '1 hour' where id=${sqlLiteral(expiredCreated.parent_plan_id)}::uuid returning 1) select jsonb_build_object('updated',(select count(*) from changed))::text;`);assert.throws(()=>client.resume(expiredCreated.parent_plan_id,expired.parent.parent_plan_fingerprint,"PREVIEW","operator"),error=>error.code==="RSBI_APPROVAL_EXPIRED");
    const childExpired=preview(50000,"f");const childExpiredCreated=client.create(childExpired.parent,childExpired.children,"integration-child-expired");const childExpiredApproval=client.approveParent(childExpiredCreated.parent_plan_id,childExpired.parent.parent_plan_fingerprint,"operator");client.generateChildren(childExpiredCreated.parent_plan_id,childExpired.parent.parent_plan_fingerprint);client.approveChild(childExpired.children[0].child_plan_id,childExpiredApproval.approval_id,childExpired.parent.parent_plan_fingerprint,childExpired.children[0].child_plan_fingerprint);client.query(`with changed as (update public.retailer_catalogue_child_plans set approved_at=now()-interval '20 minutes',approval_expires_at=now()-interval '1 minute' where id=${sqlLiteral(childExpired.children[0].child_plan_id)}::uuid returning 1) select jsonb_build_object('updated',(select count(*) from changed))::text;`);assert.throws(()=>client.beginChild(childControl(childExpired.children[0],childExpired.parent),childExpired.parent.parent_plan_fingerprint,"operator"),error=>error.code==="RSBI_APPROVAL_EXPIRED");
    const counts=client.query("select jsonb_build_object('parents',(select count(*) from public.retailer_catalogue_parent_plans),'children',(select count(*) from public.retailer_catalogue_child_plans),'runs',(select count(*) from public.retailer_catalogue_apply_runs),'business_tables',(select count(*) from pg_tables where schemaname='public' and tablename in ('products','product_variants','retailers','retailer_products','offers','price_history')))::text;");assert.deepEqual(counts,{parents:5,children:6,runs:5,business_tables:0});
    const successReport={result:"PASS",parent_status:client.status(created.parent_plan_id).parent.status,child_sizes:success.children.map(c=>c.record_ids.length),concurrency:{attempts:2,succeeded:1,blocked:1,code:"RSBI_REPLAY_BLOCKED"},resume_ready:resume.ready_children.length,replay:replay.code,control_writes:{parents:1,children:2,runs:2},business_writes:0};const failureReport={result:"PASS",parent_status:client.status(failureCreated.parent_plan_id).parent.status,child_statuses:client.status(failureCreated.parent_plan_id).children.map(c=>c.status),resume_ready:failureResume.ready_children.length,blocked_dependency_groups:failureResume.blocked_dependency_groups,rollback_status:rollbackDone.status,control_writes:{parents:1,children:2,runs:3},business_writes:0};fs.writeFileSync(path.join(ROOT,"tmp/jons-phase-2-ledger-success-simulation.json"),`${JSON.stringify(successReport,null,2)}\n`);fs.writeFileSync(path.join(ROOT,"tmp/jons-phase-2-ledger-failure-simulation.json"),`${JSON.stringify(failureReport,null,2)}\n`);
  }catch(error){primaryError=error;throw error;}finally{const cleanup=run("docker",["rm","-f",container],30000);if(!primaryError&&cleanup.status!==0)assert.fail(cleanup.stderr);}
});
