const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");
const policy = require("./config/retailers/jons-supplements");
const { buildClassificationArtifact } = require("./lib/retailer-snapshot/classifier");
const { buildParentPlan } = require("./lib/retailer-snapshot/parent-plan-builder");
const { validateClassificationArtifact, validateParentPlan } = require("./lib/retailer-snapshot/validators");

function fixture(count=96){const records=Array.from({length:count},(_,i)=>({source_record_id:String(i+1),external_product_id:String(i+1000),external_variant_id:String(i+2000),source_fingerprint:"a".repeat(64),raw:{}}));const snapshot={snapshot_id:"00000000-0000-4000-8000-000000000001",source_sha256:"a".repeat(64),records};const contexts=new Map(records.map((r,i)=>[r.source_record_id,{primary_status:i<26?"SAFE_EXISTING_VARIANT":"SAFE_NEW_CANONICAL_PRODUCT",reason_codes:i<26?["IDENTITY_EXACT_EXTERNAL_VARIANT"]:["IDENTITY_EXACT_FORMAT","IDENTITY_EXACT_SIZE"],proposed_action:i<26?"NOOP":"CREATE_CANONICAL_PRODUCT",approval_level:"PARENT_APPROVAL",dependency_group:`group:${r.external_product_id}`,rollback_group:`group:${r.external_product_id}`} ]));return{snapshot,contexts};}
test("96-record read-only flow classifies 26 existing + 70 simple and seals 50/46 children",()=>{const {snapshot,contexts}=fixture();const canonical={snapshot_id:"00000000-0000-4000-8000-000000000003",captured_at:"1970-01-01T00:00:00.000Z",fingerprint:"b".repeat(64),indexes:{}};const classification=buildClassificationArtifact({snapshot,canonicalSnapshot:canonical,policy,contexts});assert.deepEqual(classification.totals,{SAFE_EXISTING_VARIANT:26,SAFE_NEW_CANONICAL_PRODUCT:70});assert.equal(validateClassificationArtifact(classification,snapshot.records.map((r)=>r.source_record_id)),true);const plans=buildParentPlan({classification,sourceSnapshot:snapshot,canonicalSnapshot:canonical,policy});assert.deepEqual(plans.children.map((c)=>c.record_ids.length),[50,46]);assert.equal(validateParentPlan(plans.parent,plans.children),true);});
test("Phase 1 modules prove no Supabase client, RPC or SQL write implementation",()=>{const dir=path.resolve("scripts/lib/retailer-snapshot");const files=[...fs.readdirSync(dir).filter((name)=>name.endsWith(".js")&&!name.endsWith(".test.js")).map((name)=>path.join(dir,name)),path.resolve("scripts/retailer-snapshot-phase1.js")];const text=files.map((file)=>fs.readFileSync(file,"utf8")).join("\n");assert.doesNotMatch(text,/require\(["']@supabase\/supabase-js/);assert.doesNotMatch(text,/\.rpc\s*\(/);assert.doesNotMatch(text,/\b(?:INSERT|UPDATE|DELETE)\s+(?:INTO|FROM|[a-z_]+\s+SET)\b/i);assert.doesNotMatch(text,/SAFE_UPDATE\s*=/);});
test("read-only CLI rejects write-bearing flags",()=>{const {args}=require("./retailer-snapshot-phase1");for(const flag of ["--apply","--approve","--rpc"])assert.throws(()=>args([flag]),/read-only/);});
test("read-only CLI requires caller-supplied source paths and embeds no private defaults",()=>{const {main}=require("./retailer-snapshot-phase1");assert.throws(()=>main([]),/Required read-only inputs/);});
