const assert = require("node:assert/strict");
const crypto = require("node:crypto");
const path = require("node:path");
const { spawnSync } = require("node:child_process");
const test = require("node:test");
const { canonicalJson } = require("./lib/canonical-json");
const { buildReviewedVariantCreateRebindPlan } = require("./lib/reviewed-variant-create-rebind-offer-update");

const ROOT = path.resolve(__dirname, "..");
const MIGRATION = "supabase/migrations/20260901090000_add_reviewed_variant_create_rebind_offer_update.sql";
const DIGEST_FIX_MIGRATION = "supabase/migrations/20260901100000_fix_reviewed_variant_digest_schema_resolution.sql";
const IMAGE = "postgres:17-alpine";
function run(command, args, options = {}) { return spawnSync(command, args, { cwd: ROOT, encoding: "utf8", timeout: options.timeout || 180_000, input: options.input }); }
function output(result) { return `${result.stdout || ""}\n${result.stderr || ""}`; }
function ok(result, label) { assert.equal(result.error, undefined, `${label}: ${result.error?.message}`); assert.equal(result.status, 0, `${label}:\n${output(result)}`); return result; }
function dockerAvailable() { return run("docker", ["version", "--format", "{{.Server.Version}}"], { timeout: 10_000 }).status === 0; }
function exec(container, args, options = {}) { return run("docker", ["exec", ...(options.stdin ? ["-i"] : []), container, ...args], options); }
function sql(container, text, expectSuccess = true) {
  const result = exec(container, ["psql", "-X", "--no-psqlrc", "-v", "ON_ERROR_STOP=1", "-U", "postgres", "-d", "postgres", "-tA", "-f", "-"], { stdin: true, input: text });
  if (expectSuccess) ok(result, "SQL");
  return result;
}
function json(container, text) { const result = sql(container, `select (${text})::text;`); return JSON.parse(result.stdout.trim()); }
function literal(value) { return `'${JSON.stringify(value).replaceAll("'", "''")}'::jsonb`; }
function wait(container) {
  for (let index = 0; index < 80; index += 1) {
    if (exec(container, ["pg_isready", "-U", "postgres"]).status === 0) return;
    Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, 250);
  }
  assert.fail("PostgreSQL unavailable");
}
function fixture() {
  const now = Date.now();
  const state = {
    product: { id: 69, name: "Efectiv Nutrition Vegan Protein 908g", slug: "efectiv-nutrition-vegan-protein-908g", brand: "Efectiv", category: "Whey Protein", net_weight_g: 900, product_format: "powder", is_active: true, merged_into_product_id: null },
    variant: { id: 64, product_id: 69, variant_key: "default", display_name: "Default", flavour_code: null, flavour_label: null, size_value: null, size_unit: null, pack_count: null, product_format: null, gtin: null, is_active: true, is_default: true },
    retailer: { id: 3, name: "Whey Okay", slug: "whey-okay", website: "https://wheyokay.com" },
    mapping: { id: 65, retailer_id: 3, product_id: 69, product_variant_id: 64, external_product_id: null, external_variant_id: null, external_sku: null, external_options: null, external_name: "Efectiv Nutrition Vegan Protein 908g", external_slug: "efectiv-nutrition-vegan-protein-908g", external_gtin: null, external_url: "https://wheyokay.com/efectiv-nutrition-vegan-protein-908g-300-p.asp", match_method: "existing_offer", match_confidence: 100, updated_at: "2026-06-30T19:40:13.950Z" },
    offer: { id: 73, product_id: 69, retailer_id: 3, product_variant_id: 64, retailer_product_id: 65, price: 24.99, shipping_cost: 3.99, total_price: null, in_stock: false, url: "https://wheyokay.com/efectiv-nutrition-vegan-protein-908g-300-p.asp", last_checked_at: "2026-06-29T12:32:18.530Z" },
  };
  const source = { external_product_id: "300", external_variant_id: "301", title: "Efectiv Nutrition Vegan Protein 908g - Biscuit Spread", flavour: "Biscuit Spread", weight_value: "908", weight_unit: "g", price: "22.70", shipping_cost: "3.99", in_stock: true, url: state.offer.url, source_url: `${state.offer.url}?_=&variantid=301`, gtin: null, mpn: null };
  const semantic = "a".repeat(64);
  return buildReviewedVariantCreateRebindPlan({ state, source, captures: [{ captured_at: new Date(now - 120_000).toISOString(), semantic_fingerprint: semantic }, { captured_at: new Date(now - 60_000).toISOString(), semantic_fingerprint: semantic }], expiresAt: new Date(now + 15 * 60_000).toISOString() });
}
const setup = `
create schema extensions; create extension pgcrypto with schema extensions;
create role anon nologin; create role authenticated nologin; create role service_role nologin;
create table public.retailers(id bigint primary key,name text,slug text,website text);
create table public.products(id bigint primary key,name text,slug text,brand text,category text,net_weight_g numeric,product_format text,is_active boolean,merged_into_product_id bigint);
create table public.product_variants(id bigint generated by default as identity primary key,product_id bigint,variant_key text,display_name text,flavour_code text,flavour_label text,size_value numeric,size_unit text,pack_count integer,product_format text,gtin text,nutrition_override jsonb,is_active boolean,is_default boolean);
create table public.retailer_products(id bigint primary key,retailer_id bigint,product_id bigint,product_variant_id bigint,external_product_id text,external_variant_id text,external_sku text,external_options jsonb,external_name text,external_slug text,external_gtin text,external_url text,match_method text,match_confidence numeric,created_at timestamptz default now(),updated_at timestamptz);
create table public.offers(id bigint primary key,product_id bigint,retailer_id bigint,product_variant_id bigint,retailer_product_id bigint,price numeric,shipping_cost numeric,total_price numeric,in_stock boolean,url text,last_checked_at timestamptz);
create table public.price_history(id bigint generated by default as identity primary key,offer_id bigint,price numeric,shipping_cost numeric,total_price numeric,checked_at timestamptz);
create table public.approved_import_plans(id uuid primary key default gen_random_uuid(),artifact_sha256 text,run_id text,plan_fingerprint text,source_row_fingerprint text,plan_kind text,retailer_id bigint,created_at timestamptz default now(),expires_at timestamptz,consumed_at timestamptz,source text,plan_json jsonb,status text default 'approved',identity_observation_result jsonb);
alter table public.approved_import_plans enable row level security; alter table public.approved_import_plans force row level security; revoke all on public.approved_import_plans from public,anon,authenticated,service_role;
create function public.atomic_import_has_exact_keys(p jsonb,k text[]) returns boolean language sql immutable as $$select jsonb_typeof(p)='object' and (select array_agg(key order by key) from jsonb_object_keys(p) key)=(select array_agg(x order by x) from unnest(k)x)$$;
create function public.atomic_import_canonical_json(v jsonb) returns text language plpgsql immutable strict as $$declare r text;begin case jsonb_typeof(v) when 'object' then select '{'||coalesce(string_agg(to_jsonb(e.key)::text||':'||public.atomic_import_canonical_json(e.value),',' order by e.key),'')||'}' into r from jsonb_each(v)e; when 'array' then select '['||coalesce(string_agg(public.atomic_import_canonical_json(e.value),',' order by e.ordinality),'')||']' into r from jsonb_array_elements(v) with ordinality e(value,ordinality); else r:=v::text; end case;return r;end$$;
create function public.atomic_import_decimal_string(v numeric) returns text language sql immutable as $$select v::text$$;
create function public.validate_product_import_plan_read_only(jsonb) returns jsonb language sql stable as $$select '{"legacy":true}'::jsonb$$;
create function public.apply_product_import_plan(jsonb) returns jsonb language sql volatile as $$select '{"legacy":true}'::jsonb$$;
create function public.apply_approved_product_import_plan(uuid,text,text,text,bigint,text,text) returns jsonb language sql volatile as $$select '{"legacy":true}'::jsonb$$;
create function public.record_identity_proven_price_observation(bigint,text,text,text,bigint) returns jsonb language sql volatile as $$select '{"status":"IDENTITY_OBSERVATION_DISABLED"}'::jsonb$$;
create function public.retailer_catalogue_actual_database_target() returns jsonb language sql stable as $$select '{"target_environment":"PRODUCTION","project_ref":"aftboxmrdgyhizicfsfu","database_identity":"supplementscout-production:aftboxmrdgyhizicfsfu"}'::jsonb$$;
create function public.approve_product_import_plan(p_plan jsonb,p_artifact text,p_run text,p_source text,p_expiry timestamptz) returns jsonb language plpgsql volatile security definer as $$declare i uuid;begin perform public.validate_product_import_plan_read_only(p_plan); insert into public.approved_import_plans(artifact_sha256,run_id,plan_fingerprint,source_row_fingerprint,plan_kind,retailer_id,expires_at,source,plan_json) values(p_artifact,p_run,p_plan#>>'{meta,plan_fingerprint}',p_plan#>>'{meta,source_row_fingerprint}',p_plan#>>'{meta,plan_kind}',(p_plan#>>'{retailer,id}')::bigint,p_expiry,p_source,p_plan) returning id into i;return jsonb_build_object('approval_id',i);end$$;
insert into public.retailers values(3,'Whey Okay','whey-okay','https://wheyokay.com');
insert into public.products values(69,'Efectiv Nutrition Vegan Protein 908g','efectiv-nutrition-vegan-protein-908g','Efectiv','Whey Protein',900,'powder',true,null);
insert into public.product_variants(id,product_id,variant_key,display_name,flavour_code,flavour_label,size_value,size_unit,pack_count,product_format,gtin,nutrition_override,is_active,is_default) values(64,69,'default','Default',null,null,null,null,null,null,null,'{}',true,true);
select setval(pg_get_serial_sequence('public.product_variants','id'),64,true);
insert into public.retailer_products values(65,3,69,64,null,null,null,null,'Efectiv Nutrition Vegan Protein 908g','efectiv-nutrition-vegan-protein-908g',null,'https://wheyokay.com/efectiv-nutrition-vegan-protein-908g-300-p.asp','existing_offer',100,now(),'2026-06-30T19:40:13.950Z');
insert into public.offers values(73,69,3,64,65,24.99,3.99,null,false,'https://wheyokay.com/efectiv-nutrition-vegan-protein-908g-300-p.asp','2026-06-29T12:32:18.530Z');
`;

test("reviewed variant create/rebind/update is atomic, fail-closed, private, and idempotent", { skip: !dockerAvailable() && "Docker unavailable" }, () => {
  const container = `supplementscout-reviewed-rebind-${crypto.randomBytes(5).toString("hex")}`;
  let primary;
  try {
    ok(run("docker", ["run", "--detach", "--rm", "--name", container, "--network", "none", "-e", "POSTGRES_PASSWORD=local-only", "-v", `${ROOT}:/workspace:ro`, IMAGE]), "start postgres");
    wait(container); sql(container, setup);
    ok(exec(container, ["psql", "-X", "--no-psqlrc", "-v", "ON_ERROR_STOP=1", "-U", "postgres", "-d", "postgres", "-f", `/workspace/${MIGRATION}`]), "apply migration");
    const preRepair = sql(container, `select public.validate_product_import_plan_read_only(${literal(fixture())});`, false);
    assert.notEqual(preRepair.status, 0);
    assert.match(output(preRepair), /function digest\(text, unknown\) does not exist/);
    ok(exec(container, ["psql", "-X", "--no-psqlrc", "-v", "ON_ERROR_STOP=1", "-U", "postgres", "-d", "postgres", "-f", `/workspace/${DIGEST_FIX_MIGRATION}`]), "apply digest repair");
    const plan = fixture();
    assert.equal(json(container, `public.validate_product_import_plan_read_only(${literal(plan)})` ).valid, true);
    const activeDefinition = json(container, `jsonb_build_object('unqualified',(select count(*) from regexp_matches(pg_get_functiondef('public.validate_reviewed_variant_create_rebind_offer_update_plan(jsonb)'::regprocedure),'(^|[^A-Za-z0-9_.])digest\\s*\\(','g')),'qualified',(select count(*) from regexp_matches(pg_get_functiondef('public.validate_reviewed_variant_create_rebind_offer_update_plan(jsonb)'::regprocedure),'extensions\\.digest\\s*\\(','g')),'search_path',(select proconfig from pg_proc where oid='public.validate_reviewed_variant_create_rebind_offer_update_plan(jsonb)'::regprocedure),'extension_schema',(select n.nspname from pg_proc p join pg_namespace n on n.oid=p.pronamespace where p.oid='extensions.digest(text,text)'::regprocedure))`);
    assert.deepEqual(activeDefinition, { unqualified:0, qualified:4, search_path:["search_path=pg_catalog, public, pg_temp"], extension_schema:"extensions" });
    const failClosedCounts = json(container, `jsonb_build_array((select count(*) from products),(select count(*) from product_variants),(select count(*) from retailer_products),(select count(*) from offers),(select count(*) from price_history))`);
    const wrongSource = structuredClone(plan);
    wrongSource.meta.source_row_fingerprint = "0".repeat(64);
    wrongSource.meta.plan_fingerprint = null;
    wrongSource.meta.plan_fingerprint = crypto.createHash("md5").update(canonicalJson(wrongSource)).digest("hex");
    const wrongSourceResult = sql(container, `select public.validate_product_import_plan_read_only(${literal(wrongSource)});`, false);
    assert.notEqual(wrongSourceResult.status, 0);
    assert.match(output(wrongSourceResult), /source semantics or two-capture proof/);
    assert.doesNotMatch(output(wrongSourceResult), /function digest\(/);
    for (const mutation of ["update public.offers set price=25 where id=73", "update public.retailer_products set product_variant_id=999 where id=65", "update public.products set name='drift' where id=69"]) {
      const failed = sql(container, `begin;${mutation};select public.validate_product_import_plan_read_only(${literal(plan)});rollback;`, false);
      assert.notEqual(failed.status, 0, `stale mutation passed: ${mutation}`);
      assert.match(output(failed), /stale reviewed variant rebind plan/);
    }
    assert.deepEqual(json(container, `jsonb_build_array((select count(*) from products),(select count(*) from product_variants),(select count(*) from retailer_products),(select count(*) from offers),(select count(*) from price_history))`), failClosedCounts);
    assert.deepEqual(json(container, `public.validate_product_import_plan_read_only('{"meta":{"operation_type":"legacy"}}'::jsonb)`), { legacy:true });
    const artifact = "b".repeat(64), runId = "reviewed-rebind-integration";
    const approved = json(container, `public.approve_product_import_plan(${literal(plan)},'${artifact}','${runId}','integration-test',((${literal(plan)})#>>'{meta,expires_at}')::timestamptz)`);
    const before = json(container, `jsonb_build_object('product',(select to_jsonb(p) from products p where id=69),'counts',jsonb_build_array((select count(*) from products),(select count(*) from product_variants),(select count(*) from retailer_products),(select count(*) from offers),(select count(*) from price_history)))`);
    sql(container, `create function public.fail_reviewed_history() returns trigger language plpgsql as $$begin raise exception 'INJECTED_LAST_STEP_FAILURE';end$$;create trigger fail_reviewed_history before insert on public.price_history for each row execute function public.fail_reviewed_history();`);
    const call = `public.apply_approved_product_import_plan('${approved.approval_id}','${artifact}','${plan.meta.plan_fingerprint}','${plan.meta.source_row_fingerprint}',3,'feed','${runId}')`;
    assert.notEqual(sql(container, `select ${call};`, false).status, 0);
    const rolledBack = json(container, `jsonb_build_object('product',(select to_jsonb(p) from products p where id=69),'counts',jsonb_build_array((select count(*) from products),(select count(*) from product_variants),(select count(*) from retailer_products),(select count(*) from offers),(select count(*) from price_history)),'approval',(select status from approved_import_plans where id='${approved.approval_id}'))`);
    assert.deepEqual(rolledBack.product, before.product); assert.deepEqual(rolledBack.counts, before.counts); assert.equal(rolledBack.approval, "approved");
    sql(container, "drop trigger fail_reviewed_history on public.price_history;drop function public.fail_reviewed_history();");
    const applied = json(container, call); assert.equal(applied.status, "APPLIED"); assert.equal(applied.already_applied, false);
    const after = json(container, `jsonb_build_object('product',(select to_jsonb(p) from products p where id=69),'variant',(select jsonb_build_object('display_name',display_name,'flavour_code',flavour_code,'size_value',size_value,'size_unit',size_unit) from product_variants where id<>64),'mapping',(select jsonb_build_object('variant',product_variant_id,'product',external_product_id,'source_variant',external_variant_id) from retailer_products where id=65),'offer',(select jsonb_build_object('variant',product_variant_id,'price',price,'shipping',shipping_cost,'total',total_price,'stock',in_stock,'url',url) from offers where id=73),'counts',jsonb_build_array((select count(*) from products),(select count(*) from product_variants),(select count(*) from retailer_products),(select count(*) from offers),(select count(*) from price_history)))`);
    assert.deepEqual(after.product, before.product); assert.deepEqual(after.counts, [1,2,1,1,1]); assert.deepEqual(after.variant, { display_name:"Biscuit Spread / 908g", flavour_code:"biscuit-spread", size_value:908, size_unit:"g" });
    assert.equal(after.mapping.product,"300"); assert.equal(after.mapping.source_variant,"301"); assert.equal(after.mapping.variant,after.offer.variant);
    assert.deepEqual(after.offer, { variant:after.offer.variant, price:22.70, shipping:3.99, total:26.69, stock:true, url:"https://wheyokay.com/efectiv-nutrition-vegan-protein-908g-300-p.asp" });
    const replay = json(container, call); assert.equal(replay.status,"ALREADY_APPLIED"); assert.equal(replay.already_applied,true);
    const replayCounts = json(container, `jsonb_build_array((select count(*) from products),(select count(*) from product_variants),(select count(*) from retailer_products),(select count(*) from offers),(select count(*) from price_history))`); assert.deepEqual(replayCounts,after.counts);
    const grants = json(container, `jsonb_build_object('approved',has_function_privilege('service_role','public.apply_approved_product_import_plan(uuid,text,text,text,bigint,text,text)','execute'),'raw_apply',has_function_privilege('service_role','public.apply_product_import_plan(jsonb)','execute'),'validator',has_function_privilege('service_role','public.validate_product_import_plan_read_only(jsonb)','execute'),'helper',has_function_privilege('service_role','public.apply_reviewed_variant_create_rebind_offer_update_plan(jsonb)','execute'),'anon_approved',has_function_privilege('anon','public.apply_approved_product_import_plan(uuid,text,text,text,bigint,text,text)','execute'),'authenticated_approved',has_function_privilege('authenticated','public.apply_approved_product_import_plan(uuid,text,text,text,bigint,text,text)','execute'))`);
    assert.deepEqual(grants,{ approved:true, raw_apply:false, validator:false, helper:false, anon_approved:false, authenticated_approved:false });
  } catch (error) { primary=error; throw error; } finally {
    const stopped=run("docker",["rm","--force",container],{timeout:30_000}); if(!primary && stopped.status!==0 && !/No such container/i.test(output(stopped))) ok(stopped,"stop postgres");
  }
});
