create table public.outbound_clicks (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  offer_id bigint null references public.offers(id) on delete set null,
  product_id bigint null references public.products(id) on delete set null,
  retailer_id bigint null references public.retailers(id) on delete set null,
  destination_url text not null,
  source_page text not null,

  constraint outbound_clicks_source_page_check
    check (source_page in ('product_best_offer', 'product_offer_list'))
);

create index outbound_clicks_created_at_idx
on public.outbound_clicks (created_at);

create index outbound_clicks_offer_id_idx
on public.outbound_clicks (offer_id);

create index outbound_clicks_product_id_idx
on public.outbound_clicks (product_id);

create index outbound_clicks_retailer_id_idx
on public.outbound_clicks (retailer_id);

alter table public.outbound_clicks enable row level security;
