begin;

set local lock_timeout='5s';
set local statement_timeout='120s';

do $apply$
declare
  v_target jsonb:=public.retailer_catalogue_actual_database_target();
  v_authority constant text:='owner-chat-2026-08-26-do-dziela-prepare-fit-house-retailer-evidence-batch-11';
  v_config_sha256 constant text:='69316475e96e470840874a2eeeffa7f4a19319a437e6d947da101c4668267fb7';
  v_manifest_sha256 constant text:='a1e596f7707c851534e04e30d13f4289439449556787c572736e77b279c75292';
  v_source_fingerprint constant text:='ef14011b0634d3f20053a569323eb8170defb458d28d22b1bbf700ef2416f1bb';
  v_scope constant jsonb:='[
    {"product_id":673,"product":"Now Foods Chaste Berry Vitex Extract 300mg 90 Capsules","default_variant_id":513,"mapping_id":683,"offer_id":691,"external_product_id":"9680391831792","external_variant_id":"48142863401200","external_sku":null,"external_options":null,"url":"https://fithouse.uk/products/now-foods-chaste-berry-vitex-extract-300-mg-90-vege-caps?variant=48142863401200","variant_key":"90-servings","display_name":"90 Servings","size_value":90,"size_unit":"servings","pack_count":1,"product_format":"capsule","price":19.99,"shipping":3.99,"total":23.98,"in_stock":true},
    {"product_id":674,"product":"Swanson L-Tyrosine 500mg 100 Capsules","default_variant_id":531,"mapping_id":684,"offer_id":692,"external_product_id":"9706776264944","external_variant_id":"48219037106416","external_sku":null,"external_options":null,"url":"https://fithouse.uk/products/swanson-l-tyrosine-500mg-100-caps?variant=48219037106416","variant_key":"100-servings","display_name":"100 Servings","size_value":100,"size_unit":"servings","pack_count":1,"product_format":"capsule","price":6.99,"shipping":3.99,"total":10.98,"in_stock":true},
    {"product_id":678,"product":"OstroVit Creatine Monohydrate 400 Capsules","default_variant_id":514,"mapping_id":688,"offer_id":696,"external_product_id":"10024895742192","external_variant_id":"49735378960624","external_sku":null,"external_options":null,"url":"https://fithouse.uk/products/ostrovit-creatine-monohydrate-400-caps?variant=49735378960624","variant_key":"133-servings","display_name":"133 Servings","size_value":133,"size_unit":"servings","pack_count":1,"product_format":"capsule","price":24.99,"shipping":3.99,"total":28.98,"in_stock":true},
    {"product_id":683,"product":"Osavi Super Strong Omega 3 500 EPA 250 DHA 60 Softgels","default_variant_id":544,"mapping_id":703,"offer_id":701,"external_product_id":"10079982944496","external_variant_id":"49957958156528","external_sku":null,"external_options":null,"url":"https://fithouse.uk/products/osavi-super-strong-omega-3-500-epa-250-dha-60-softgels?variant=49957958156528","variant_key":"60-servings","display_name":"60 Servings","size_value":60,"size_unit":"servings","pack_count":1,"product_format":"softgel","price":19.99,"shipping":3.99,"total":23.98,"in_stock":true},
    {"product_id":689,"product":"Trec Nutrition ALA 250mg 60 Capsules","default_variant_id":552,"mapping_id":709,"offer_id":707,"external_product_id":"10028561989872","external_variant_id":"49745363337456","external_sku":null,"external_options":null,"url":"https://fithouse.uk/products/trec-nutrition-ala-250-60-caps?variant=49745363337456","variant_key":"60-servings","display_name":"60 Servings","size_value":60,"size_unit":"servings","pack_count":1,"product_format":"capsule","price":9.99,"shipping":3.99,"total":13.98,"in_stock":true},
    {"product_id":690,"product":"Nutrend Creatine Compressed 120 Capsules","default_variant_id":554,"mapping_id":710,"offer_id":708,"external_product_id":"10028475810032","external_variant_id":"49745019797744","external_sku":null,"external_options":null,"url":"https://fithouse.uk/products/nutrend-creatine-compressed-capsules-120-caps?variant=49745019797744","variant_key":"40-servings","display_name":"40 Servings","size_value":40,"size_unit":"servings","pack_count":1,"product_format":"capsule","price":19.99,"shipping":3.99,"total":23.98,"in_stock":true},
    {"product_id":715,"product":"Doctor''s Best Fully Active B12 1500mcg 60 Capsules","default_variant_id":594,"mapping_id":796,"offer_id":734,"external_product_id":"8776311636208","external_variant_id":"45938991890672","external_sku":null,"external_options":null,"url":"https://fithouse.uk/products/doctors-best-fully-active-b12-1-500-mcg-60-vege-caps?variant=45938991890672","variant_key":"60-servings","display_name":"60 Servings","size_value":60,"size_unit":"servings","pack_count":1,"product_format":"capsule","price":9.99,"shipping":3.99,"total":13.98,"in_stock":true},
    {"product_id":726,"product":"Reflex Nutrition Magnesium Bisglycinate 90 Capsules","default_variant_id":627,"mapping_id":859,"offer_id":745,"external_product_id":"8685938376944","external_variant_id":"45768791982320","external_sku":null,"external_options":null,"url":"https://fithouse.uk/products/reflex-nutrition-magnesium-bisglycinate-90-caps?variant=45768791982320","variant_key":"30-servings","display_name":"30 Servings","size_value":30,"size_unit":"servings","pack_count":1,"product_format":"capsule","price":9.99,"shipping":3.99,"total":13.98,"in_stock":true},
    {"product_id":731,"product":"7Nutrition Coenzyme Q10 200mg 60 Capsules","default_variant_id":624,"mapping_id":864,"offer_id":750,"external_product_id":"9176724177136","external_variant_id":"46992608657648","external_sku":null,"external_options":null,"url":"https://fithouse.uk/products/7nutrition-coenzyme-q10-60-vege-caps?variant=46992608657648","variant_key":"60-servings","display_name":"60 Servings","size_value":60,"size_unit":"servings","pack_count":1,"product_format":"capsule","price":9.99,"shipping":3.99,"total":13.98,"in_stock":true},
    {"product_id":734,"product":"7Nutrition Vitamin D3 2000 IU 120 Softgels","default_variant_id":605,"mapping_id":867,"offer_id":753,"external_product_id":"9168643719408","external_variant_id":"46969317228784","external_sku":null,"external_options":null,"url":"https://fithouse.uk/products/7-nutrition-vitamin-d3-2000-120-gel-caps-copy?variant=46969317228784","variant_key":"120-servings","display_name":"120 Servings","size_value":120,"size_unit":"servings","pack_count":1,"product_format":"softgel","price":5.99,"shipping":3.99,"total":9.98,"in_stock":true},
    {"product_id":740,"product":"7Nutrition Berberine Stack 500mg 90 Capsules","default_variant_id":606,"mapping_id":873,"offer_id":759,"external_product_id":"9168824172784","external_variant_id":"46969725714672","external_sku":null,"external_options":null,"url":"https://fithouse.uk/products/7-nutrition-berberine-stack-90-vege-caps?variant=46969725714672","variant_key":"90-servings","display_name":"90 Servings","size_value":90,"size_unit":"servings","pack_count":1,"product_format":"capsule","price":11.99,"shipping":3.99,"total":15.98,"in_stock":true}
  ]'::jsonb;
  e record; v_target_variant_id bigint; v_rows integer; v_mapping_before jsonb; v_offer_before jsonb;
  v_products_before bigint; v_variants_before bigint; v_mappings_before bigint; v_offers_before bigint; v_history_before bigint; v_series_before bigint;
begin
  if current_user<>'postgres' or v_target->>'target_environment'<>'PRODUCTION'
    or v_target->>'project_ref'<>'aftboxmrdgyhizicfsfu' or v_target->>'database_identity'<>'supplementscout-production:aftboxmrdgyhizicfsfu'
    or v_authority<>'owner-chat-2026-08-26-do-dziela-prepare-fit-house-retailer-evidence-batch-11'
    or v_config_sha256!~'^[0-9a-f]{64}$' or v_manifest_sha256!~'^[0-9a-f]{64}$'
    or v_source_fingerprint<>'ef14011b0634d3f20053a569323eb8170defb458d28d22b1bbf700ef2416f1bb' then raise exception 'Fit House retailer-evidence batch authority, evidence or target mismatch'; end if;
  if jsonb_array_length(v_scope)<>11 or (select count(distinct (x->>'mapping_id')::bigint) from jsonb_array_elements(v_scope) x)<>11
    or exists(select 1 from jsonb_array_elements(v_scope) x where (x->>'mapping_id')::bigint in (686,687,2063,2084,2099,2107,2123)) then raise exception 'Fit House retailer-evidence batch scope mismatch'; end if;
  perform pg_advisory_xact_lock(hashtextextended('supplementscout:fit-house-exact-pack:retailer-evidence-11',0));
  select count(*) into v_products_before from public.products; select count(*) into v_variants_before from public.product_variants;
  select count(*) into v_mappings_before from public.retailer_products; select count(*) into v_offers_before from public.offers;
  select count(*) into v_history_before from public.price_history; select count(*) into v_series_before from public.price_identity_series;
  if v_products_before<>1112 or v_variants_before<>2747 or v_mappings_before<>2761 or v_offers_before<>2761 or v_history_before<>4001
    or (select count(*) from public.retailer_products rp join public.product_variants v on v.id=rp.product_variant_id where rp.retailer_id=9 and v.pack_count is not null and v.size_value is not null and nullif(trim(v.size_unit),'') is not null)<>181
    or (select count(*) from public.retailer_products where retailer_id=9)<>286 or (select count(*) from public.offers where retailer_id=9)<>286 then raise exception 'Fit House retailer-evidence batch baseline mismatch'; end if;
  for e in select * from jsonb_to_recordset(v_scope) as x(product_id bigint,product text,default_variant_id bigint,mapping_id bigint,offer_id bigint,external_product_id text,external_variant_id text,external_sku text,external_options jsonb,url text,variant_key text,display_name text,size_value numeric,size_unit text,pack_count integer,product_format text,price numeric,shipping numeric,total numeric,in_stock boolean) order by mapping_id loop
    if not exists(select 1 from public.products where id=e.product_id and name=e.product and is_active and merged_into_product_id is null for update)
      or not exists(select 1 from public.product_variants where id=e.default_variant_id and product_id=e.product_id and variant_key='default' and display_name='Default' and size_value is null and size_unit is null and pack_count is null and is_active and is_default for update)
      or exists(select 1 from public.product_variants where product_id=e.product_id and variant_key=e.variant_key)
      or exists(select 1 from public.price_identity_series where offer_id=e.offer_id) then raise exception 'Fit House product, target or prior-series mismatch for mapping %',e.mapping_id; end if;
    select to_jsonb(rp) into v_mapping_before from public.retailer_products rp where rp.id=e.mapping_id and rp.retailer_id=9 and rp.product_id=e.product_id and rp.product_variant_id=e.default_variant_id and rp.external_product_id=e.external_product_id and rp.external_variant_id=e.external_variant_id and rp.external_sku is not distinct from e.external_sku and coalesce(rp.external_options,'{}'::jsonb)=coalesce(e.external_options,'{}'::jsonb) and rp.external_url=e.url for update;
    select to_jsonb(o) into v_offer_before from public.offers o where o.id=e.offer_id and o.retailer_id=9 and o.product_id=e.product_id and o.product_variant_id=e.default_variant_id and o.retailer_product_id=e.mapping_id and o.price=e.price and o.shipping_cost=e.shipping and o.total_price=e.total and o.in_stock=e.in_stock and o.url=e.url for update;
    if v_mapping_before is null or v_offer_before is null then raise exception 'Fit House binding or commercial mismatch for mapping %',e.mapping_id; end if;
    insert into public.product_variants(product_id,variant_key,display_name,flavour_code,flavour_label,size_value,size_unit,pack_count,product_format,gtin,image,nutrition_override,is_default,is_active)
    values(e.product_id,e.variant_key,e.display_name,null,null,e.size_value,e.size_unit,e.pack_count,e.product_format,null,null,'{}'::jsonb,false,true) returning id into v_target_variant_id;
    update public.retailer_products set product_variant_id=v_target_variant_id where id=e.mapping_id and retailer_id=9 and product_variant_id=e.default_variant_id;
    get diagnostics v_rows=row_count; if v_rows<>1 then raise exception 'Fit House mapping move affected % rows',v_rows; end if;
    update public.offers set product_variant_id=v_target_variant_id where id=e.offer_id and retailer_product_id=e.mapping_id and product_variant_id=e.default_variant_id;
    get diagnostics v_rows=row_count; if v_rows<>1 then raise exception 'Fit House offer move affected % rows',v_rows; end if;
    if not exists(select 1 from public.retailer_products rp join public.offers o on o.retailer_product_id=rp.id where rp.id=e.mapping_id and o.id=e.offer_id and rp.product_variant_id=v_target_variant_id and o.product_variant_id=v_target_variant_id and (to_jsonb(rp)-'product_variant_id')=(v_mapping_before-'product_variant_id') and (to_jsonb(o)-'product_variant_id')=(v_offer_before-'product_variant_id')) then raise exception 'Fit House preservation mismatch for mapping %',e.mapping_id; end if;
  end loop;
  if (select count(*) from public.products)<>v_products_before or (select count(*) from public.product_variants)<>v_variants_before+11
    or (select count(*) from public.retailer_products)<>v_mappings_before or (select count(*) from public.offers)<>v_offers_before
    or (select count(*) from public.price_history)<>v_history_before or (select count(*) from public.price_identity_series)<>v_series_before
    or (select count(*) from public.retailer_products rp join public.product_variants v on v.id=rp.product_variant_id where rp.retailer_id=9 and v.pack_count is not null and v.size_value is not null and nullif(trim(v.size_unit),'') is not null)<>192 then raise exception 'Fit House retailer-evidence batch postcondition mismatch'; end if;
end $apply$;

commit;
