begin;

create table public.nutrition_candidates (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  product_id bigint references public.products(id) on delete restrict,
  retailer_id bigint references public.retailers(id) on delete restrict,
  source_type text not null check (
    source_type in (
      'manufacturer_product_page',
      'retailer_product_page',
      'retailer_feed'
    )
  ),
  source_url text not null check (
    length(source_url) between 9 and 2000
    and source_url ~ '^https://'
    and position('#' in source_url) = 0
    and source_url !~* '[?&](token|secret|signature|password|auth|api[_-]?key|credential|x-amz|x-goog|key|sig|code)='
  ),
  source_file_sha256 text not null check (source_file_sha256 ~ '^[0-9a-f]{64}$'),
  source_snapshot_ref text not null check (
    length(source_snapshot_ref) between 1 and 500
    and source_snapshot_ref ~ '^tmp/[A-Za-z0-9._/-]+$'
    and position('..' in source_snapshot_ref) = 0
  ),
  source_domain text not null check (
    source_domain = lower(source_domain)
    and source_domain ~ '^[a-z0-9.-]+\.[a-z]{2,}$'
  ),
  product_name text not null check (length(btrim(product_name)) between 1 and 300),
  brand text not null check (length(btrim(brand)) between 1 and 200),
  proposed_field text not null check (
    proposed_field in (
      'net_weight_g',
      'net_volume_ml',
      'serving_count_verified',
      'serving_size_g',
      'serving_size_ml',
      'protein_per_serving_g',
      'creatine_per_serving_g'
    )
  ),
  proposed_value numeric not null check (proposed_value > 0),
  proposed_unit text not null check (
    (proposed_field in (
      'net_weight_g',
      'serving_size_g',
      'protein_per_serving_g',
      'creatine_per_serving_g'
    ) and proposed_unit = 'g')
    or (proposed_field in ('net_volume_ml', 'serving_size_ml') and proposed_unit = 'ml')
    or (proposed_field = 'serving_count_verified' and proposed_unit = 'count')
  ),
  confidence text not null check (confidence in ('HIGH', 'MEDIUM', 'LOW')),
  evidence_snippet text not null check (length(btrim(evidence_snippet)) between 1 and 300),
  source_locator text not null check (length(btrim(source_locator)) between 1 and 500),
  warning_flags text[] not null default '{}'::text[] check (
    cardinality(warning_flags) <= 20
    and array_position(warning_flags, null) is null
  ),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  reviewed_at timestamptz,
  reviewed_by text check (reviewed_by is null or length(reviewed_by) between 1 and 200),
  review_note text check (review_note is null or length(review_note) <= 1000),
  run_id text not null check (length(run_id) between 1 and 200),
  candidate_fingerprint text not null unique check (candidate_fingerprint ~ '^[0-9a-f]{64}$'),
  check (
    lower(split_part(split_part(source_url, '://', 2), '/', 1))
      in (source_domain, 'www.' || source_domain)
  ),
  check (
    (status = 'pending' and reviewed_at is null and reviewed_by is null and review_note is null)
    or
    (status in ('approved', 'rejected') and reviewed_at is not null and reviewed_by is not null)
  )
);

create index nutrition_candidates_status_created_idx
  on public.nutrition_candidates (status, created_at desc, id desc);

create index nutrition_candidates_product_status_idx
  on public.nutrition_candidates (product_id, status)
  where product_id is not null;

create or replace function public.guard_nutrition_candidate_review_update()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  if old.status <> 'pending' then
    raise exception 'nutrition candidate has already been reviewed';
  end if;

  if new.status not in ('approved', 'rejected') then
    raise exception 'nutrition candidate review must approve or reject';
  end if;

  if row(
    new.id,
    new.created_at,
    new.product_id,
    new.retailer_id,
    new.source_type,
    new.source_url,
    new.source_file_sha256,
    new.source_snapshot_ref,
    new.source_domain,
    new.product_name,
    new.brand,
    new.proposed_field,
    new.proposed_value,
    new.proposed_unit,
    new.confidence,
    new.evidence_snippet,
    new.source_locator,
    new.warning_flags,
    new.run_id,
    new.candidate_fingerprint
  ) is distinct from row(
    old.id,
    old.created_at,
    old.product_id,
    old.retailer_id,
    old.source_type,
    old.source_url,
    old.source_file_sha256,
    old.source_snapshot_ref,
    old.source_domain,
    old.product_name,
    old.brand,
    old.proposed_field,
    old.proposed_value,
    old.proposed_unit,
    old.confidence,
    old.evidence_snippet,
    old.source_locator,
    old.warning_flags,
    old.run_id,
    old.candidate_fingerprint
  ) then
    raise exception 'nutrition candidate evidence is immutable';
  end if;

  return new;
end;
$$;

create trigger nutrition_candidates_review_update_guard
before update on public.nutrition_candidates
for each row execute function public.guard_nutrition_candidate_review_update();

alter table public.nutrition_candidates enable row level security;

revoke all on table public.nutrition_candidates from public, anon, authenticated;
revoke all on sequence public.nutrition_candidates_id_seq from public, anon, authenticated;
revoke all on function public.guard_nutrition_candidate_review_update()
  from public, anon, authenticated;

grant select, insert, update on table public.nutrition_candidates to service_role;
grant usage, select on sequence public.nutrition_candidates_id_seq to service_role;

comment on table public.nutrition_candidates is
  'Private review-only numeric nutrition candidates. Approval never updates canonical product data.';

commit;
