begin;

create table public.product_match_review_queue (
  id bigint generated by default as identity primary key,
  snapshot_id text not null check (length(snapshot_id) between 1 and 128),
  review_item_id text not null check (length(review_item_id) between 1 and 200),
  source_record_id text not null check (length(source_record_id) between 1 and 200),
  retailer text not null check (length(trim(retailer)) between 1 and 200),
  product_title text not null check (length(trim(product_title)) between 1 and 1000),
  variant_title text,
  primary_status text not null check (length(primary_status) between 1 and 100),
  reason_codes text not null default '',
  confidence text not null check (confidence in ('HIGH', 'MEDIUM', 'LOW')),
  canonical_candidates jsonb not null default '[]'::jsonb
    check (jsonb_typeof(canonical_candidates) = 'array'),
  source_sku text,
  source_gtin text,
  source_weight text,
  source_price numeric(12,2),
  source_url text,
  suggested_action text not null default '',
  decision text not null default 'PENDING'
    check (decision in (
      'PENDING',
      'APPROVE_EXISTING_VARIANT',
      'APPROVE_NEW_VARIANT_SEED',
      'APPROVE_NEW_PRODUCT',
      'APPROVE_NEW_FAMILY_SEED',
      'DEFER_POLICY',
      'MARK_OOS',
      'REJECT_IDENTITY',
      'REQUEST_NEW_SOURCE',
      'SUPERSEDE'
    )),
  selected_canonical_product_id bigint
    references public.products(id) on delete restrict,
  selected_canonical_variant_id bigint
    references public.product_variants(id) on delete restrict,
  reviewer_notes text check (
    reviewer_notes is null or length(reviewer_notes) <= 1000
  ),
  reviewed_by text,
  reviewed_at timestamptz,
  consumed_at timestamptz,
  source_row_fingerprint text not null
    check (source_row_fingerprint ~ '^[0-9a-f]{64}$'),
  artifact_fingerprint text not null
    check (artifact_fingerprint ~ '^[0-9a-f]{64}$'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint product_match_review_queue_snapshot_item_unique
    unique (snapshot_id, review_item_id),
  constraint product_match_review_queue_decision_state check (
    (
      decision = 'PENDING'
      and reviewed_by is null
      and reviewed_at is null
      and selected_canonical_product_id is null
      and selected_canonical_variant_id is null
    )
    or (
      decision = 'APPROVE_EXISTING_VARIANT'
      and selected_canonical_product_id is not null
      and selected_canonical_variant_id is not null
      and reviewed_by is not null
      and reviewed_at is not null
    )
    or (
      decision = 'APPROVE_NEW_VARIANT_SEED'
      and selected_canonical_product_id is not null
      and selected_canonical_variant_id is null
      and reviewed_by is not null
      and reviewed_at is not null
    )
    or (
      decision in (
        'APPROVE_NEW_PRODUCT',
        'APPROVE_NEW_FAMILY_SEED',
        'DEFER_POLICY',
        'MARK_OOS',
        'REJECT_IDENTITY',
        'REQUEST_NEW_SOURCE',
        'SUPERSEDE'
      )
      and selected_canonical_product_id is null
      and selected_canonical_variant_id is null
      and reviewed_by is not null
      and reviewed_at is not null
    )
  )
);

create index product_match_review_queue_decision_updated_idx
  on public.product_match_review_queue (decision, updated_at desc);

create index product_match_review_queue_retailer_snapshot_idx
  on public.product_match_review_queue (retailer, snapshot_id);

alter table public.product_match_review_queue enable row level security;

revoke all on table public.product_match_review_queue
  from public, anon, authenticated;
revoke all on sequence public.product_match_review_queue_id_seq
  from public, anon, authenticated;
grant select, insert, update on table public.product_match_review_queue
  to service_role;
grant usage, select on sequence public.product_match_review_queue_id_seq
  to service_role;

comment on table public.product_match_review_queue is
  'Read-only matcher proposals and administrator decisions. Rows never authorize direct catalogue writes.';

commit;
