create table public.search_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_type text not null,
  source_page text not null,
  query text not null,
  applied_query text null,
  corrected_query text null,
  result_count integer null,
  match_status text null,
  search_mode text null,
  suggestion_type text null,
  suggestion_label text null,
  suggestion_href text null,

  constraint search_events_event_type_check
    check (event_type in ('search_results', 'search_submit', 'suggestion_click')),
  constraint search_events_source_page_check
    check (source_page in ('homepage', 'search_page', 'unknown')),
  constraint search_events_match_status_check
    check (match_status is null or match_status in ('exact', 'corrected', 'none')),
  constraint search_events_search_mode_check
    check (search_mode is null or search_mode in ('standard_ilike')),
  constraint search_events_result_count_check
    check (result_count is null or result_count >= 0)
);

create index search_events_created_at_idx
on public.search_events (created_at);

create index search_events_event_type_created_at_idx
on public.search_events (event_type, created_at);

create index search_events_match_status_created_at_idx
on public.search_events (match_status, created_at);

alter table public.search_events enable row level security;
