create table public.ignored_duplicate_product_pairs (
  id bigint generated by default as identity primary key,
  product_a_id bigint not null references public.products(id) on delete cascade,
  product_b_id bigint not null references public.products(id) on delete cascade,
  ignored_at timestamptz not null default now(),

  constraint ignored_duplicate_product_pairs_not_same_product
    check (product_a_id <> product_b_id),

  constraint ignored_duplicate_product_pairs_ordered
    check (product_a_id < product_b_id),

  constraint ignored_duplicate_product_pairs_unique
    unique (product_a_id, product_b_id)
);

create index ignored_duplicate_product_pairs_product_a_idx
on public.ignored_duplicate_product_pairs (product_a_id);

create index ignored_duplicate_product_pairs_product_b_idx
on public.ignored_duplicate_product_pairs (product_b_id);

alter table public.ignored_duplicate_product_pairs enable row level security;
