begin;

create table public.nutrition_candidate_batch_items (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  run_id text not null check (length(run_id) between 1 and 200),
  source_record_id text not null check (length(btrim(source_record_id)) between 1 and 300),
  product_id bigint not null references public.products(id) on delete restrict,
  product_name text not null check (length(btrim(product_name)) between 1 and 300),
  brand text not null check (length(btrim(brand)) between 1 and 200),
  manufacturer text not null check (length(btrim(manufacturer)) between 1 and 200),
  source_url text not null check (
    length(source_url) between 9 and 2000
    and source_url ~ '^https://'
    and position('#' in source_url) = 0
    and source_url !~* '[?&](token|secret|signature|password|auth|api[_-]?key|credential|x-amz|x-goog|key|sig|code)='
  ),
  source_domain text not null check (
    source_domain = lower(source_domain)
    and source_domain ~ '^[a-z0-9.-]+\.[a-z]{2,}$'
  ),
  official_domains text[] not null check (
    cardinality(official_domains) between 1 and 20
    and array_position(official_domains, null) is null
  ),
  missing_fields text[] not null check (
    cardinality(missing_fields) between 1 and 7
    and array_position(missing_fields, null) is null
    and missing_fields <@ array[
      'net_weight_g',
      'net_volume_ml',
      'serving_count_verified',
      'serving_size_g',
      'serving_size_ml',
      'protein_per_serving_g',
      'creatine_per_serving_g'
    ]::text[]
  ),
  current_values jsonb not null default '{}'::jsonb check (jsonb_typeof(current_values) = 'object'),
  manifest_note text check (manifest_note is null or length(manifest_note) <= 1000),
  page_status text not null check (page_status in ('FETCHED', 'FAILED')),
  page_error text check (page_error is null or length(page_error) <= 2000),
  source_file_sha256 text check (
    source_file_sha256 is null or source_file_sha256 ~ '^[0-9a-f]{64}$'
  ),
  source_snapshot_ref text check (
    source_snapshot_ref is null or (
      source_snapshot_ref ~ '^tmp/[A-Za-z0-9._/-]+$'
      and position('..' in source_snapshot_ref) = 0
    )
  ),
  source_context_sha256 text not null check (source_context_sha256 ~ '^[0-9a-f]{64}$'),
  unique (run_id, product_id),
  unique (run_id, source_record_id),
  check (
    lower(split_part(split_part(source_url, '://', 2), '/', 1))
      = any(official_domains)
    or regexp_replace(lower(split_part(split_part(source_url, '://', 2), '/', 1)), '^www\.', '')
      = any(official_domains)
  ),
  check (
    (page_status = 'FETCHED' and source_file_sha256 is not null and source_snapshot_ref is not null)
    or (page_status = 'FAILED' and source_file_sha256 is null and source_snapshot_ref is null)
  )
);

create index nutrition_candidate_batch_items_run_idx
  on public.nutrition_candidate_batch_items (run_id, created_at, id);

alter table public.nutrition_candidate_batch_items enable row level security;

revoke all on table public.nutrition_candidate_batch_items from public, anon, authenticated;
revoke all on sequence public.nutrition_candidate_batch_items_id_seq from public, anon, authenticated;

grant select, insert on table public.nutrition_candidate_batch_items to service_role;
grant usage, select on sequence public.nutrition_candidate_batch_items_id_seq to service_role;

alter table public.nutrition_candidates
  drop constraint nutrition_candidates_source_type_check,
  add constraint nutrition_candidates_source_type_check check (
    source_type in (
      'manufacturer_product_page',
      'retailer_product_page',
      'retailer_feed',
      'owner_transcribed_official_page'
    )
  );

alter table public.nutrition_candidates
  drop constraint nutrition_candidates_source_snapshot_ref_check,
  add constraint nutrition_candidates_source_snapshot_ref_check check (
    (
      length(source_snapshot_ref) between 1 and 500
      and source_snapshot_ref ~ '^tmp/[A-Za-z0-9._/-]+$'
      and position('..' in source_snapshot_ref) = 0
    )
    or source_snapshot_ref ~ '^db:nutrition_candidate_batch_items/[1-9][0-9]*$'
  );

comment on table public.nutrition_candidate_batch_items is
  'Private immutable manifest work items. They expose missing fields for owner transcription but never approve or update catalogue data.';

comment on column public.nutrition_candidate_batch_items.missing_fields is
  'Extraction and owner-entry focus only. It is not verification, approval, or product-update authority.';

commit;
