begin;

set local lock_timeout = '5s';
set local statement_timeout = '60s';

do $preflight$
begin
  if to_regclass('public.price_identity_series') is not null
     or to_regclass('public.price_observation_producers') is not null
     or exists(select 1 from information_schema.columns where table_schema='public' and table_name='price_history' and column_name='identity_series_id') then
    raise exception 'identity-proven price observation foundation already exists; rerun rejected';
  end if;
  if to_regprocedure('public.apply_approved_product_import_plan(uuid,text,text,text,bigint,text,text)') is null
     or to_regprocedure('public.retailer_catalogue_sha256_json(jsonb)') is null
     or to_regprocedure('public.retailer_catalogue_business_counts()') is null then
    raise exception 'identity-proven observations require the current atomic offer and catalogue control paths';
  end if;
end
$preflight$;

create table public.price_identity_series (
  id bigint generated by default as identity primary key,
  identity_version smallint not null check(identity_version=1),
  fingerprint text not null unique check(fingerprint~'^[0-9a-f]{64}$'),
  offer_id bigint not null check(offer_id>0),
  retailer_id bigint not null check(retailer_id>0),
  retailer_product_id bigint not null check(retailer_product_id>0),
  product_id bigint not null check(product_id>0),
  product_variant_id bigint not null check(product_variant_id>0),
  external_product_id text not null check(length(trim(external_product_id)) between 1 and 128),
  external_variant_id text check(external_variant_id is null or length(trim(external_variant_id)) between 1 and 128),
  flavour text,
  size_value numeric not null check(size_value>0 and size_value::text<>'NaN'),
  size_unit text not null check(length(trim(size_unit)) between 1 and 32),
  pack_count integer not null check(pack_count>0),
  product_format text,
  unit_count integer check(unit_count is null or unit_count>0),
  unit_type text check(unit_type is null or length(trim(unit_type)) between 1 and 64),
  gtin text check(gtin is null or gtin~'^[0-9]{8,14}$'),
  retailer_source text not null check(retailer_source~'^[a-z0-9][a-z0-9-]{0,127}$'),
  source_importer text not null check(source_importer~'^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$'),
  currency text not null check(currency='GBP'),
  created_at timestamptz not null default clock_timestamp(),
  constraint price_identity_series_unit_pair check((unit_count is null)=(unit_type is null))
);

comment on table public.price_identity_series is
  'Immutable versioned exact offer/variant/pack identities for future price intelligence; IDs are historical values and intentionally do not cascade with mutable catalogue rows.';

create index price_identity_series_offer_created_idx
  on public.price_identity_series(offer_id,created_at desc,id desc);
create index price_identity_series_variant_pack_idx
  on public.price_identity_series(product_id,product_variant_id,pack_count,size_unit,size_value);

create function public.reject_price_identity_series_mutation()
returns trigger language plpgsql volatile security definer set search_path=pg_catalog,public,pg_temp as $immutable$
begin
  raise exception 'price identity series are immutable';
end
$immutable$;

create trigger price_identity_series_immutable
before update or delete on public.price_identity_series
for each row execute function public.reject_price_identity_series_mutation();

create table public.price_observation_producers (
  retailer_id bigint not null references public.retailers(id) on delete restrict,
  retailer_slug text not null,
  source_importer text not null check(source_importer~'^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$'),
  approved_scope text not null,
  technically_capable boolean not null,
  enabled boolean not null default false,
  public_use text not null check(public_use in ('eligible-after-separate-approval','owner-deferred','blocked')),
  terms_mode text not null check(terms_mode='standard-single-purchase-only'),
  updated_at timestamptz not null default clock_timestamp(),
  primary key(retailer_id,source_importer),
  constraint price_observation_producer_enable_guard check(not enabled or technically_capable)
);

insert into public.price_observation_producers
  (retailer_id,retailer_slug,source_importer,approved_scope,technically_capable,enabled,public_use,terms_mode)
values
  (7,'simply-supplements','retailer_offer_mixed_batch','approved-120',true,false,'eligible-after-separate-approval','standard-single-purchase-only'),
  (9,'fit-house','retailer_offer_mixed_batch','approved-286',true,false,'eligible-after-separate-approval','standard-single-purchase-only'),
  (10,'jon-s-supplements','retailer_offer_mixed_batch','reviewed-current-sync',true,false,'eligible-after-separate-approval','standard-single-purchase-only'),
  (3,'whey-okay','retailer_offer_mixed_batch','approved-586-only',true,false,'eligible-after-separate-approval','standard-single-purchase-only'),
  (1,'gym-high','gym-high-reviewed-full-catalogue-v1','reviewed-66',true,false,'owner-deferred','standard-single-purchase-only'),
  (11,'6-pack-supplements','retailer_offer_mixed_batch','blocked-pending-mass-oos-review',false,false,'blocked','standard-single-purchase-only'),
  (12,'ebay-uk','ebay-existing-offer-refresh-exact-237-v1','blocked-pending-237-continuity',false,false,'blocked','standard-single-purchase-only');

alter table public.price_history
  add column identity_series_id bigint,
  add column currency text,
  add column in_stock boolean,
  add column observation_kind text,
  add column source_run_id text,
  add column source_importer text,
  add column recorder_version smallint,
  add column observation_date date,
  add column evidence_status text,
  add column anomaly_flags text[];

-- Reuse the existing approval ledger as the durable per-operation report. This
-- keeps fail-closed skip reasons visible without creating a second import log.
alter table public.approved_import_plans
  add column identity_observation_result jsonb,
  add constraint approved_import_plans_identity_observation_result_check
    check(identity_observation_result is null or jsonb_typeof(identity_observation_result)='object');

alter table public.price_history
  add constraint price_history_identity_series_fkey foreign key(identity_series_id)
    references public.price_identity_series(id) on delete restrict,
  add constraint price_history_observation_kind_check check(observation_kind is null or observation_kind in ('offer_created','delivered_price_changed','daily_confirmation')),
  add constraint price_history_currency_check check(currency is null or currency='GBP'),
  add constraint price_history_recorder_version_check check(recorder_version is null or recorder_version=1),
  add constraint price_history_evidence_status_check check(evidence_status is null or evidence_status in ('proven','quarantined')),
  add constraint price_history_source_run_check check(source_run_id is null or source_run_id~'^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$'),
  add constraint price_history_source_importer_check check(source_importer is null or source_importer~'^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$'),
  add constraint price_history_proven_all_or_none check(
    (identity_series_id is null and currency is null and in_stock is null and observation_kind is null
      and source_run_id is null and source_importer is null and recorder_version is null
      and observation_date is null and evidence_status is null and anomaly_flags is null)
    or
    (identity_series_id is not null and currency='GBP' and in_stock is not null and observation_kind is not null
      and source_run_id is not null and source_importer is not null and recorder_version=1
      and observation_date is not null and evidence_status is not null and anomaly_flags is not null
      and price is not null and price>0 and price::text<>'NaN'
      and shipping_cost is not null and shipping_cost>=0 and shipping_cost::text<>'NaN'
      and total_price is not null and total_price>0 and total_price::text<>'NaN')
  );

create index price_history_proven_series_time_idx
  on public.price_history(identity_series_id,checked_at desc,id desc)
  where identity_series_id is not null;
create index price_history_proven_status_time_idx
  on public.price_history(evidence_status,checked_at desc)
  where identity_series_id is not null;
create unique index price_history_daily_confirmation_unique
  on public.price_history(identity_series_id,observation_date)
  where observation_kind='daily_confirmation';
create unique index price_history_source_operation_unique
  on public.price_history(identity_series_id,source_importer,source_run_id,observation_kind)
  where identity_series_id is not null;

create function public.record_identity_proven_price_observation(
  p_offer_id bigint,
  p_observation_kind text,
  p_source_run_id text,
  p_source_importer text,
  p_existing_history_id bigint default null
) returns jsonb
language plpgsql volatile security definer set search_path=pg_catalog,public,pg_temp as $recorder$
declare
  v_offer public.offers%rowtype;
  v_mapping public.retailer_products%rowtype;
  v_variant public.product_variants%rowtype;
  v_product public.products%rowtype;
  v_retailer public.retailers%rowtype;
  v_policy public.price_observation_producers%rowtype;
  v_identity jsonb;
  v_fingerprint text;
  v_series_id bigint;
  v_history_id bigint;
  v_gtin text;
  v_unit_count integer;
  v_unit_type text;
  v_flags text[]:='{}';
  v_previous public.price_history%rowtype;
  v_previous_two public.price_history%rowtype;
  v_status text;
begin
  if p_offer_id is null or p_offer_id<=0 then
    return jsonb_build_object('status','IDENTITY_OBSERVATION_SKIPPED','reason','INVALID_OFFER_ID');
  end if;
  if p_observation_kind not in ('offer_created','delivered_price_changed','daily_confirmation') then
    return jsonb_build_object('status','IDENTITY_OBSERVATION_SKIPPED','reason','UNSUPPORTED_OBSERVATION_KIND');
  end if;
  if p_source_run_id is null or p_source_run_id!~'^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$'
     or p_source_importer is null or p_source_importer!~'^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$' then
    return jsonb_build_object('status','IDENTITY_OBSERVATION_SKIPPED','reason','INVALID_SOURCE_PROVENANCE');
  end if;

  select * into v_offer from public.offers where id=p_offer_id for update;
  if not found then return jsonb_build_object('status','IDENTITY_OBSERVATION_SKIPPED','reason','OFFER_NOT_FOUND'); end if;
  select * into v_policy from public.price_observation_producers where retailer_id=v_offer.retailer_id and source_importer=p_source_importer;
  if not found or not v_policy.enabled then
    return jsonb_build_object('status','IDENTITY_OBSERVATION_SKIPPED','reason','PRODUCER_DISABLED','retailer_id',v_offer.retailer_id::text,'source_importer',p_source_importer);
  end if;

  select * into v_mapping from public.retailer_products where id=v_offer.retailer_product_id;
  select * into v_variant from public.product_variants where id=v_offer.product_variant_id;
  select * into v_product from public.products where id=v_offer.product_id;
  select * into v_retailer from public.retailers where id=v_offer.retailer_id;
  if v_mapping.id is null or v_variant.id is null or v_product.id is null or v_retailer.id is null
     or not v_product.is_active or v_product.merged_into_product_id is not null or not v_variant.is_active
     or v_mapping.product_id is distinct from v_offer.product_id or v_mapping.retailer_id is distinct from v_offer.retailer_id
     or v_mapping.product_variant_id is distinct from v_offer.product_variant_id or v_variant.product_id is distinct from v_offer.product_id
     or nullif(trim(v_mapping.external_product_id),'') is null
     or v_variant.pack_count is null or v_variant.pack_count<=0
     or v_variant.size_value is null or v_variant.size_value<=0 or v_variant.size_value::text='NaN'
     or nullif(trim(v_variant.size_unit),'') is null then
    return jsonb_build_object('status','IDENTITY_OBSERVATION_SKIPPED','reason','MISSING_OR_CONFLICTING_EXACT_IDENTITY');
  end if;
  if v_offer.price is null or v_offer.price<=0 or v_offer.price::text='NaN'
     or v_offer.shipping_cost is null or v_offer.shipping_cost<0 or v_offer.shipping_cost::text='NaN'
     or v_offer.total_price is null or v_offer.total_price<=0 or v_offer.total_price::text='NaN'
     or round(v_offer.price+v_offer.shipping_cost,2) is distinct from round(v_offer.total_price,2)
     or v_offer.in_stock is null or v_offer.last_checked_at is null then
    return jsonb_build_object('status','IDENTITY_OBSERVATION_SKIPPED','reason','INCOMPLETE_DELIVERED_PRICE_OR_STOCK');
  end if;

  v_unit_count:=case when coalesce(v_product.unit_pricing_verified,false) and v_product.unit_count>0 and nullif(trim(v_product.unit_type),'') is not null then v_product.unit_count else null end;
  v_unit_type:=case when v_unit_count is not null then v_product.unit_type else null end;
  v_gtin:=case
    when v_variant.gtin~'^[0-9]{8,14}$' then v_variant.gtin
    when v_mapping.match_method='gtin' and v_mapping.match_confidence=100 and v_mapping.external_gtin~'^[0-9]{8,14}$' then v_mapping.external_gtin
    else null end;
  v_identity:=jsonb_build_object(
    'identity_version',1,
    'offer_id',v_offer.id::text,
    'retailer_id',v_offer.retailer_id::text,
    'retailer_product_id',v_offer.retailer_product_id::text,
    'product_id',v_offer.product_id::text,
    'product_variant_id',v_offer.product_variant_id::text,
    'external_product_id',v_mapping.external_product_id,
    'external_variant_id',v_mapping.external_variant_id,
    'flavour',coalesce(v_variant.flavour_code,v_variant.flavour_label),
    'size_value',public.atomic_import_decimal_string(v_variant.size_value),
    'size_unit',v_variant.size_unit,
    'pack_count',v_variant.pack_count::text,
    'product_format',coalesce(v_variant.product_format,v_product.product_format),
    'unit_count',case when v_unit_count is null then null else to_jsonb(v_unit_count::text) end,
    'unit_type',v_unit_type,
    'gtin',v_gtin,
    'retailer_source',v_retailer.slug,
    'source_importer',p_source_importer,
    'currency','GBP');
  v_fingerprint:=public.retailer_catalogue_sha256_json(v_identity);

  insert into public.price_identity_series(
    identity_version,fingerprint,offer_id,retailer_id,retailer_product_id,product_id,product_variant_id,
    external_product_id,external_variant_id,flavour,size_value,size_unit,pack_count,product_format,
    unit_count,unit_type,gtin,retailer_source,source_importer,currency)
  values(1,v_fingerprint,v_offer.id,v_offer.retailer_id,v_offer.retailer_product_id,v_offer.product_id,v_offer.product_variant_id,
    v_mapping.external_product_id,v_mapping.external_variant_id,coalesce(v_variant.flavour_code,v_variant.flavour_label),
    v_variant.size_value,v_variant.size_unit,v_variant.pack_count,coalesce(v_variant.product_format,v_product.product_format),
    v_unit_count,v_unit_type,v_gtin,v_retailer.slug,p_source_importer,'GBP')
  on conflict(fingerprint) do nothing;
  select id into v_series_id from public.price_identity_series where fingerprint=v_fingerprint;

  if exists(select 1 from public.price_identity_series where offer_id=v_offer.id and id<>v_series_id) then
    v_flags:=array_append(v_flags,'IDENTITY_SERIES_RESET');
  end if;
  select * into v_previous from public.price_history
    where identity_series_id=v_series_id and (p_existing_history_id is null or id<>p_existing_history_id)
    order by checked_at desc,id desc limit 1;
  if v_previous.id is not null then
    if abs(v_offer.total_price-v_previous.total_price)>=100 then v_flags:=array_append(v_flags,'LARGE_ABSOLUTE_CHANGE'); end if;
    if v_previous.total_price>0 and abs(v_offer.total_price-v_previous.total_price)/v_previous.total_price>=0.5 then v_flags:=array_append(v_flags,'LARGE_PERCENT_CHANGE'); end if;
    if v_previous.in_stock=false and v_offer.in_stock=true then v_flags:=array_append(v_flags,'RETURNED_FROM_OOS'); end if;
    select * into v_previous_two from public.price_history
      where identity_series_id=v_series_id and id<>v_previous.id and (p_existing_history_id is null or id<>p_existing_history_id)
      order by checked_at desc,id desc limit 1;
    if v_previous_two.id is not null and round(v_previous_two.total_price,2)=round(v_offer.total_price,2)
       and round(v_previous.total_price,2)<>round(v_offer.total_price,2)
       and v_offer.last_checked_at-v_previous.checked_at<=interval '48 hours' then
      v_flags:=array_append(v_flags,'RAPID_REVERSAL');
    end if;
  end if;
  select coalesce(array_agg(distinct flag order by flag),'{}') into v_flags from unnest(v_flags) flag;
  v_status:=case when cardinality(v_flags)>0 then 'quarantined' else 'proven' end;

  if p_existing_history_id is not null then
    update public.price_history set
      identity_series_id=v_series_id,currency='GBP',in_stock=v_offer.in_stock,observation_kind=p_observation_kind,
      source_run_id=p_source_run_id,source_importer=p_source_importer,recorder_version=1,
      observation_date=(v_offer.last_checked_at at time zone 'UTC')::date,evidence_status=v_status,anomaly_flags=v_flags
    where id=p_existing_history_id and offer_id=v_offer.id and identity_series_id is null
      and price is not distinct from v_offer.price and shipping_cost is not distinct from v_offer.shipping_cost
      and total_price is not distinct from v_offer.total_price and checked_at is not distinct from v_offer.last_checked_at
    returning id into v_history_id;
    if v_history_id is null then return jsonb_build_object('status','IDENTITY_OBSERVATION_SKIPPED','reason','CURRENT_HISTORY_ROW_MISMATCH'); end if;
  else
    insert into public.price_history(offer_id,price,shipping_cost,total_price,checked_at,identity_series_id,currency,in_stock,
      observation_kind,source_run_id,source_importer,recorder_version,observation_date,evidence_status,anomaly_flags)
    values(v_offer.id,v_offer.price,v_offer.shipping_cost,v_offer.total_price,v_offer.last_checked_at,v_series_id,'GBP',v_offer.in_stock,
      p_observation_kind,p_source_run_id,p_source_importer,1,(v_offer.last_checked_at at time zone 'UTC')::date,v_status,v_flags)
    on conflict do nothing returning id into v_history_id;
    if v_history_id is null then
      select id into v_history_id from public.price_history
      where identity_series_id=v_series_id and (
        (source_importer=p_source_importer and source_run_id=p_source_run_id and observation_kind=p_observation_kind)
        or (observation_kind='daily_confirmation' and p_observation_kind='daily_confirmation' and observation_date=(v_offer.last_checked_at at time zone 'UTC')::date)
      ) order by id limit 1;
      return jsonb_build_object('status','IDENTITY_OBSERVATION_REPLAYED','price_history_id',v_history_id::text,'identity_series_id',v_series_id::text,'fingerprint',v_fingerprint);
    end if;
  end if;
  return jsonb_build_object('status','IDENTITY_OBSERVATION_RECORDED','price_history_id',v_history_id::text,
    'identity_series_id',v_series_id::text,'fingerprint',v_fingerprint,'evidence_status',v_status,'anomaly_flags',to_jsonb(v_flags));
end
$recorder$;

create or replace function public.retailer_catalogue_business_counts()
returns jsonb language sql stable security definer set search_path=pg_catalog,public,pg_temp as $counts$
  select jsonb_build_object(
    'products',(select count(*) from public.products),
    'product_variants',(select count(*) from public.product_variants),
    'retailer_products',(select count(*) from public.retailer_products),
    'offers',(select count(*) from public.offers),
    'price_history',(select count(*) from public.price_history where observation_kind is distinct from 'daily_confirmation'))
$counts$;

create or replace function public.apply_approved_product_import_plan(
  p_approval_id uuid,p_artifact_sha256 text,p_plan_fingerprint text,p_source_row_fingerprint text,
  p_retailer_id bigint,p_plan_kind text,p_run_id text) returns jsonb
language plpgsql volatile security definer set search_path=pg_catalog,public,pg_temp as $apply_approved$
declare
  v_approval public.approved_import_plans%rowtype;
  v_result jsonb;
  v_consumed_at timestamptz;
  v_observation jsonb;
  v_kind text;
begin
  select * into v_approval from public.approved_import_plans where id=p_approval_id for update;
  if not found then raise exception 'approved import plan not found'; end if;
  if v_approval.status<>'approved' or v_approval.consumed_at is not null then raise exception 'approved import plan already consumed'; end if;
  if v_approval.expires_at<=now() then raise exception 'approved import plan expired'; end if;
  if v_approval.artifact_sha256 is distinct from p_artifact_sha256 or v_approval.run_id is distinct from p_run_id
     or v_approval.plan_fingerprint is distinct from p_plan_fingerprint or v_approval.source_row_fingerprint is distinct from p_source_row_fingerprint
     or v_approval.retailer_id is distinct from p_retailer_id or v_approval.plan_kind is distinct from p_plan_kind then
    raise exception 'approved import plan metadata mismatch';
  end if;
  if v_approval.plan_fingerprint is distinct from v_approval.plan_json#>>'{meta,plan_fingerprint}'
     or v_approval.source_row_fingerprint is distinct from v_approval.plan_json#>>'{meta,source_row_fingerprint}'
     or v_approval.plan_kind is distinct from v_approval.plan_json#>>'{meta,plan_kind}'
     or v_approval.retailer_id is distinct from nullif(v_approval.plan_json#>>'{retailer,id}','')::bigint
     or md5(public.atomic_import_canonical_json(jsonb_set(v_approval.plan_json,'{meta,plan_fingerprint}','null'::jsonb,false)))<>v_approval.plan_fingerprint then
    raise exception 'approved import plan ledger integrity mismatch';
  end if;
  v_result:=public.apply_product_import_plan(v_approval.plan_json);
  v_kind:=case
    when v_result->>'offer_action'='create' then 'offer_created'
    when v_result->>'price_history_action'='create' then 'delivered_price_changed'
    else 'daily_confirmation' end;
  v_observation:=public.record_identity_proven_price_observation(
    (v_result->>'offer_id')::bigint,v_kind,v_approval.run_id,v_approval.source,
    nullif(v_result->>'price_history_id','')::bigint);
  if v_observation->>'status'='IDENTITY_OBSERVATION_RECORDED'
     and v_result->>'price_history_id' is null then
    v_result:=jsonb_set(v_result,'{price_history_id}',to_jsonb((v_observation->>'price_history_id')::bigint),true);
  end if;
  update public.approved_import_plans
    set status='consumed',consumed_at=now(),identity_observation_result=v_observation
    where id=v_approval.id returning consumed_at into v_consumed_at;
  return v_result||jsonb_build_object('approval_id',v_approval.id,'approval_status','consumed','consumed_at',v_consumed_at,
    'artifact_sha256',v_approval.artifact_sha256,'run_id',v_approval.run_id,'plan_fingerprint',v_approval.plan_fingerprint,
    'source_row_fingerprint',v_approval.source_row_fingerprint,'retailer_id',v_approval.retailer_id::text,'plan_kind',v_approval.plan_kind,
    'identity_observation',v_observation);
end
$apply_approved$;

alter table public.price_identity_series owner to postgres;
alter table public.price_observation_producers owner to postgres;
alter function public.reject_price_identity_series_mutation() owner to postgres;
alter function public.record_identity_proven_price_observation(bigint,text,text,text,bigint) owner to postgres;
alter function public.retailer_catalogue_business_counts() owner to postgres;
alter function public.apply_approved_product_import_plan(uuid,text,text,text,bigint,text,text) owner to postgres;

alter table public.price_identity_series enable row level security;
alter table public.price_identity_series force row level security;
alter table public.price_observation_producers enable row level security;
alter table public.price_observation_producers force row level security;
revoke all on table public.price_identity_series,public.price_observation_producers from public,anon,authenticated,service_role;
revoke all on sequence public.price_identity_series_id_seq from public,anon,authenticated,service_role;
revoke all on function public.reject_price_identity_series_mutation(),
  public.record_identity_proven_price_observation(bigint,text,text,text,bigint),
  public.retailer_catalogue_business_counts() from public,anon,authenticated,service_role;
revoke all on function public.apply_approved_product_import_plan(uuid,text,text,text,bigint,text,text) from public,anon,authenticated;
grant execute on function public.apply_approved_product_import_plan(uuid,text,text,text,bigint,text,text) to service_role;

commit;
