begin;

set local lock_timeout='5s';
set local statement_timeout='120s';

do $apply$
declare
  v_target jsonb:=public.retailer_catalogue_actual_database_target();
  v_authority constant text:='owner-chat-2026-08-26-complete-fit-house-safe-batch-15';
  v_config_sha256 constant text:='69316475e96e470840874a2eeeffa7f4a19319a437e6d947da101c4668267fb7';
  v_manifest_sha256 constant text:='a1e596f7707c851534e04e30d13f4289439449556787c572736e77b279c75292';
  v_scope constant jsonb:='[
    {"mode":"create","product_id":679,"product":"Mutant Creakong Advanced Creatine 1kg","default_variant_id":532,"mapping_id":689,"offer_id":697,"external_product_id":"10028457820400","external_variant_id":"49744956850416","external_sku":null,"external_options":null,"url":"https://fithouse.uk/products/mutant-creakong-advanced-creatine-1kg?variant=49744956850416","variant_key":"1000g","display_name":"1kg","flavour_code":null,"flavour_label":null,"size_value":1000,"size_unit":"g","pack_count":1,"product_format":"powder","price":26.99,"shipping":3.99,"total":30.98,"in_stock":false},
    {"mode":"create","product_id":680,"product":"PER4M Micronised Creatine 150g","default_variant_id":535,"mapping_id":690,"offer_id":698,"external_product_id":"10028467093744","external_variant_id":"49744981426416","external_sku":null,"external_options":null,"url":"https://fithouse.uk/products/per4m-micronised-creatine-150g?variant=49744981426416","variant_key":"150g","display_name":"150g","flavour_code":null,"flavour_label":null,"size_value":150,"size_unit":"g","pack_count":1,"product_format":"powder","price":7.99,"shipping":3.99,"total":11.98,"in_stock":true},
    {"mode":"create","product_id":681,"product":"Doctor''s Best Pure Collagen Peptides 417g","default_variant_id":539,"mapping_id":701,"offer_id":699,"external_product_id":"10034753143024","external_variant_id":"49768736948464","external_sku":null,"external_options":null,"url":"https://fithouse.uk/products/doctors-best-pure-collagen-peptides-417g?variant=49768736948464","variant_key":"417g","display_name":"417g","flavour_code":null,"flavour_label":null,"size_value":417,"size_unit":"g","pack_count":1,"product_format":"powder","price":44.99,"shipping":3.99,"total":48.98,"in_stock":true},
    {"mode":"rebind","product_id":688,"product":"TBJP Berberine 60 Capsules","default_variant_id":549,"target_variant_id":2891,"mapping_id":708,"offer_id":706,"external_product_id":"10028557009136","external_variant_id":"49745349804272","external_sku":null,"external_options":null,"url":"https://fithouse.uk/products/tbjp-berberine-60-caps?variant=49745349804272","variant_key":"60-servings","display_name":"60 Servings","flavour_code":null,"flavour_label":null,"size_value":60,"size_unit":"servings","pack_count":1,"price":14.99,"shipping":3.99,"total":18.98,"in_stock":true},
    {"mode":"create","product_id":694,"product":"OstroVit Pure Glycine 200g","default_variant_id":565,"mapping_id":736,"offer_id":712,"external_product_id":"8493486047472","external_variant_id":"45060015816944","external_sku":null,"external_options":null,"url":"https://fithouse.uk/products/ostrovit-pure-glycine-200-g-natural?variant=45060015816944","variant_key":"natural-200g","display_name":"200g / Natural","flavour_code":"natural","flavour_label":"Natural","size_value":200,"size_unit":"g","pack_count":1,"product_format":"powder","price":5.99,"shipping":3.99,"total":9.98,"in_stock":false},
    {"mode":"create","product_id":705,"product":"Now Foods Taurine Powder 227g","default_variant_id":581,"mapping_id":748,"offer_id":724,"external_product_id":"8511414534384","external_variant_id":"45128091402480","external_sku":null,"external_options":null,"url":"https://fithouse.uk/products/now-foods-taurine-powder-227g?variant=45128091402480","variant_key":"227g","display_name":"227g","flavour_code":null,"flavour_label":null,"size_value":227,"size_unit":"g","pack_count":1,"product_format":"powder","price":14.99,"shipping":3.99,"total":18.98,"in_stock":true},
    {"mode":"create","product_id":706,"product":"Now Foods MSM Powder 227g","default_variant_id":582,"mapping_id":749,"offer_id":725,"external_product_id":"8493494370544","external_variant_id":"45060077060336","external_sku":null,"external_options":null,"url":"https://fithouse.uk/products/now-foods-msm-powder-227g?variant=45060077060336","variant_key":"227g","display_name":"227g","flavour_code":null,"flavour_label":null,"size_value":227,"size_unit":"g","pack_count":1,"product_format":"powder","price":12.99,"shipping":3.99,"total":16.98,"in_stock":true},
    {"mode":"create","product_id":719,"product":"Osavi Colostrum Powder 100g","default_variant_id":598,"mapping_id":800,"offer_id":738,"external_product_id":"8333749092592","external_variant_id":"44263526629616","external_sku":null,"external_options":null,"url":"https://fithouse.uk/products/colostrum-1200-mg-powder-100-grams?variant=44263526629616","variant_key":"unflavoured-100g","display_name":"100g / Unflavoured","flavour_code":"unflavoured","flavour_label":"Unflavoured","size_value":100,"size_unit":"g","pack_count":1,"product_format":"powder","price":24.99,"shipping":3.99,"total":28.98,"in_stock":true},
    {"mode":"create","product_id":720,"product":"Now Foods Collagen Peptides Powder 227g","default_variant_id":599,"mapping_id":801,"offer_id":739,"external_product_id":"8493491585264","external_variant_id":"45060053762288","external_sku":null,"external_options":null,"url":"https://fithouse.uk/products/now-foods-collagen-peptides-powder-227g?variant=45060053762288","variant_key":"227g","display_name":"227g","flavour_code":null,"flavour_label":null,"size_value":227,"size_unit":"g","pack_count":1,"product_format":"powder","price":19.99,"shipping":3.99,"total":23.98,"in_stock":true},
    {"mode":"create","product_id":725,"product":"Now Foods Organic Inulin Prebiotic Powder 227g","default_variant_id":621,"mapping_id":858,"offer_id":744,"external_product_id":"8968956084464","external_variant_id":"46453444935920","external_sku":null,"external_options":null,"url":"https://fithouse.uk/products/inulin-prebiotic-pure-powder-organic?variant=46453444935920","variant_key":"unflavoured-227g","display_name":"227g / Unflavoured","flavour_code":"unflavoured","flavour_label":"Unflavoured","size_value":227,"size_unit":"g","pack_count":1,"product_format":"powder","price":13.99,"shipping":3.99,"total":17.98,"in_stock":true},
    {"mode":"create","product_id":727,"product":"7Nutrition Citrulline Malate 250g","default_variant_id":633,"mapping_id":860,"offer_id":746,"external_product_id":"8147551846640","external_variant_id":"43582764876016","external_sku":null,"external_options":null,"url":"https://fithouse.uk/products/7-nutrition-citrulline-malate-250g?variant=43582764876016","variant_key":"unflavoured-250g","display_name":"250g / Unflavoured","flavour_code":"unflavoured","flavour_label":"Unflavoured","size_value":250,"size_unit":"g","pack_count":1,"product_format":"powder","price":14.99,"shipping":3.99,"total":18.98,"in_stock":true},
    {"mode":"create","product_id":732,"product":"7Nutrition Vitamin C Pure Powder 250g","default_variant_id":630,"mapping_id":865,"offer_id":751,"external_product_id":"9176635834608","external_variant_id":"46992502718704","external_sku":null,"external_options":null,"url":"https://fithouse.uk/products/7nutrition-vitamin-c-pure-250g?variant=46992502718704","variant_key":"unflavoured-250g","display_name":"250g / Unflavoured","flavour_code":"unflavoured","flavour_label":"Unflavoured","size_value":250,"size_unit":"g","pack_count":1,"product_format":"powder","price":8.99,"shipping":3.99,"total":12.98,"in_stock":false},
    {"mode":"create","product_id":733,"product":"Animal Flex Powder Cherry Berry 369g","default_variant_id":634,"mapping_id":866,"offer_id":752,"external_product_id":"9174925803760","external_variant_id":"49768841904368","external_sku":null,"external_options":null,"url":"https://fithouse.uk/products/animal-flex-powder-cherry-berry-369g?variant=49768841904368","variant_key":"cherry-berry-369g","display_name":"369g / Cherry Berry","flavour_code":"cherry berry","flavour_label":"Cherry Berry","size_value":369,"size_unit":"g","pack_count":1,"product_format":"powder","price":37.99,"shipping":3.99,"total":41.98,"in_stock":true},
    {"mode":"rebind","product_id":508,"product":"GYM HIGH Shred Mode 60 Capsules","default_variant_id":435,"target_variant_id":2975,"mapping_id":947,"offer_id":761,"external_product_id":"9673951019248","external_variant_id":"48121139658992","external_sku":null,"external_options":null,"url":"https://fithouse.uk/products/gym-high-shred-mode-60-capsules?variant=48121139658992","variant_key":"60-servings","display_name":"60 Servings","flavour_code":null,"flavour_label":null,"size_value":60,"size_unit":"servings","pack_count":1,"price":39.99,"shipping":3.99,"total":43.98,"in_stock":true},
    {"mode":"rebind","product_id":1,"product":"GYM HIGH CREA-4 Elite Capsules","default_variant_id":559,"target_variant_id":2965,"mapping_id":2098,"offer_id":1912,"external_product_id":"8341423587568","external_variant_id":"44288495091952","external_sku":null,"external_options":{},"url":"https://fithouse.uk/products/gym-high-crea-4-elite-60-servings?variant=44288495091952","variant_key":"60-servings","display_name":"60 Servings","flavour_code":null,"flavour_label":null,"size_value":60,"size_unit":"servings","pack_count":1,"price":25.99,"shipping":3.99,"total":29.98,"in_stock":true}
  ]'::jsonb;
  e record; v_target_variant_id bigint; v_rows integer; v_mapping_before jsonb; v_offer_before jsonb;
  v_products_before bigint; v_variants_before bigint; v_mappings_before bigint; v_offers_before bigint; v_history_before bigint; v_series_before bigint;
begin
  if current_user<>'postgres' or v_target->>'target_environment'<>'PRODUCTION'
    or v_target->>'project_ref'<>'aftboxmrdgyhizicfsfu' or v_target->>'database_identity'<>'supplementscout-production:aftboxmrdgyhizicfsfu'
    or v_authority<>'owner-chat-2026-08-26-complete-fit-house-safe-batch-15'
    or v_config_sha256!~'^[0-9a-f]{64}$' or v_manifest_sha256!~'^[0-9a-f]{64}$' then raise exception 'Fit House batch 15 authority, evidence or target mismatch'; end if;
  if jsonb_array_length(v_scope)<>15 or (select count(*) from jsonb_array_elements(v_scope) x where x->>'mode'='create')<>12
    or (select count(*) from jsonb_array_elements(v_scope) x where x->>'mode'='rebind')<>3
    or (select count(distinct (x->>'mapping_id')::bigint) from jsonb_array_elements(v_scope) x)<>15
    or exists(select 1 from jsonb_array_elements(v_scope) x where (x->>'mapping_id')::bigint in (687,2063,2084,2099,2107,2123)) then raise exception 'Fit House batch 15 scope mismatch'; end if;
  perform pg_advisory_xact_lock(hashtextextended('supplementscout:fit-house-exact-pack:batch-15',0));
  select count(*) into v_products_before from public.products; select count(*) into v_variants_before from public.product_variants;
  select count(*) into v_mappings_before from public.retailer_products; select count(*) into v_offers_before from public.offers;
  select count(*) into v_history_before from public.price_history; select count(*) into v_series_before from public.price_identity_series;
  if (select count(*) from public.retailer_products rp join public.product_variants v on v.id=rp.product_variant_id where rp.retailer_id=9 and v.pack_count is not null and v.size_value is not null and nullif(trim(v.size_unit),'') is not null)<>166
    or (select count(*) from public.retailer_products where retailer_id=9)<>286 or (select count(*) from public.offers where retailer_id=9)<>286 then raise exception 'Fit House batch 15 baseline mismatch'; end if;
  for e in select * from jsonb_to_recordset(v_scope) as x(mode text,product_id bigint,product text,default_variant_id bigint,target_variant_id bigint,mapping_id bigint,offer_id bigint,external_product_id text,external_variant_id text,external_sku text,external_options jsonb,url text,variant_key text,display_name text,flavour_code text,flavour_label text,size_value numeric,size_unit text,pack_count integer,product_format text,price numeric,shipping numeric,total numeric,in_stock boolean) order by mapping_id loop
    if not exists(select 1 from public.products where id=e.product_id and name=e.product and is_active and merged_into_product_id is null for update)
      or not exists(select 1 from public.product_variants where id=e.default_variant_id and product_id=e.product_id and variant_key='default' and display_name='Default' and size_value is null and size_unit is null and pack_count is null and is_active and is_default for update)
      or exists(select 1 from public.price_identity_series where offer_id=e.offer_id) then raise exception 'Fit House product or prior-series mismatch for mapping %',e.mapping_id; end if;
    select to_jsonb(rp) into v_mapping_before from public.retailer_products rp where rp.id=e.mapping_id and rp.retailer_id=9 and rp.product_id=e.product_id and rp.product_variant_id=e.default_variant_id and rp.external_product_id=e.external_product_id and rp.external_variant_id=e.external_variant_id and rp.external_sku is not distinct from e.external_sku and coalesce(rp.external_options,'{}'::jsonb)=coalesce(e.external_options,'{}'::jsonb) and rp.external_url=e.url for update;
    select to_jsonb(o) into v_offer_before from public.offers o where o.id=e.offer_id and o.retailer_id=9 and o.product_id=e.product_id and o.product_variant_id=e.default_variant_id and o.retailer_product_id=e.mapping_id and o.price=e.price and o.shipping_cost=e.shipping and o.total_price=e.total and o.in_stock=e.in_stock and o.url=e.url for update;
    if v_mapping_before is null or v_offer_before is null then raise exception 'Fit House binding or commercial mismatch for mapping %',e.mapping_id; end if;
    if e.mode='create' then
      if exists(select 1 from public.product_variants where product_id=e.product_id and variant_key=e.variant_key) then raise exception 'Fit House target variant already exists for mapping %',e.mapping_id; end if;
      insert into public.product_variants(product_id,variant_key,display_name,flavour_code,flavour_label,size_value,size_unit,pack_count,product_format,gtin,image,nutrition_override,is_default,is_active)
      values(e.product_id,e.variant_key,e.display_name,e.flavour_code,e.flavour_label,e.size_value,e.size_unit,e.pack_count,e.product_format,null,null,'{}'::jsonb,false,true) returning id into v_target_variant_id;
    elsif e.mode='rebind' then
      v_target_variant_id:=e.target_variant_id;
      if not exists(select 1 from public.product_variants where id=v_target_variant_id and product_id=e.product_id and variant_key=e.variant_key and display_name=e.display_name and flavour_code is not distinct from e.flavour_code and flavour_label is not distinct from e.flavour_label and size_value=e.size_value and size_unit=e.size_unit and pack_count=e.pack_count and is_active and not is_default for update) then raise exception 'Fit House existing target mismatch for mapping %',e.mapping_id; end if;
    else raise exception 'Fit House unsupported mode for mapping %',e.mapping_id; end if;
    update public.retailer_products set product_variant_id=v_target_variant_id where id=e.mapping_id and retailer_id=9 and product_variant_id=e.default_variant_id;
    get diagnostics v_rows=row_count; if v_rows<>1 then raise exception 'Fit House mapping move affected % rows',v_rows; end if;
    update public.offers set product_variant_id=v_target_variant_id where id=e.offer_id and retailer_product_id=e.mapping_id and product_variant_id=e.default_variant_id;
    get diagnostics v_rows=row_count; if v_rows<>1 then raise exception 'Fit House offer move affected % rows',v_rows; end if;
    if not exists(select 1 from public.retailer_products rp join public.offers o on o.retailer_product_id=rp.id where rp.id=e.mapping_id and o.id=e.offer_id and rp.product_variant_id=v_target_variant_id and o.product_variant_id=v_target_variant_id and (to_jsonb(rp)-'product_variant_id')=(v_mapping_before-'product_variant_id') and (to_jsonb(o)-'product_variant_id')=(v_offer_before-'product_variant_id')) then raise exception 'Fit House preservation mismatch for mapping %',e.mapping_id; end if;
  end loop;
  if (select count(*) from public.products)<>v_products_before or (select count(*) from public.product_variants)<>v_variants_before+12
    or (select count(*) from public.retailer_products)<>v_mappings_before or (select count(*) from public.offers)<>v_offers_before
    or (select count(*) from public.price_history)<>v_history_before or (select count(*) from public.price_identity_series)<>v_series_before
    or (select count(*) from public.retailer_products rp join public.product_variants v on v.id=rp.product_variant_id where rp.retailer_id=9 and v.pack_count is not null and v.size_value is not null and nullif(trim(v.size_unit),'') is not null)<>181
    or (select count(*) from public.retailer_products where retailer_id=9)<>286 or (select count(*) from public.offers where retailer_id=9)<>286 then raise exception 'Fit House batch 15 postcondition mismatch'; end if;
end $apply$;

commit;
