begin;

alter table public.product_match_review_queue
  add column retailer_id bigint references public.retailers(id) on delete restrict,
  add column retailer_product_id bigint references public.retailer_products(id) on delete restrict,
  add column offer_id bigint references public.offers(id) on delete restrict,
  add column current_product_id bigint references public.products(id) on delete restrict,
  add column current_variant_id bigint references public.product_variants(id) on delete restrict,
  add column proposed_product_id bigint references public.products(id) on delete restrict,
  add column proposed_variant_id bigint references public.product_variants(id) on delete restrict,
  add column review_status text,
  add column review_kind text,
  add column operation_type text,
  add column before_state jsonb,
  add column proposed_state jsonb,
  add column impact_summary jsonb not null default '{}'::jsonb,
  add column source_evidence jsonb not null default '{}'::jsonb,
  add column source_captured_at timestamptz,
  add column expires_at timestamptz,
  add column workflow_run_url text,
  add column artifact_url text;

alter table public.product_match_review_queue
  add constraint product_match_review_queue_review_status_check check (
    review_status is null or review_status in (
      'PENDING', 'APPROVED', 'REJECTED', 'IGNORED', 'EXPIRED',
      'EXECUTING', 'EXECUTED', 'FAILED'
    )
  ),
  add constraint product_match_review_queue_review_kind_check check (
    review_kind is null or review_kind in (
      'IDENTITY_CONFLICT', 'COMMERCIAL_CHANGE', 'SOURCE_FAILURE',
      'MAPPING_DRIFT', 'POLICY_REVIEW'
    )
  ),
  add constraint product_match_review_queue_operation_type_length_check check (
    operation_type is null or length(trim(operation_type)) between 1 and 100
  ),
  add constraint product_match_review_queue_automation_state_shape_check check (
    (before_state is null or jsonb_typeof(before_state) = 'object')
    and (proposed_state is null or jsonb_typeof(proposed_state) = 'object')
    and jsonb_typeof(impact_summary) = 'object'
    and jsonb_typeof(source_evidence) = 'object'
  ),
  add constraint product_match_review_queue_automation_expiry_check check (
    expires_at is null or source_captured_at is null or expires_at > source_captured_at
  );

create unique index product_match_review_queue_offer_fingerprint_unique
  on public.product_match_review_queue (retailer_id, offer_id, source_row_fingerprint)
  where retailer_id is not null and offer_id is not null;

create index product_match_review_queue_automation_status_idx
  on public.product_match_review_queue (review_status, retailer_id, updated_at desc)
  where review_status is not null;

create table public.product_match_review_events (
  id bigint generated by default as identity primary key,
  review_id bigint not null references public.product_match_review_queue(id) on delete restrict,
  event_type text not null check (event_type in ('CREATED', 'DECISION_CHANGED', 'STATE_CHANGED', 'EVIDENCE_REFRESHED')),
  actor text not null check (length(trim(actor)) between 1 and 200),
  source_row_fingerprint text not null check (source_row_fingerprint ~ '^[0-9a-f]{64}$'),
  before_snapshot jsonb,
  after_snapshot jsonb not null check (jsonb_typeof(after_snapshot) = 'object'),
  created_at timestamptz not null default now()
);

create index product_match_review_events_review_created_idx
  on public.product_match_review_events (review_id, created_at desc);

alter table public.product_match_review_events enable row level security;
revoke all on table public.product_match_review_events from public, anon, authenticated, service_role;
revoke all on sequence public.product_match_review_events_id_seq from public, anon, authenticated, service_role;
grant select, insert on table public.product_match_review_events to service_role;
grant usage, select on sequence public.product_match_review_events_id_seq to service_role;

create or replace function public.audit_product_match_review_event()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_event_type text;
  v_actor text;
begin
  if tg_op = 'INSERT' then
    v_event_type := 'CREATED';
  elsif old.decision is distinct from new.decision
     or old.review_status is distinct from new.review_status then
    v_event_type := case
      when old.decision is distinct from new.decision then 'DECISION_CHANGED'
      else 'STATE_CHANGED'
    end;
  elsif old.source_row_fingerprint is distinct from new.source_row_fingerprint
     or old.source_evidence is distinct from new.source_evidence then
    v_event_type := 'EVIDENCE_REFRESHED';
  else
    return new;
  end if;

  v_actor := coalesce(nullif(new.reviewed_by, ''), current_user);
  insert into public.product_match_review_events (
    review_id, event_type, actor, source_row_fingerprint,
    before_snapshot, after_snapshot
  ) values (
    new.id, v_event_type, v_actor, new.source_row_fingerprint,
    case when tg_op = 'INSERT' then null else to_jsonb(old) end,
    to_jsonb(new)
  );
  return new;
end;
$$;

alter function public.audit_product_match_review_event() owner to postgres;
revoke all on function public.audit_product_match_review_event() from public, anon, authenticated;
grant execute on function public.audit_product_match_review_event() to service_role;

create trigger product_match_review_queue_immutable_audit
after insert or update on public.product_match_review_queue
for each row execute function public.audit_product_match_review_event();

comment on table public.product_match_review_events is
  'Append-only audit history for review queue evidence, decisions and lifecycle. It never authorizes catalogue writes.';
comment on column public.product_match_review_queue.review_status is
  'Review and protected-execution lifecycle. Catalogue mutation remains delegated to existing guarded importer RPCs.';
comment on column public.product_match_review_queue.source_evidence is
  'Bounded source-attempt evidence, including last success, first/last failure, attempt count and error class.';

commit;
